### ISSUE TITLE
Optimize the default Neos Hands

### ISSUE THREAD

**Issue by H3BO3** [Neos-Metaverse/NeosPublic#1002]
Currently each of the default Neos hands are 52k tris each. This has been shown to have a decent impact on rendering performance based on tests run by the JP community. I am unsure if the NeosBot avatar has the same hands and if they need to be optimized as well. Multiple users have been concerned about the hands issue for a while now and would appreciate them being optimized.

**Comment by Frooxius** [comment]
We do plan on making LOD's for them so they scale better with multiple users. They're originally designed as part of the MTC experience and placeholder before user switches to another avatar, but LOD's should help with their usability with multiple users using them.

**Comment by H3BO3** [comment]
LODs are good, but is there a reason that the max needs to reach 52k tris either way? Or will the max LOD be reduced as well?

**Comment by Frooxius** [comment]
Potentially. Your hands are something you see really up close, so since the goal of these was to be part of the starter experience where a lot of focus would be on hand interactions, they were designed as high definition models. Modern hardware can push a lot of triangles, but on weaker one we can switch to a lower LOD. For other users in populated worlds you'd see lower LOD as well.

**Comment by H3BO3** [comment]
I can understand that, but on just a single hand model it seems... excessive. That's more tris than are on most avatars

**Comment by Frooxius** [comment]
It depends on the quality standard you set. Our goal for MTC was to create an impressive experience that will showcase things that you can do in Neos. It's a fraction of the total triangle count you push in worlds with many users, so rendering them at high detail just for yourself is worth it. LODs will help when there's multiple users in the world.

**Comment by TehTurk** [comment]
I agree, not to get super heavy on optimizations are Hand LODS even a thing? I figured you always want a nice balance between performance and appearance. 50k is like your typical budget for say like a Main character of a game. So that's like 2 characters on your hands. Wouldn't it be more reasonable to reduce their poly count?

**Comment by Frooxius** [comment]
Like I said in my previous message, it depends on your quality target. Modern games have pretty big budgets for things you see up close, because that's where the player/user looks. Hands are something you see really up close so they serve that purpose from the player's POV. Keep in mind that the current hands are also used on the Quest, which is mobile hardware with fraction of the performance, which doesn't have trouble pushing 72 FPS with them.

We'll reduce what we can when we do another pass and do the LODs, which handle how things scale up with multiple instances and for other players. I can't offer you anything more beyond that right now.

**Comment by TehTurk** [comment]
Ah I see now thanks for at least that little info of the Quest, I didn't consider it much in hindsight! Just the concept of Hand LODS seemed very out there for me. Hey no rush :) I'm not demanding stuff right now appreciate you even have anything, I was more so asking more on the how/why.

**Comment by mralext20** [comment]
some of discussion in the discord ( see here: https://discordapp.com/channels/402159838827905024/533553295956901918/760757854285856818 ) lead to comparison relating to Half-Life: Alyx's hands, where the base hand is 21K tris, and the grabbity glove attachment is an attitional 21K tris, and how VR chat's quest poly limit for recommended for quest is a mear 5K polys.

not that neos is vrchat.

**Comment by Frooxius** [comment]
In 2021.3.31.528 we have released new version of head and hands avatars, which features reworked version of the hands with significantly less geometry!
