### ISSUE TITLE
[Logix / Bug] DynamicVariableInput`1 breaks after reparent

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Neos-Metaverse/NeosPublic#1057]
Using DynamicVariableInput (Any type) breaks after a reparent (grabbing or blueprints as an example) and has to be packed and unpacked to get it to work again.

**Comment by 3x1t-5tyl3** [comment]
Connection to the variable space. It seems to behave like it probably should in code but makes it impossible to code with.

The parenting doesn't matter. As soon as it's grabbed the connection is lost to whatever you're interacrint within it. For example. If packed -> unpack -> grab -> connection lost to the space until it's packed and unpacked again.

The space is on a seperate object. In this case an empty object me, Turk and a few others were testing around with.

**Comment by TehTurk** [comment]
Too help if it adds, it's due how the nature of how easy it is to break an InputVariable 's spot in the hierachy. As it's more sensitive then a DynamicImpulseReciever for determining how it's affected. Like say you Pulse for a Reciever, but unless it's packed or under the space it just doesn't respond. Samewise for a DVInput. 

One thing that was suggested was requiring the namespace/target to be defined as a slot input so it always respects that.

**Comment by Frooxius** [comment]
If you move the DynamicVariableInput outside of the hierarchy then it will naturally unlink with the DynamicVariableSpace in that hierarchy, that's how the dynamic variable system works. However I'm not sure why would you need to pack it again? Releasing grabbed node will put it back under original hierarchy, so it should relink. Is this not happening?

If you want to provide the Slot dynamically as input use ReadVariable node instead, but note that it's a lot less efficient, as it requires lookups every time and it won't trigger changes, since the hierarchy it reads from is provided as input on read.

**Comment by TehTurk** [comment]
Its more an issue of use/design to the common user. Yes Grabbing doesn't break it as it reparents as that's intended by the grabbable behavior but there's also the aspect of it's fragility if something gets pulled off its parent with a blueprint and a user is using it to make their logix and it doesnt work. I'm still trying.to wrap my head around it's proper use case if you can give some examples of how to use the DVInput because it just seems easier/simpler to use the Component form instead. 

Ah okay, that's what you had in mind hmm.

**Comment by Frooxius** [comment]
Blueprints are a community made tool and not an official one. If they move things out of the hierarchy it will break anything that depends on that. There's not really anything that could be done, they're not fully in sync with how is LogiX designed. 

I plan on making a video tutorial to show what you can do with them and what patterns you should follow, maybe on one of the livestreams.

**Comment by mralext20** [comment]
Perhaps a solution to grabbing breaking the link would be to have the input node spawn with a slider on it rather than a grabbable?

**Comment by Earthmark** [comment]
It may be possible to get blueprints to not break dynamics, I think saying that whole workflow and tool is an invalid usage is not gonna blow over too well, so I'll try some things and see if this can be mitigated.

**Comment by Frooxius** [comment]
@Earthmark There aren't really any good choices on Neos' side. They would require either some nasty hacks and checks for blueprints in the dynamic variable code (which would likely introduce a lot of bugs, performance issues and make the system really hard to work with) or use a completely different system that doesn't rely on the hierarchy.

As a rule, I won't compromise the architectural design of systems based on quirks of some user made content, it constrains things too much. The blueprint system is what will have to be adapted, likely by making sure it's part of the object's hierarchy (this is how the official system will work).

@MR-Alex42 Using Slider for nodes seems like it might be a good idea in general, I can try it out and see if there are any side effects.

**Comment by Earthmark** [comment]
Apologies, I should have been more specific. I was thinking blueprints could be made to work through this, like if they used visual parent or such.
I do agree that if the goal is that it's in the heiarchy then alright, I'm a bit confused why this and dynamic impulses are the only nodes that rely on this behavior but alright.

I think this may make better tools in the long run as well, a blueprint tool that can recognize logix and extract that logix to a staging area without reparenting it would make it much easier to debug and edit larger projects, particularly objects that move as well.

I think it may be good for testing as well, where dynamic variables make that kind of thing very easy (drop the logix into a fixture and done)
