### ISSUE TITLE
Add CopyGlobalScale component

### ISSUE THREAD

**Issue by H3BO3** [Neos-Metaverse/NeosPublic#1123]
Currently CopyGlobalTransform has drives for position and rotation, but not scale. I was wondering if this could be added since without it, it seems a little inconsistent.

**Comment by Frooxius** [comment]
The scale is omitted for a reason from global transform copy. GlobalScale should generally be considered read-only property and never assigned. This is because it's a lossy property, so any difference between rotation between the source and target object in the hierarchy will end up producing skewed transform and resulting scale won't do what you expect, since it's not necessarily possible to actually represent it exactly in the target space.

There could be a simplification of this. If the scale is uniform through the entire hierarchy, then it's ok to transform it without issues. I could add separate component which does that, but it wouldn't work for any non-uniform scale.

**Comment by H3BO3** [comment]
Ah, I see what you mean. I maintain uniform scales wherever I can so I would be able to utilize a separate component like that effectively. That would work nicely if the separate one could be added, thanks!

**Comment by ProbablePrime** [comment]
We have this component in Transform/Drivers now.
