### ISSUE TITLE
"Allow Object Saving" component

### ISSUE THREAD

**Issue by Ruikio** [Neos-Metaverse/NeosPublic#1134]
**Just to get it out of the way. I'm aware that the store system will probably do something like this.. sometime in the future of Neos.**

It'd be nice to add a component onto an object that says something along the lines of Allow saving of object? [ ] and you could check the box or uncheck. 

That way you could have a map be open for people to save random objects like you would normally hanging out but prevent them from saving certain objects.

Figured it could go under **_Add Component > Transform > Tagging > Allow object saving_**

Majority of my worlds don't let people go over moderator on publish so it wouldn't be a worry about Builder. I'd just like people to hang out in the world and spawn items and be silly without them saving things out of respect for certain objects. (Say for example.. having permission to use an item but they ask you to not have it distributed.)
Just since most of the worlds I help make end up being chill worlds. I hate restricting ALL SAVING just because some items people not wanting to get out. Say for example I drop a bunch of experimental Lounge drinks in a world just to add functionality to it and do 'product placement'. But it's a chill world and I don't want people to nab something that may not be intended on getting out or is experimental and may break something unintentionally.

The use case for this would allow people to enjoy the features of spawning and saving things in Neos in any world publicly but also restricting items in that world being saved.

Remixed it up a little from my post in the [#Bugs-and-feedback channel. ](https://discordapp.com/channels/402159838827905024/439422161657135106/764155719921827840)

**Comment by TehTurk** [comment]
#740 To link for Rukio to Read over as we discussed it :0

**Comment by ProbablePrime** [comment]
I'm linking #289 with a note that this sort of item is on the roadmap for consideration in this feature. Not to halt discussion but to let you know that Froox is most likely already thinking about items in this area and that feedback in this area is most likely valuable for this effort. 

And because someone else will link it if i dont :)

**Comment by TehTurk** [comment]
Appreciate it prime! Some of the issues are a bit all over in description

**Comment by Ruikio** [comment]
Something that was suggested by [Dante in the bugs-and-feedback channel](https://discordapp.com/channels/402159838827905024/439422161657135106/764183752816459846) , this also could be substituted via a permissions saving black list. 
In this instance, you could put a items you did not want to be saved under a parent and have the parent be blacklisted from saving. This would theoretically allow people to continue spawning / saving things they spawn out in a world but prevent them from grabbing things and saving things that are under this black listed parent.

It would be important to consider that upon grabbing something, since the object becomes under the active user upon grabbing, that this item keeps the saving prevention on it.


The idea that keeps people from saving things is the point of this thread. A component can surely be over ridden if for some reason the owner of the world leaves builder open to people on publish, yet adds the component anyway. Adding a blacklist to perms, to my understanding, means that only the world creator (Not the host of the session) can change permissions and is safe guarded even if builder is left open.

**Comment by Frooxius** [comment]
I'm not really sure about this one. Something like this wouldn't be secure by any means, it would be more of a hint "please don't save this", but I couldn't guarantee that people couldn't easily work around it. For that we need a lot more robust system, which is going to be license / object ID system: https://github.com/Frooxius/NeosPublic/issues/21

It is technically possible to do the simple one in the meanwhile, but after experience with SimpleAvatarProtection, which started with a similar request, I don't think it's a good idea. People tend to overestimate how much it actually protects things and use it for things it was never meant to be used. The tagging wouldn't help it much, it would make the system weaker than it is right now.

Then a lot of time has to be spent patching those cases, which also make other code messier and make other features harder to work on because of the messiness. I think it might be better to just do the proper system instead, since it ends up taking same or less time in the end and offers more robust solution rather than patchy one instead.

The Object ID / License system is pretty high on the priority list right now, I could see even about bumping it up some more before full physics is implemented for example.
