### ISSUE TITLE
[Bug] Text renderer using 100% cpu

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Neos-Metaverse/NeosPublic#1146]
Text renderer under these conditions on a valuefield or directly on text renderer causing alot of cpu usage and subsequent loss of tracking/crashing
![Photo in Legacy Grid Space - Private](https://user-images.githubusercontent.com/61988002/95829968-42340580-0d37-11eb-8a2e-da53ebbf515a.png)

**Comment by Frooxius** [comment]
100 % CPU being used isn't necessarily a bug on itself, the text rendering system as many others are heavily parallelized and will utilize all available CPU cores to do the background work.

I don't understand how it relates to loss of tracking though? Is there anything that indicates the cause of the crash? Any crash log or something like that?

Is it possible to send that setup to me for testing?

**Comment by Aerizeon** [comment]
The setup isn't any more involved than the nodes you see in the image.
The loop completes fine, and there are no errors when writing to the ValueField<String>.
However, if you open an inspector on that ValueField<String>, or you write to a TextRenderer Value instead, after about 10 seconds or so, Neos will begin to use all available CPU, to the point of starving both SteamVR and the OS of CPU Time, which results in loss of head tracking, and eventually Neos Crashing.

I suspect this is an issue with rendering of certain (invalid?) characters, and not with the length of the string, since there are probably quite a few characters in that range that aren't valid codepoints.

The Neos logs do not appear to contain anything meaningful - They actually show a shutdown request in some instances, which isn't possible for me to do.

For Reference, my system specs (at the time of hosting the test sessions) are:
Intel Core i7-4790k + 32 GB Ram
AMD Radeon 5700XT
Windows 10

**Comment by 3x1t-5tyl3** [comment]
Just tested it and after closing down the game through alt f4 I also have a hard VR crash https://pastebin.com/BmwyKnnv

It also left neos open while my VR crashed. 
![image](https://user-images.githubusercontent.com/61988002/95835466-88409780-0d3e-11eb-980e-e60cd168f426.png)

For reference:
8700k + 32gb of 2400mhz ram
Asus Strix 1080ti
win10 - 2004

**Comment by Aerizeon** [comment]
http://cloudx.azurewebsites.net/open/world/U-Epsilion/R-e10a634a-a2fe-4d44-b57c-a8e033bb6208

**Comment by Frooxius** [comment]
Thanks, I'll have a look when I can. I don't think it's because of the invalid characters, those should just be ignored. However rendering 50000 unique characters requires Neos to fetch and render all of them into a glyph atlas (likely multiples of them actually), so that might be taking a bulk of the CPU usage. Although it's a bit odd, since we stressed the system quite a bit before, so it might be something else too. It's hard to tell without actually testing though, hence why I asked for the setup.
