### ISSUE TITLE
Fire on fail for the "Equip Tooltip" node

### ISSUE THREAD

**Issue by GalexY727** [Neos-Metaverse/NeosPublic#1164]
..if permissions don't allow the Tool to be equipped or otherwise failed to equip it (like having a tool already equipped and not force de-equipping it before hand).
An "OnFailed" output could prevent certain behaviours in logix when wanting to equip a tool where one does not have the permissions for.

**Comment by shiftyscales** [comment]
What 'certain behaviors' are you referring to, @GalexY727? Do you have any specific examples/use-cases in mind? Depending on how the Logix is setup, if the tool isn't equipped, it doesn't send an impulse, so subsequent Logix chained into it wouldn't run.

**Comment by ProbablePrime** [comment]
Spoke to Exit about this in game.

If a tooltip can't be equipped due to permissions please fire an outgoing impulse which signals failure
If a tooltip can't be equipped because one is already equipped in that hand AND DEQUIP EXISTING IS FALSE, please fire an impulse which signals failure.

The example given here was that they wanted to do some clean up of other state such as variables and animations if a tooltip fails to equip.

**Comment by shiftyscales** [comment]
I see. I assume this is in the context of a tooltip multiplexer, then.

**Comment by TehTurk** [comment]
Not typically, This can be also very essential with any tooltip setup, even RawDatas for games, or even certain affects for other tools.

**Comment by ProbablePrime** [comment]
Oh also can be found in:
- Custom Toolshelves
- Custom Context Menus
- Games that use raw data tooltip and the equip nodes(Oh hey Laser beam does this somewhere)

Thanks Shifty!

**Comment by Frooxius** [comment]
This has been added by @ProbablePrime in 2021.8.13.612! Thanks!
