### ISSUE TITLE
FBT Users have issues spawning with Common Spawn Area 

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Neos-Metaverse/NeosPublic#1342]
Concurrently FBT users kinda are in a bad situation because the CommonSpawnArea Component's default's make it so FBT users spawn in weird rotation. The tweak would be to change the default "RotationNode" and maybe "PositionNode" to "GroundProjectedHead".

This would ensure no weird rotational spawning.

Edit: Reproduceable steps:
1. Have FBT and create a new world
2. Spawn in weirdly rotated, E.G. When laying down or sitting with leg's crossed or anythingelse but flat foot rotation IRL.

AFAIK this issue is apparently older and kinda got forgotten.

**Comment by 3x1t-5tyl3** [comment]
It also applies when not in noclip btw. It just happens to flip them *before* they spawn in due to gravity.

**Comment by TehTurk** [comment]
Ah, okay! Thanks for clear up, I remember the conversation from ingame and remembered only seeing it occur due to NoClip.

**Comment by 3x1t-5tyl3** [comment]
Bumping this.
I've noticed that even in normal walk it still flips you. Which can be nauseating.
Definetly both position and rotation node needs to be GroundProjectedHead for FBT users to spawn properly/not in weird angles when not explicitly in walk mode.

**Comment by StarfishHidari** [comment]
the default rotation should definitely be either  root or ground projected head for FBT, I've had to change this on every spawn area I make and I'm suprised that wasn't always the default

**Comment by shadowpanther** [comment]
I also have to correct other worlds' owners on this issue. I don't have FBT, but sometimes I fall through the world on spawn because of the defaults. Setting the spawn to GroundProjectedHead fixes that.

**Comment by TehTurk** [comment]
Hi there! Is it possible if this could be done for the next build at all? This seems like a pretty simple change since it seems like the default enum change.

**Comment by StarfishHidari** [comment]
Hey this issue has been around for a while now and seems like a relatively simple change to add, has it just been overlooked or is there a reason it hasn't been changed?

**Comment by H3BO3** [comment]
@shiftyscales Why is this tagged as UI/UX? It's a component default enum change. Any news on this change being made yet?

**Comment by 3x1t-5tyl3** [comment]
Just to be clear what was requested in the post:

The tweak in question here is about changing the default Position-/RotationNode  from "Feet" to "GroundProjectedHead" for the "CommonSpawnArea" Component.

**Comment by StarfishHidari** [comment]
When I'm using full body I spawn sideways in almost every world and fall through the world because of this default value. Can we get this looked at?

It should be a simple enum change unless there's something else we're unaware of, but we haven't really been told if there's anything in the way of changing this.

**Comment by TehTurk** [comment]
Recently been going through the Labels and also checking with Shifty, UI/UX apparently was supposed to mean User Interfaces / User Experience hence the confusion @H3BO3 I'm going a few issues and trying to reconcile where this can be adjusted.

**Comment by H3BO3** [comment]
That makes no sense @TehTurk , UI is the interface, UX is the ease of use of the interface to accomplish a goal, those terms are related to design vs. functionality of only control interfaces, not component tweaks.

**Comment by TehTurk** [comment]
I'm aware this is why I'm going through it and looking at it right now.

**Comment by 3x1t-5tyl3** [comment]
What is going on with this? This is a hilariously small change is there anything blocking this? Did we overlook anything? Is there something more deeply nested that we (as the users) don't see here?

**Comment by AshtonSparx** [comment]
Haven't read through all the comments of this, but it happens when you're in flight as well.. To correct yourself, gotta go into Physical then back into fly/No-clip which is dumb, how hasn't this tweak been made yet?

**Comment by shiftyscales** [comment]
As another update on this issue, the proposed solution of just changing the default enum was decided to not be a suitable fix as it doesn't address the actual underlying issue- namely in the default foot value not functioning properly/as expected. So there'll be a bit more time before this issue can be addressed as it requires fixing the current default value rather than just modifying it/mitigating it.

**Comment by StarfishHidari** [comment]
We will work on focusing more on the issue in the future and not the solution, but could this issue have not received some sort of a reply explaining this? I really appreciate you posting on here and explaining rather than responding on discord, but this issue went 5 months without any reply. We asked "is there something we aren't aware of" multiple times and didn't get any reply, so we really didn't have much at all to go off of and it just seemed like the issue wasn't even being noticed for the longest time.

The closest thing we got to a reply was the comment shifty had made on the discord, not on github, and probable had to copy over to here.

**Comment by shadowpanther** [comment]
I think we all have to work on proper communication. We players need to better explain what end results we need to achieve, not the means to get it (though the means could suggest some kind of intermediate solution). And the staff need to better explain what could or couldn't be done from their side and what is the proper way of fixing the issue.
