### ISSUE TITLE
Read Only Dynamic Variable

### ISSUE THREAD

**Issue by Earthmark** [Neos-Metaverse/NeosPublic#1371]
When defining configuration of an object via dynamic variables I am currently binding a dynamic variable to a slot's name, and using that as the configuration domain (it's for an auto-generated menu) (Part of the name is used as part of the dynamic variable name).

For instance, I have a slot that goes
Config:
  Option A (contains dynvar broadcasting the slot name as 'Config/Option A.Name')

However, I've noticed that if I make a duplicate of the slot, it's quite hard to get the new slot and the old slot to diverge name wise, as both slots are driven by the same name.

I've encountered this before when I want drop-in configuration options, I need to make a value copy from the source into the dynamic variable storage instead of driving that storage directly, however this is just more components.

If possible, can either the current dynamic variables support, or add a new dynamic variable component that does not modify the target storage with the value from the dynamic space, and instead only broadcasts a value into the dynamic variable space?

**Comment by Frooxius** [comment]
I'm not quite sure if I understand this use-case. If you don't want the dynamic variable to modify the existing variable, you should be using one of the one-way drivers, like DynamicValueVariableDriver. Those will never modify the dynamic variable in the space, only ever read it.

Having read only "variables" is a bit problematic, because it's not clear how to handle some scenarios. E.g. if you place multiple read-only variables within the same space, where each one has a different value, what would happen then? Those would conflict and the actual value would be something undefined or unexpected.

I'm not sure how to interpret this statement either: "add a new dynamic variable component that does not modify the target storage with the value from the dynamic space, and instead only broadcasts a value into the dynamic variable space?"

By definition, dynamic variable that broadcasts value into the dynamic variable space modifies the value in that space, that's one and the same operation.

**Comment by shiftyscales** [comment]
From my understanding of the issue from my own time in working with dynamic variables- it's a desire to have a dynamic variable that only accepts a value from a single source.

As a potential use-case, when I converted all of my existing avatar systems to dynamic variables, one of the first things that I did was to hook up the controller nodes to drive dynamic variables directly.

In this use-case I only ever want/need one data source to write to the variables- in this case, the value streams from the controllers (I'm currently doing this as there is no other means to directly access the value streams otherwise). So in this context, I won't ever be writing to those values anywhere else, they are strictly read-only in how I apply those variables. E.g. as boolean/float inputs only across the rest of my Logix/components.

Similarly, I have a dynamic variable that is set up to provide me with my current user scale (as a stand-in replacement for having to get my user root and user scale in Logix every single time) I instead drive a dynamic variable with my user scale again- as a 'read-only' variable that only accepts that one data source as its input- because in that context, it doesn't make sense for there to be any other value written to it other than what it already is/should be as driven by my user scale.

Effectively what is desired is a ValueCopy in 'dynamic variable' form.

**Comment by Frooxius** [comment]
If you want it to only be a single fixed source, then you should just use ValueCopy instead, using the dynamic system when you don't want it to be really dynamic is using the wrong tool for the job.

**Comment by Earthmark** [comment]
In this case I want a module to auto-attach to a values being broadcast in the model.
One such example is a dynamic variable that broadcasts the slot of a menu for a user, so spawning a new menu option from your inventory can easily find that menu and inject itself, without needing a heuristic to find the slot in question.

However, in some situations that slot value may accidently get overwritten, for instance:
Have this menu installed on an Avatar (Menu A) the Dynamic Variable points to A.

The user spawns a copy of the menu as an item in the world to show someone how to add the menu to their own avatar, Menu B is not under an avatar, so it's broadcasting a slot, but that slot isn't parented under a space so that's fine.
The user with menu A picks up menu B, now B and A are in the same space, with the same binding.
In this situation it is ambiguous I agree, in practice the system seems to use the latest updating value, as I said there is a workaround to this, it just takes extra value copies.
But if you don't use that workaround right now, and you bound the dynamic variable directly to a storage value, both A and B point to either A or B.
If A, the newly spawned menu will not work unless fixed, and if this is a context of installing it into a new avatar, then good chance it'll just add to the confusion.
If B, the user will be adding modules to the item version of the menu.

For this kind of a system I do agree there are vauge spaces, however those spaces tend to be transient. Like where your holding an item or duplicating a self referential item under a variable space to then move out out (or rebind it) so the issue is resolved shortly.

Personally I've had this come up just about every time I've had to deal with reference type dynamic variables (such as logix tutorial world, or the build-a-yote), I pretty much always seem to provide fixed references inside a dynamic variable space (logix tutorial world kind of does changes at runtime, but it's due to user interaction. The values are still for the most part broadcast only). With value style dynamic variables it comes up less often, but still sometimes as well.

**Comment by Earthmark** [comment]
I think in this case I'm using the dynamics system as named const static variables, because I don't see a good other way to have named const static variables that aren't slot name based, and the slot name approach has a lot of asterisks and issues.

**Comment by Earthmark** [comment]
This can be faked with a value copy driving into a dynamic variable output, so I think this may just be how it is for now.

The hope of this was a dynamic field that didn't attempt to write back to it's source, and would only write the value into the dynamic, but it seems like that's not the intended design.

For now I'll close this as #2555 is more clear and uses the new format
