### ISSUE TITLE
Request: add rendering for multipart Emoji characters

### ISSUE THREAD

**Issue by shadowpanther** [Neos-Metaverse/NeosPublic#1441]
There are a bunch of emoji glyphs that are defined by two or more Unicode characters. Things like country flags, human emojis with custom skin color, etc.
For example, a flag of Russia (🇷🇺) is represented by 🇷 U+1F1F7 and 🇺 U+1F1FA. When I try to paste those into Neos's TextRenderer, I get separate R and U glyphs instead:
![](https://cdn.discordapp.com/attachments/439422161657135106/784929748631420969/2020-12-06_02.49.10.webp)

**Comment by Frooxius** [comment]
This is a little bit more complicated, because those Emoji's are color glyphs, rather than standard curve-based ones (which are rendered using the MSDF) and we currently don't have a subsystem for rendering these yet (particularly determining that they're a different type of glyph and rasterizing them), although parts of it are already implemented.

I'm not fully sure how much work is integrating those going to be, so this is probably going to be a lower priority right now.
