### ISSUE TITLE
Logix "Playback driver" *BOOL for loop audio is ignored.

### ISSUE THREAD

**Issue by TeknoCatron** [Neos-Metaverse/NeosPublic#1447]
Logix node "Playback driver" ignores the Boolean for loop TRUE-FALSE

While being driven, the TRUE or FALSE is ignored.
Loop Boolean does drive the loop in the inspector, but keeps the loop active in any case.

**Comment by Frooxius** [comment]
What do you mean by it being ignored? What results are you expecting and what are you getting instead?

**Comment by shiftyscales** [comment]
Do you have any details on the replication of this issue, @TeknoCatron? It appears to me the loop boolean is properly respected, if I change it while the playback is being driven with a Drive Playback node, the looping value will change properly.

Going to close this issue because it is appearing to be a non-issue, it can be re-opened if more details/a replication case are provided.
