### ISSUE TITLE
Allow TooltipMultiplexer to be equipped if connected tooltips are allowed

### ISSUE THREAD

**Issue by The-furf-of-July** [Neos-Metaverse/NeosPublic#1462]
I think it would be good to allow Tooltip Multiplexers to be equipped by non-builder users, if and only if all of the tooltips that the multiplexer can switch between are also allowed. 

This would resolve the security conflicts with blanket allowing Tooltip Multiplexers, and would allow tools composed of multiple RawData or Brush tips to be equipped by Guest users.

Yes, this would require extra behavior to handle Tooltip Multiplexers compared to other tooltips, however given the nature of them, that seems reasonable.

An example usage: A multiplexer of various brush types currently cannot be equipped by a guest, but each individual brush type can.

**Comment by RueShejn** [comment]
the problem with that is that people would be able to troll or grief with that bit of freedom basically allowing them to do what ever they want without needing permissions

there is also no way(to my knowlage) to check for every possible thing a tooltip could be, say i have a tool tip that reference a user it could A)show connection info or B) be used to grief user

**Comment by RueShejn** [comment]
if you want users in your world to be able to equip a specific tooltip you can add the tooltip by slot to the whitelist of tools they can use
the tool would also need to be tagged

**Comment by The-furf-of-July** [comment]
This would not allow any additional freedom than the current system already does, RawDataTooltip is currently blanket allowed for guests. What you're referring to requires a rework of logix/component permissions.

**Comment by The-furf-of-July** [comment]
What this is requesting is to perform the same checks you normally do with any other tool, on each sub-tool of the multiplexer.

**Comment by Frooxius** [comment]
This is a bit problematic. We can't do the same checks that are done normally with any other tool, because those are checking which tool is the user actually equipping. Checking if either the currently active tool or any of the tools in the list requires a different mechanism, which adds extra complexity (checking when the list changes, checking when permissions change, just the fact that the whole list needs to be checked in the first place when checking whether or not the tool can be used).

Generally adding extra complexity to security/permission systems isn't a good idea, because it adds more points of failure and more attack vectors, so there needs to be a really compelling reason to do warrant it.

What are the use-cases for this? Generally multitools contain builder tools, so in most cases you wouldn't be able to use them anyway unless you already have permission to use pretty much any tool.

We have official planned systems for swapping tools quickly and easily from compact Facet inventories, so in such scenarios those might be favored instead, as they wouldn't require adding more complexity to the permission system itself, but rather build on top of it.

**Comment by The-furf-of-July** [comment]
The system you described may work for that.

The reason I'm finding this troublesome is because I wanted to take the gun, sword, and bow portions of the Architect (which are all rawdatatooltips), and removing all dev tools, so I can use it for movement/utility purposes without needing to ask for builder perms. 
I think I could still do the same thing if I implement the multiplexer with logix instead of components and make the three into a single rawdata tool, but, still a little frustrating.

In general, any complex rawdata tool(s) with multiple modes needs to be made without using a multiplexer or else it gets treated as a builder tool. 

I do understand the concerns with adding complexity to the permissions system, though.

**Comment by shiftyscales** [comment]
For the reasons mentioned above by Frooxius, I don't feel this should be implemented. It adds considerable complexity and potential security vulnerabilities in an important system, and this issue can be worked around by changing the design of the tool itself to consider this restriction.
