### ISSUE TITLE
Material DeDuplication on world save removes driven materials

### ISSUE THREAD

**Issue by inzanesonikku** [Neos-Metaverse/NeosPublic#1497]
https://user-images.githubusercontent.com/18068941/102573013-50d5ca80-40a2-11eb-92e5-46ac146951b4.mp4

when driving the color of this unlit material im trying to drive and when i save, that material just goes away entirely

**Comment by H3BO3** [comment]
Was it being referenced by any renderers, and/or was it in the Assets folder of the world? If you're trying to drive material properties it's best to have them somewhere persistent so the link can stay intact.

**Comment by inzanesonikku** [comment]
@H3BO3 the orb for the material was in the world and it just deletes itself upon saving

**Comment by H3BO3** [comment]
Hmm, definitely strange. Can you replicate this in a new world?

**Comment by inzanesonikku** [comment]
possibly, i'll try that in a bit

**Comment by inzanesonikku** [comment]
> Hmm, definitely strange. Can you replicate this in a new world?

yep, it happens the exact same way

**Comment by shiftyscales** [comment]
Where is the component for the material itself stored? In the log you provided, following your save I see:

> 7:44:39 PM.926 ( 30 FPS)	World Optimized! Deduplicated Materials: 3, Deduplicated Static Providers: 17, Cleaned Up Assets: 99

What are your exact replication steps in a new world? I've not been able to replicate this on my end yet.

**Comment by shiftyscales** [comment]
@Frooxius -
I've investigated this issue with Zane. The issue is indeed material deduplication. But it occurs in a very particular circumstance.

The easiest way to replicate it is as follows:
- Create two cubes
- Create two unlit materials and apply one to each
- Add distinct Logix to each material to set the TintColor of each material, but ensure that both have the same color prior to saving (e.g. black/0,0,0,0.)
- Delete the material orbs so that the materials are stored in the assets folder
- Save the world

Despite being driven by two separate pieces of Logix, because the driven TintColor of each material is the same at the time of saving, Neos will deduplicate the materials, and apply the deduplicated material onto the other cube, linking them.

Of note:
- If these steps are replicated, but the material orbs are not deleted/the assets aren't placed in the asset folder, then the issue will not occur. Despite having the same TintColor, the materials will remain separated until the material orbs are deleted/the assets are stored in the assets folder. Perhaps because the materials are directly stored under the objects that are using them, e.g. the material orbs instead of being references to the materials?
- This issue/deduplication may also potentially be related to other issues such as #659- overly aggressive deduplication placing materials where they don't belong.

**Comment by shiftyscales** [comment]
On retrospect looking back at this issue, it feels more like an implementation issue on the part of the world designer/something that should be considered. Assets stored in the assets folder are intended more to be temporary/cleaned up from time to time, so if driving the material with Logix, it makes sense for it to be packed away in some dedicated slot somewhere in the world's hierarchy instead.
