### ISSUE TITLE
Neos emoticons/sprites on font chain

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#1537]
Unicode has Private Use Areas where Neos could put its logo and add it to the default fonts so that people can easily use it in strings.

A current alternative is for users to do this themselves or replace that bit of text with an image or similar.

**Comment by Frooxius** [comment]
This could be potentially added, but someone would need to make a font. But just for a single symbol that might be overkill. One thing that I'm considering is adding a set of Neos emoticons/sprites to the standard chain, which would have the logos as well, but it also adds a constant VRAM cost, so I'm not sure if it's worth putting it there globally. It would allow them to be addressed using names, like <sprite name=neos_logo> rather than cryptic Unicode symbols.
