### ISSUE TITLE
Ability to buy Storage or Storage Packages with $ or NCR and Seperate Marketplace Storage

### ISSUE THREAD

**Issue by alexderpyfox** [Neos-Metaverse/NeosPublic#1616]
## what topic do you want to discuss?
I want to discuss some suggestions for the storage allocation regarding the marketplace system and future I gotten feet back from some creators and users regarding storage a lot lately 

## Goal of discussion
Can be anything it's just a idea 

## Discussion:
So my suggestion was to have the store be it's own storage aswell so when for example creators upload items to the store they have a certain permanent storage allocated for the marketplace so it doesn't mess with their own private storage and so when someone buys an object it won't get deleted if the uploader/seller  didn't pay for extra private storage anymore via the current system.
 also It would be handy if the bought items don't take up storage for the buyer but only they add things to the object and only adds the modifications to their private storage count.

So the second part is ability to buy semi permanent storage packages directly without patron for example probable prime suggested in the discord as suggestion 12$ for 5gb for a year or even buying storage  packages using ncr itself also the ability to gift other people storage packages kinda like how you can gift people discord nitro.
Then also for the marketplace where creators want to sell their objects on charge a small fee with each purchase when they want to sell more than 1gb worth of items on the maket place so then the marketplace stays as a in between for what storage space it uses as long as it's seperate from a users private storage

**Comment by alexderpyfox** [comment]
![sketch-1611018900130](https://user-images.githubusercontent.com/61125650/104975901-3c1b8800-59fc-11eb-8f14-4969079221a7.png)

**Comment by TehTurk** [comment]
Hey Alex, adjusted the title to better reflect the issue but ideally you want these to be one issue, not 3 in one. For your first issue, that was already accounts for as Marketplace would be on the uploaders storage, not a *seperate* thing for the buyer, make sure you understand how it works currently before suggesting changes.  

Better Patreon Packages are a good idea, say for like a year of storage vs the month to month. 

Offline Stuff is a thing, but it might be different or not presented in the same way, but that's a future question of how or what.

**Comment by alexderpyfox** [comment]
It's not a good idea to have it on the uploaders main storage because if they rely on having extra storage and suddenly decide not to pay for extra storage anymore then all paid objects dissapears from the store and people that bought them

**Comment by TehTurk** [comment]
That would be something that would be handled by the marketplace system/Neos Servers. So there'd probably be hosting costs put on an item, or it'd be frozen to buy untill it's up again. There's ideas here but it comes down to when we get there wants the best option too.b

**Comment by Frooxius** [comment]
There won't be a separate storage system for marketplace, but there are a few things that should make this better:

- We'd like to have a mechanism which will mark the storage as "free" for the creators once their items reach a certain level of popularity. This needs to be carefully tuned, otherwise it could be abused by users to get free storage this way. We still have to pay for all the storage on our end monthly (and that's not including continuous bandwidth costs) regardless, so that essentially ends up being "subsidized" by other sources of income
- If you buy item, you can just place a link to it to the marketplace. This won't take any storage from your own account, as the item isn't stored on it. If you however make modifications or save your own copy, it'll use your storage, since you're storing a unique version.
- Buying storage directly with NCR or pre-paying for a longer period is definitely something we'd like to add. Doing things through Patreon keeps things simpler right now, but those are definitely options we want to add long term.
- There will be some restrictions on being able to remove things published to the marketplace. Probably some kind of mechanism for deletion which would ensure that everyone who bought the item can still access it, but more thought needs to be put into this. E.g. the removal taking 2-4 weeks to complete and transferring the item somewhere else after. This would be only in cases when the storage wasn't granted for free to the creator if it didn't hit the right threshold.

**Comment by Frooxius** [comment]
We added ability to buy storage with NCR in 2021.11.3.481! Thanks for the request and discussion.
