### ISSUE TITLE
More direct access to clipboard from logix / components

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#1643]
## Is your feature request related to a problem? Please describe.
I am currently making a thing which makes me want to spawn out import dialogues for arbitrary links. (not to inventory items but to arbitrary image links.)

## Describe the solution you'd like
I'd like a simple way to read/spawn things from a users clipboard and maybe write to it so that logix systems can open import dialogues more easily.

## Describe alternatives you've considered
This is currently only possible by emulating keyboard presses for Ctrl+A, C and V while focusing the user into a text field with the desired link or by abusing the new functionality for copying folder links.
Both of these are somewhat ugly workarounds and the first one comes with the downside of requiring the user to double click while also toggling a keyboard for a single frame which can interrupt their laser mid-double click.

**Comment by Aerizeon** [comment]
This seems like it would need an associated prompt (similar to the prompt for opening URLs) or the generalized permissions system, otherwise this would be easily abused (such as someone copying their neos password from a password manager - you don't want LogiX to arbitrarily grab *that* from you)

**Comment by Psychpsyo** [comment]
Definitely. I was thinking something that opens a paste dialogue or requests clipboard access, similar to what the "Paste content from clipboard" facet or accessing a websocket does.

**Comment by Frooxius** [comment]
I'm not sure if I want to add such mechanisms, because there are security concerns and getting around them is a bit of a poor UI/UX. Better approach for working with clipboard might be through user-initiated actions, like importing or exporting, so it's clear when/how their clipboard gets modified/accessed through their actions.

E.g. for importing, my plan is to add a way to specify "Import handlers". That would allow for adding custom handlers for different file types and extending the import functionality of Neos that way.
