### ISSUE TITLE
Neos Dash does not have an ObjectRoot.

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#1765]
## Is your tweak request related to a problem? Please describe.
Things should have properly configured ObjectRoots. The dash is no exception.

## Describe what would you like tweaked
Add an ObjectRoot to the Neos Dash.

## Describe alternatives you've considered
Not having an ObjectRoot on the Neos Dash.

**Comment by Frooxius** [comment]
What are your usecases that require it to have object root?

Dash is a special object running in the userspace to provide core functionality, not a spawnable object that user can manipulate, so it pretty much is an exception.

I'm not saying that it can't be added, but it sounds like you might be doing something that's not something we'd officially support, so this could be very much "Do at your own risk, because it might break at any point" territory.

**Comment by Psychpsyo** [comment]
It's not that it would provide any super useful functionality (that I can think of right now) but more that, when someone inspects the dash, it shows a good example of how/where to put object roots and makes people more likely to catch on to that and copy that behavior when making their own objects.

**Comment by shiftyscales** [comment]
Generally speaking a user should not need to inspect their dashboard/userspace much less do so as a template for how to set up their object.

As Froox noted above, it's not intended to be a spawnable, user-manipulatable object, as such in the absense of a usecase, I'm going to close out this issue for now, I don't think this necessarily needs to be implemented, @Psychpsyo.

**Comment by Frooxius** [comment]
Yeah, the dash isn't really a good template for users to look at, it's very special object. With some recent work on the desktop, it's actually gotten a bit more complicated, as pieces of the dash get moved completely outside of it into separate part of the scene hierarchy in some cases, so the concept of it having a single ObjectRoot doesn't quite apply to it anymore.
