### ISSUE TITLE
World overwrite is not working.

### ISSUE THREAD

**Issue by orange3134** [Neos-Metaverse/NeosPublic#1814]
## Describe the bug
The function to overwrite the world using the World Orb seems to be no longer working.
When I take one world orb and trigger another world orb, nothing is displayed.

## Relevant issues
none

## To Reproduce
1. Create two worlds and spawn two world orbs.
2. Grab one and trigger the other.
3. Nothing happens.

## Expected behavior
A menu will appear to overwrite the world.

## Screenshots / Video
https://youtu.be/EEznXk6Fu4s

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.3.5.176
 - Neos Platform: Windows
 - Regression: Yes (I'm sorry, but I don't know which version. I last used this feature in January of this year)

## Additional context
none

## Reporters:
orange

**Comment by shiftyscales** [comment]
Hi @orange3134 - do you have any more specific instruction on how to replicate this issue? I've attempted to do so, but it appears to be working properly for me. I grab the newer/more up to date world in my right palm, and click on the older world I wish to overwrite with my right laser.

A context menu pops up, and I select the overwrite option. Everything appears to be working properly.

On reviewing your video, I believe the issue is that you are using both of your hands/lasers to try to overwrite. To overwrite a world, you need to hold the newer version of the world in your palm, and click on the older version of the world with the same hand's laser.

https://user-images.githubusercontent.com/54213390/110689988-3b030d80-8198-11eb-91e7-a1c7f4d0bf80.mp4

**Comment by orange3134** [comment]
@shiftyscales 
Thank you for answering!
I didn't know that I could overwrite the world by grabbing the World Orb directly.
Anyway, I was able to overwrite it, so the problem was solved. thanks you.

However, I remember that in previous versions it was possible to overwrite with a remote grab.
The photo is a little hard to see (and the laser is hidden), but I grabbed the orb in the back with the laser and overwrote the orb in the foreground.
![2020-07-17_16 41 24](https://user-images.githubusercontent.com/56525091/110894181-c0262800-833a-11eb-9af8-2f8ac439581b.jpg)

**Comment by shiftyscales** [comment]
> 
> 
> @shiftyscales
> Thank you for answering!
> I didn't know that I could overwrite the world by grabbing the World Orb directly.
> Anyway, I was able to overwrite it, so the problem was solved. thanks you.
> 
> However, I remember that in previous versions it was possible to overwrite with a remote grab.
> The photo is a little hard to see (and the laser is hidden), but I grabbed the orb in the back with the laser and overwrote the orb in the foreground.
> ![2020-07-17_16 41 24](https://user-images.githubusercontent.com/56525091/110894181-c0262800-833a-11eb-9af8-2f8ac439581b.jpg)

Hmm... I wonder if this might be related to #1781 ? It sounds like it might be a similar case.
