### ISSUE TITLE
Detect OBS running and suggest streamer camera

### ISSUE THREAD

**Issue by mralext20** [Neos-Metaverse/NeosPublic#1833]
## Is your feature request related to a problem? Please describe.
as was noticed in the videos channel in the discord, people new to neos are generally blind to some of it's more powerful features, like the streaming camera.

## Describe the solution you'd like
one solution to this could be to detect OBS running (like discord does), and throw a message up on the dash or similar that's like 'yo, we detected OBS running. do you wanna use the streaming camera?'

## Describe alternatives you've considered
this problem may be solved more suscinctly by the MTC's Streaming room, however i doubt this as the current state of the MTC does have a streaming room.

## Additional context
https://discord.com/channels/402159838827905024/472301664271859723/821113273084674049 - idea in # videos.

**Comment by Frooxius** [comment]
I'm not sure if this is a good idea, we'd have to be constantly checking running processes on the user's system for this and that might be a bit weird behavior. Not sure it would be good UI/UX, it has potential to be really annoying too if you don't want it. 

We are working on a new MTC Streaming room, which is going to teach how to use the camera and such, so I think it might be better to put focus onto that. 

The UI for the camera will be reorganized as well.

**Comment by shiftyscales** [comment]
Yeah, for the present time, I think it would be best to emphasize the discovery/visibility of the functionality such as through the dedicated MTC room for it, @mralext20.

I also feel some users might feel checking their running processes for OBS could also potentially be seen as invasive, even if it's just a simple check. For the above mentioned reasons, I'm thinking this shouldn't be implemented at this time, if at all.

There is a slight learning curve to use of the streaming tools we have available, but that'd probably be true regardless of what it looks like/how the user discovers it. Ideally prospective streamers would take a moment to do a bit their due diligence in taking a brief period to explore the platform before they present it, rather than going in completely blind.

Depending on the streamer even if they are running OBS they might not necessarily be equipped to make full use of the streaming tools, e.g. capturing from the SteamVR VR view rather than directly from the application. The community also tends to be pretty quick to point out the tools in their chats, or in-app when applicable too.

If you have any suggestions of potential ways to increase the visibility of the tool set to its intended audience though, feel free to open another GitHub issue with those proposed suggestions/tweaks.
