### ISSUE TITLE
Disable Desktop Overlay when in Desktop Mode

### ISSUE THREAD

**Issue by FlameSoulis** [Neos-Metaverse/NeosPublic#1861]
## Is your tweak request related to a problem? Please describe.
It isn't related to any known issues, but does involve a rather odd situation: namely, there is no reason a desktop-user should need access to their own desktop in the desktop view mode. 

## Describe what would you like tweaked
When in desktop mode, disable or do not render the desktop overlay, since the user is already viewing and operating their desktop traditionally. It makes sense when in VR, but less sense in Desktop.

## Describe alternatives you've considered
Just make it an option in settings or via command line to disregard disabling the desktop viewer when in desktop mode.

## Additional context
The only possible reason I could see it remaining is if someone creates virtual monitors and uses this as an alternative means to access. However, this may be a very niche situation.

**Comment by Frooxius** [comment]
This will make more sense once we have screen sharing, which will let you stream your desktop to other users in the world, which is why we kept it there for now. I don't think it's worth it spending time engineering solution to hide/disable it in the meanwhile, it's just an oddity right now, but shouldn't actively harm anything.

**Comment by kazu0617** [comment]
By the way, does this Issue contain any mention of "Disabling only the DashBoard display"?
(I'm posting this here because I had to Duplicate it, but I don't think it's necessary to be in the Dash menu when displaying in desktop mode or Quest, although it certainly doesn't need to be cut down in terms of functionality).
