### ISSUE TITLE
Referencing Node

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#1882]
## Is your feature request related to a problem? Please describe.
Getting the RefID of an object is currently only possible through somewhat hacky ways or the Write Ref node. A node to do it without writing would be nice.

## Relevant issues
Did not find any.

## Describe the solution you'd like
Give us a node which basically does the opposite of the -> node, converting from an object to its RefID.

## Describe alternatives you've considered
Using the Write Ref node which needs a pulse and a field to be written to, (ab)using a RefEditor component which also needs a field or doing string parsing on the string representation of the object which isn't very efficient.

**Comment by mralext20** [comment]
This feels like an instance of xyproblem. ( https://xyproblem.info/ )

Why do you want the ref ID?

**Comment by Frooxius** [comment]
Yeah definitely. The reason it's hacky is because you shouldn't ever need to bother with RefID. I **strongly** discourage dealing with those directly, they're more of an underlying implementation detail and it can change at any time, you shouldn't be using them at all of any legitimate content.

What problem are you trying to solve?

**Comment by Psychpsyo** [comment]
I was mainly just messing around and noticed that there was no simple/clean way to have the opposite of the -> node. This wasn't for anything specific but mainly just to make RefIDs easier to deal with.

**Comment by H3BO3** [comment]
isn't that what the Write Ref node is for?

**Comment by Frooxius** [comment]
I see. I'm sorry, but this won't get added, especially not for that. You shouldn't be dealing with RefID's at all in the first place. If you use hacks to do that, your creations will likely break at some point, preserving compatibility and behaviors of those isn't something we plan on doing, as that would constrain the development in some areas significantly. 

I'd recommend using nodes for working with references directly and avoid the RefID's, since the references abstract their implementation details away. If there's something missing for working with references, feel free to make an issue for that, but as for raw ones, we don't want to promote their use.
