### ISSUE TITLE
Add Local Impulse Timeout

### ISSUE THREAD

**Issue by Toxic-Cookie** [Neos-Metaverse/NeosPublic#1902]
## Is your feature request related to a problem? Please describe.
When I add an impulse timeout node, my immediate thought is that it is a global timeout for all users, when in reality it is actually a local timeout.

## Relevant issues
At some point Local Fire on X was added alongside Fire On X. This is a similar case.

## Describe the solution you'd like
Add a Local Impulse Timeout node and make regular Impulse Timeout global for all users in the session.

## Describe alternatives you've considered
Solutions can be made to work around this problem but it would make more sense to just add an extra node for this distinction like with the Fire On X/Local Fire On X nodes.

## Additional context
None

**Comment by Zyzyl** [comment]
Thanks for posting this. I've thought a global timeout option would be pretty handy for a while now.

**Comment by Frooxius** [comment]
Having a global timeout option is kinda tricky, it's not really something you can do with network latency. Say you have two users across the world, with 200 ms network latency. Both fire the impulse at the exact same time.

It will take at least 100 ms for each to know about each other's impulse, so both impulses will go through, even though only one technically should. When dealing with network latency, we can't guarantee that the impulse timeout will actually work properly, because if they happen fast enough, they will go through.

Adding a global one would probably be more confusing than just having the local one and structuring your logic around it.

We might rename the timeout so it's more clear that it's only local to avoid the confusion, I think that's probably the best solution for this.

**Comment by Toxic-Cookie** [comment]
That does sound tricky. Renaming it would be a decent compromise.

**Comment by Frooxius** [comment]
Renamed it in 2021.3.30.508, thanks!
