### ISSUE TITLE
New Default headsets are too bright

### ISSUE THREAD

**Issue by TehTurk** [Neos-Metaverse/NeosPublic#1920]
## Is your tweak request related to a problem? Please describe.
New defaults are a bit way too bright.
## Describe what would you like tweaked?
For it to be reduced and possibly have the lights in the hands removed? The emission on the material is enough imho.
## Describe alternatives you've considered
-none-
## Additional context
I like the new design ^^

**Comment by Hayden-da-Serg** [comment]
This is my exact thought when I first saw them, the brightness can very often be distracting, as it would commonly create a lens flare in the HMD, and I for one would not like a lens flare coming off my hands while doing much of anything.
As mentioned above it also makes seeing in dark environments very difficult due to the contrasting brightness.
