### ISSUE TITLE
New Desktop mode doesn't get notification preview

### ISSUE THREAD

**Issue by AshtonSparx** [Neos-Metaverse/NeosPublic#1923]
## Describe the bug
When in desktop mode, and someone messages/invites you. No message preview appears. You also don't see notifications of friends going online. At first I thought you didn't get any sounds either, but turns out it's extremely quiet, set all audio to 100 and still could hardly hear anything. (tested in vr and still quiet like a mouse)

## Relevant issues
None I could find.

## To Reproduce
1. Launch neos in VR
2. Press F8 to enable desktop mode
3. Have someone send you a message or invite you
4. Get notification sounds but no pop-up preview.

## Expected behavior
You should get a flat notification panel appear on the top-left of your screen.

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.3.31.528
 - Neos Platform: Any
 - Link to reproduction World/Item: N/A
 - Regression: With the curved dash, worked fine.

## Additional context
While dash is open, you still get no notification preview

## Reporters:
@AshtonSparx#5050 (AshtonSparx Neos)

**Comment by shiftyscales** [comment]
The notifications being really quiet is a bug. I believe related to #1880. I'll make a GitHub issue about that, thanks.

As far as notifications- I don't know if any work would go into making those work on the desktop mode since there is an entire notifications system that is planned for eventual development. The current notifications system is legacy/from the old UI, and ideally wouldn't be updated in favor of putting that time towards developing its replacement.

**Comment by Frooxius** [comment]
This is intentional right now, I don't have plans for the old notification UI to be ported over to the desktop, but there's a new, more flexible one planned, which will work both in VR and in desktop.

**Comment by AshtonSparx** [comment]
This is not really an issue anymore as opening/closing the dashboard re-centers everything. If this should remain open. It can be opened again. But currently, I don't see the issue anymore.
