### ISSUE TITLE
The mouse does is not recentered when radial menus are opened.

### ISSUE THREAD

**Issue by CheesecakeCG** [Neos-Metaverse/NeosPublic#1934]
## Describe the bug
The mouse does not get recentered when radial menus are opened.

## To Reproduce
Enter NeosVR in desktop mode.
Look at an avatar or tool, left click.

It seems to only happen on Linux. I tried it on both X11 with KWin and Wayland with Wayfire.

## Expected behavior
The mouse should be centered in the middle of the radial menu.

## Screenshots / Video
https://streamable.com/oh7fum

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.4.2.690
 - Neos Platform: Linux 
 - Regression: Not sure. (I've only used Neos for Windows up until recently. It worked then with the old desktop mode)

## Reporters:
Discord:
- Greyfus#9503
- hare_ware#4880 (Me)

**Comment by redyoshi49q** [comment]
I have experienced this issue as well.  For others who also have this issue, the following is a workaround for until the bug is fixed:

* Using your mouse, focus your display on the object/region you wish to middle click.
* Press Escape to open the main Neos VR menu.
* Center your cursor within the display.
* With the cursor centered, press Escape again to close the main Neos VR menu.
* If you're intending to use the radial menu on a held object, press the right mouse button to grab it now; try to not move the mouse while doing so.
* Without keeping the mouse steady, press the middle mouse button.  If successful, you should be able to use the radial menu as intended.

**Comment by Frooxius** [comment]
Unfortunately this seems to be limitation of the Unity API on Linux, as it doesn't support centering the cursor like this. Instead I made the menu not auto-dismiss if the cursor starts out outside of it in 2021.4.5.911, which should fix not being able to use it.
