### ISSUE TITLE
Determine what Hand is Grabbing a Grabbable is clunky can we simplify? (Grabber Chirality)

### ISSUE THREAD

**Issue by TehTurk** [Neos-Metaverse/NeosPublic#1947]
## Is your feature request related to a problem? Please describe.
Yes, there's 5-6 different ways of determining which hand is grabbing something. These work but usually take an unnecessary amount of effort. There's even been custom nodes for this.

## Relevant issues

-none that I could find please link if there is one- 

## Describe the solution you'd like
A simple node like Grabber BodyNode, but instead it's something like Grabber Chirality
A Grabber will always parent to a Holder, which hand initiating that grabber is also key as well too. 

## Describe alternatives you've considered
Usually this can be a 5-7 node setups depending and when your doing stuff on the fly it'd be a simpler addition for alot of folks.

**Comment by Frooxius** [comment]
The GrabberBodyNode node is already as simple as it gets for giving you the information about which body part the grabber belongs to. It can potentially belong to any body node, so your code should deal with that - check if it's either left hand or right hand, because it can be neither.

One thing I can add though are some helper nodes for working with the BodyNode, which includes determining of chirality of a body node, among other things. That could simplify determining that, but it could result in misbehavior if not used properly (e.g. if the grabber corresponds to a foot for example, something that doesn't have chirality like the head or simply not having a body node associated).

**Comment by TehTurk** [comment]
Dang okay. 
Yes this is the norm now, I was hoping to simplify it in some way.
Hmm I think that would help, I think in moments where stuff is intended to be handled by those body nodes your expecting different behavior not the same. I think that's within expectable means.

**Comment by Frooxius** [comment]
Added the nodes in 2021.4.5.911 which should simplify the setup. But please still note the above, if you oversimplify your setup to the point of not dealing with all possible scenarios, you might run into trouble at some point.
