### ISSUE TITLE
Joining world gets stuck on "Establishing Connection" when relay setup fails

### ISSUE THREAD

**Issue by Aerizeon** [Neos-Metaverse/NeosPublic#1968]
## Describe the bug
It seems that, when NAT Punchthrough fails, if the relay connection *also* fails setup, Neos will continue to display the "Establishing Connection" message indefinitely.

## To Reproduce
Unfortunately, this only seems to be reproducible at present, because the relay service isn't functioning.

## Expected behavior
A "Connection failed" message, stating that the relay service was unreachable or malfunctioning.

## Screenshots / Video
![Loading...](http://files.aerizeon.net/sharex/2021/Neos_04-06tRYT6G09OY.png)

## Bug information (please complete the following information):
 - How often does it happen: Sometimes
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.4.6.931
 - Neos Platform: Windows

## Additional context
Attached error log

## Reporters:
Epsilion
A bunch of people in discord who noticed the issues around the same time.
[DESKTOP-C7VB0S9 - 2021.4.6.931 - 2021-04-06 21_59_15.partial.log](https://github.com/Neos-Metaverse/NeosPublic/files/6268547/DESKTOP-C7VB0S9.-.2021.4.6.931.-.2021-04-06.21_59_15.partial.log)

**Comment by shadowpanther** [comment]
I also had issues with world sync yesterday - I was able to connect to the session and saw/heard users, but after some time the world sync started to lag behind, and it seemed that it was not the host's bandwidth, but my connection instead. In one of the cases, the world sync completely stopped (inspectors didn't update, slots didn't move, etc.) until I quit the session and joined back.
Can't find anything relevant in the log.

**Comment by Frooxius** [comment]
This is already implemented, if the relay fails to connect, you will get an error message.

Your assumption that relay was not functioning is incorrect, the relay was functioning properly. There was a problem with different part of the service that's already been addressed.

**Comment by Aerizeon** [comment]
The "joining" message never gets dismissed in this case, and never displays anything to the user to indicate an error has occurred, how is this not a bug?

**Comment by Frooxius** [comment]
Like I said above, you are making incorrect assumptions. The relay was functioning properly. The connection was established and was communicating.

You made the issue about getting stuck when the relay fails. The relay didn't fail. If it did, it would already give you the error message you asked for, that has been implemented.

The actual problem was caused by the matchmaker service, this was just a symptom of a different bug that has been addressed internally.

**Comment by Aerizeon** [comment]
I understand that the cause I identified was incorrect, however in this state, neos still never timed out the connection, and prevented new connections to the same world.

**Comment by Frooxius** [comment]
Connections only timeout when the other end stops responding for a while. But again, this wasn't the case, the connection was technically established and communicating, so it wasn't subject to timeout.

A different bug  caused it to get stuck in that state where it was communicating, but stuck on processing. It **has** been addressed.

The thing you reported and requested specifically in this issue is already implemented though, so I just closed it since there's not anything actionable anymore.
