### ISSUE TITLE
Change "Alt" for 3rd person to F number keys

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Neos-Metaverse/NeosPublic#2015]
## Is your tweak request related to a problem? Please describe.
When using 3rd person I chagne and sprint alot I constantly change my keyboard layout which messes with all my typing and all of my interactions due to ALT+Shift being the combination in windows to change keyboard layouts.

## Describe what would you like tweaked
Change it from ALT to F # keys.
F5 similar to minecraft might be good.

## Describe alternatives you've considered
No alternative.

## Additional context
![grafik](https://user-images.githubusercontent.com/61988002/114762020-8beebe80-9d61-11eb-9290-acd9aea62155.png)

**Comment by Frooxius** [comment]
As mentioned in the release notes, this is only temporary and will be changed, but I don't know what to yet, because I still have more parts to work on (freeform camera and such), so it's a bit too early for feedback on this, sorry. I'll see what the proper method ends up being as I have more things in place.
