### ISSUE TITLE
Headless client stats/command API

### ISSUE THREAD

**Issue by shadowpanther** [Neos-Metaverse/NeosPublic#2035]
## Is your feature request related to a problem? Please describe.
I want to gather some stats from my headless client.

## Relevant issues
None that I know of.

## Describe the solution you'd like
An API exposed via HTTP that would return a single/multiple parseable JSON(s). Said JSON would probably be a combination of worlds, users and status commands (list of running sessions with their parameters, list of users for each session with role/afk/etc. for each). Popular server software usually have something like /server-status that you can GET and parse.

As an extension of this interface, a *command* API that would allow to control the headless without emulating typing into its stdin and trying to parse its stdout. Just having the same commands that are available in the console would help. For example, I could set up an external script to check if the session is running and try to restart it if it crashed. Or spin a session for an event with just one button.

## Describe alternatives you've considered
Make a wrapper to pass stdin commands and parse stdout.

## Additional context
I've made a docker image for the headless client so that I could easily run it on any machine without setting up mono and such. Containers are not usually supposed to be console-interactive, so having other means to control the headless would be great. Also, automation would be a lot easier with such an API.

**Comment by glitchfur** [comment]
Having a local API in the headless client would be an extremely useful addition. I'm currently working on a project that interfaces with the headless client using the exact alternative method you described: by wrapping around its `stdin` and `stdout` streams, to issue commands and receive output. However it is far from a clean solution, as I am parsing command outputs into JSON myself.  Plus there are sometimes nuances with how commands return their output which makes it a lot harder to parse reliably. Having an API would make it far more convenient to write scripts that interface with the headless client directly, instead of having to create or use such wrappers.
