### ISSUE TITLE
Desktop reticle disappears when in use

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#2105]
## Is your tweak request related to a problem? Please describe.
When scrolling through long lists or clicking a lot in desktop without moving the mouse, the desktop reticle will disappear, forcing you to move the mouse before continuing.

## Describe what would you like tweaked
Make the desktop reticle disappear timer not only factor in mouse movement but also clicking and scrolling.

## Describe alternatives you've considered
Keeping it like this which is annoying quite often when scrolling through inspectors and other lists.

**Comment by shiftyscales** [comment]
I feel this could be also improved by exposing the cursor fade time as a setting once the settings UI is reworked (although that is out of the scope of this issue/could have its own issue opened).

I've not personally run into this too often- likely because I usually have a dev tool tip equipped when scrolling things, but without a dev tool equipped, it became a lot more obvious why it could be frustrating.

It appears that the mechanism to activate the laser/cursor by clicking the left mouse button only applies in the third person camera, and not while in the first person view.

**Comment by Psychpsyo** [comment]
> I've not personally run into this too often- likely because I usually have a dev tool tip equipped when scrolling things, but without a dev tool equipped, it became a lot more obvious why it could be frustrating.

I don't run into it with inspectors that often either, though I have a tool I use quite commonly which has rather long, scrollable fields.

**Comment by Frooxius** [comment]
Made changes in 2021.4.28.1415 so clicking and scrolling will keep it active!
