### ISSUE TITLE
Change password on the website

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Neos-Metaverse/NeosPublic#2132]
## Is your feature request related to a problem? Please describe.
I currently have no easy way to change my password through the website; which can be problematic as I like to swap my passwords frequently.

This also includes the "Forgotten password" option.

## Relevant issues
#206 ?

## Describe the solution you'd like
A way to change my password on the website and request a forgotten password change.

## Describe alternatives you've considered
Only use client which is iffy. Especially for account management in VR.

## Additional context
-

**Comment by shadowpanther** [comment]
I guess, as a workaround, you can F8 to desktop mode, change the password, then F8 back to VR. Or just launch in Screen mode just for that.

**Comment by 3x1t-5tyl3** [comment]
> 
> 
> I guess, as a workaround, you can F8 to desktop mode, change the password, then F8 back to VR. Or just launch in Screen mode just for that.

Appreciate the workaround. But I'm well aware of it. I'm just documenting things to make it easier to find in the future. :)

**Comment by Frooxius** [comment]
You can actually change your password on the early development version of the new website: https://cloudx-account.azurewebsites.net

We do not plan on adding that option on the old website, since it's handled by a 3rd party developer and thus is difficult to update, it will be eventually replaced by the one linked above once it reaches sufficient feature parity.
