### ISSUE TITLE
Bring back K and L keys for Inspector.

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#2168]
## Is your feature request related to a problem? Please describe.
When looking at a slot in an Inspector, K and L used to get you a logix interface for the slot or unpack it. They don't anymore.

## Relevant issues
Couldn't find any.

## Describe the solution you'd like
Restore the old behavior.

## Describe alternatives you've considered
Keeping only the current ways and not having these options.

**Comment by Frooxius** [comment]
This is intentional. Those were part of the debug screen mode, which was never officially supported and those keys were only added to aid with quick debugging as the mode wouldn't allow use of context menu. This however introduced some security issues and others.

The official desktop mode lets you interact with tools in same way as in VR and opening inspector is done through the developer tooltip.

We do not provide support or restore behaviors of officially unsupported features, I'm sorry.
