### ISSUE TITLE
Improve Jumping Movement

### ISSUE THREAD

**Issue by MR-Alex42** [Neos-Metaverse/NeosPublic#2194]
## Is your tweak request related to a problem? Please describe.
Currently the jump movement for an avatar is unnatural as the avatur is taking off immediately without bending the knees.

## Describe what would you like tweaked
A natural vertical jump requires to bend the knees to build up momentum before taking off.
I would like to see a more natural movement.

## Describe alternatives you've considered
Some LogiX that overrides the avatar system.

## Additional context
Please see slow motion video analysis of a vertical human jump:
https://www.youtube.com/watch?v=BFIGdCXgdeI

**Comment by Frooxius** [comment]
I'm sorry, but we don't plan on implementing this as official locomotion. The goal of the in-game locomotion system is to provide responsive controls, rather than realism, so this would go directly against that, by adding additional latency before the jump occurs. Most games with this style of control don't do this either, unless they're very cinematic based (e.g. Assassin's Creed, whose controls feel "heavier" as a result)

Depending on how it's done it could potentially also induce nausea, as we'd have to move the user's viewpoint for them before the jump, or just have nothing visually happen for them, which would make the delay before the jump even more confusing.
