### ISSUE TITLE
Migrating a cloud variable to a new definition

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#2202]
## Is your feature request related to a problem? Please describe.
I'll probably be in a position soon where I'll need to replace a cloud variable currently on my Neos account with one that is defined by a group.

## Relevant issues
Didn't find any.

## Describe the solution you'd like
A Neos bot command that takes a source variable definition and a target variable definition and migrates all set values for the source variable to the target variable.

## Describe alternatives you've considered
1. Having the entire variable be reset by the change-over.
2. Not switching the variable declaration. (not exactly a professional thing to keep group-related cloud variables on a personal account)
3. Manually finding a values currently set for the variable and entering them into the new one. (which would be tedious and annoying, especially if the need ever comes up again)

## Additional context
This request is closely related to my other request from #2200 as it is came up due to the same situation.

**Comment by Frooxius** [comment]
This is a bit problematic, because migrating a variable and its values while it's still in use is a pretty big task, because people can still be writing and reading the values as it's being transitioned to a new one. It will also likely break any existing items and worlds that you don't update manually to reference new variable, unless we add some sort of redirection system.

I'm not sure if this is something we'd support given the engineering effort required, generally you should plan ahead with your variables and if you need a new one or make changes, create a new one instead and distribute new versions of the item to use it.
