### ISSUE TITLE
Add LogiX node: Space

### ISSUE THREAD

**Issue by RobertBaruch** [Neos-Metaverse/NeosPublic#2216]
## Is your feature request related to a problem? Please describe.
Sometimes I find that I have to use an input string that is one space. Visually, this looks no different from any other string that is empty or contains multiple spaces or tabs.

## Describe the solution you'd like
Like the New Line node, I'd like to see a Space node.

## Additional context
To be fair, this request doesn't ask for missing functionality to be implemented. It only makes LogiX more readable.

**Comment by Frooxius** [comment]
We can add constants for other common escape sequences / ASCII control symbols as well, that might be a good general addition.

**Comment by Zyzyl** [comment]
Maybe put them all under a subfolder in Strings then Froox?

**Comment by shadowpanther** [comment]
Could we instead have a Char input node that would be shorter than a String one, but similar in size to the proposed 'literal'(constant) node, while being more useful? (this expands use-cases)
Maybe have it show non-printable characters as a hex code? (this addresses the non-visual appearance of spaces/tabs/0x00)

**Comment by mralext20** [comment]
And perhaps a "newline (Unix)" and "newline (windows)" nodes, then rename the existing newline to "newline (OS)"

**Comment by JackTheFoxOtter** [comment]
Maybe there should be a single node for common string constants and you can choose which you want to use through a combobox / enum. If we start adding a new node for every useful constant that could potentially escalate into a LOT of new nodes quickly.
That way non-visual characters can be represented by a description text in the combobox, and OS specific constants like the mentioned newline can be distinguished easily. It's not a new functionality because you can use normal string inputs for this as well, but it would definitely improve readability of code and streamline string operations a bit more.

Maybe a similar approach could be taken for constants of other types as well (namely mathematical constants), it could reduce the overall node count quite a bit and provide a more easily scaleable solution since it would be trivial to add new constants to the list later on without adding an entirely new node each time, which I'd argue would be a good thing.

Because many of these string constants would utilize more than just a single character a char node in this case wouldn't be sufficient, but I like the idea on it's own, maybe this should be a separate feature request.

**Comment by Zyzyl** [comment]
@JackTheFoxOtter having a single node with an enum input does sound like quite an elegant solution. That said, I'm not sure having a large number of nodes for constants is necessarily much of a problem if they're kept out of the main Strings / Math category lists. 

Re: enum inputs I see 2 specific usability issues:
1) paging through enums with lots of potential values is a pain
2) you can't immediately see the full set of possible enum values without cycling through them all

Of course those are both potentially fixable with UI changes in the future.

**Comment by Frooxius** [comment]
We're not adding those as enums like this, this is not in line with the general design style of LogiX nodes.

**Comment by RobertBaruch** [comment]
ᵒʰ ᵍᵒᵈ ʷʰᵃᵗ ʰᵃᵛᵉ ᶦ ᵈᵒⁿᵉ

**Comment by Frooxius** [comment]
Added a bunch of character constant nodes (including space) in 2021.5.13.384!
