### ISSUE TITLE
Prefix the MTC with a locale, when it's first loaded or a user starts one

### ISSUE THREAD

**Issue by RaithSphere** [Neos-Metaverse/NeosPublic#2232]
So just an idea that stemmed from a discussion with a member of the Japanese community, would be to prefix or suffix the name of the mtc with the locale of the user that is currently hosting it, this could help with language barriers and allow people to know which language the user speaks.

This could also help with English users joining a session with a non English speaker.

For example

Metaverse training centre [cz] or
[ja] metaverse training centre

**Comment by TehTurk** [comment]
Alternatively instead of Locale could we do a sprite with a flag? While Locale is good, visuals can also go far too, or even in Tandem.

**Comment by 3x1t-5tyl3** [comment]
Maybe a ping display of some form to check for the connection before you join? Though that might bring some security concerns 🤔

**Comment by shiftyscales** [comment]
That's way out of scope for what this issue is asking for @3x1t-5tyl3.

On-topic, however, I think this can be treated as a content issue. It is possible to drive the session name, so a small bit of logic could append [locale] to the session name.

I'll raise this as a possibility with the content building team.

**Comment by chemicalcrux** [comment]
This came up on the Discord a few days ago. A concern was that people might use one language for the UI but be completely comfortable using another for communication.

https://discord.com/channels/402159838827905024/477711742001086505/839490751092097024

Regardless, this'd be a nice heuristic.

**Comment by TehTurk** [comment]
Hmm is there a mechanism to affect world UI objects within the world browser as such? @shiftyscales I'm aware of stuff with things like the default avatars and such.

**Comment by shiftyscales** [comment]
> Hmm is there a mechanism to affect world UI objects within the world browser as such? @shiftyscales I'm aware of stuff with things like the default avatars and such.

I'm not really certain I'm understanding what you're asking about, @TehTurk. What do you mean by "mechanism to affect world UI objects"? Frooxius has previously noted extending the locale system to various asset types.

https://github.com/Neos-Metaverse/NeosPublic/issues/1715#issuecomment-773949046

> localization of images and other assets is going to be handled by the Neos' native localization system (the one currently used for the UI) once it's expanded for community use and provide a more scalable solution that doesn't need to be hard-coded into the world.

**Comment by TehTurk** [comment]
Ahh I see okay thank you for the information. Sorry for the confusion.

**Comment by Frooxius** [comment]
Eventually we want to have users indicate languages they understand and languages used in a session in a more formal manner, but this tweak would be specifically for MTC since that's started by a script.

We won't use flags to indicate languages at any point though, they're generally discouraged against since they don't map 1:1: https://wplang.org/never-use-flags-language-selection/

**Comment by Frooxius** [comment]
Added in 2021.5.15.697!
