### ISSUE TITLE
User Storage values Component or Logix

### ISSUE THREAD

**Issue by Earthmark** [Neos-Metaverse/NeosPublic#2332]
## Is your feature request related to a problem? Please describe.
I am trying to make a new world for usage by users, however some metrics that are visible to new users are not as easily 
The default user homeworld contains useful information about a user's storage amount and group listings, however the component that shows user storage is special cased to expose the text values using private fields, so I would like to get that exposed!

## Relevant issues
None seen yet.

## Describe the solution you'd like
A component or logix node that returns the numeric max and current of a user's storage amount, possibly with the component having the same restrictions of only working in that particular user's home world.

## Describe alternatives you've considered
Not having a storage indicator, which may be valid.

## Additional context
I am unsure if the storage data is going to be available long term, if it's planned to not have this be in future home worlds then nevermind! The goal is to not have the world missing features considered important.

I am concerned with using the component's private fields as they are not stable, and the hope for the user homeworlds is to have long term support for the systems built into the world, accessing private fields is a big no for long term support goals as I see it!

**Comment by Frooxius** [comment]
This is already supported by StorageUsageStatus component, under Cloud/Indicators. Please note that due to security reasons it only works in Userspace.

**Comment by Earthmark** [comment]
Thank you for the quick response Froox, I'll see about updating the wiki with that if it's not already there (I didn't see a relevant topic).
I assume then that having storage indicators in the users home world will not be a common feature in the future, and the homeworld project will not have one by default in the world.

Thank you!

**Comment by Frooxius** [comment]
It's a tricky thing yeah. Those indicators will probably get removed at some point or reworked. If we keep this functionality, you can use that to get someone's storage usage if you're in a world with them without their consent, so I don't think it's a pattern we want to keep.

There might be some middle ground perhaps, an option where the user chooses what gets displayed. E.g. the components will output their storage space usage in World, but only if they're in specific world (e.g. their Home or another world they choose).

That way someone could get the information only by being invited to their Home world, rather than any random world. That might be a good general approach for anything semi-sensitive I think.
