### ISSUE TITLE
A particular Font file fails to import/render

### ISSUE THREAD

**Issue by H3BO3** [Neos-Metaverse/NeosPublic#2337]
## Describe the bug
The attached font file either fails to import into Neos correctly, or it fails to render once it's in. A slot with all the proper components appears but nothing renders. Putting the font into a fresh textrenderer turns it invisible as well, since the font still doesn't render.

## To Reproduce
1. Import the attached file (You have to use the file browser - for some reason I couldn't import it by pasting it in. Unsure if related)
2. The font does not render. This happened consistently for the user who initially reported this, and for me as well.

## Expected behavior
The font should be visible

## Log Files
There are no relevant log exceptions to report, only the regular font import message.

## Screenshots / Video
![image](https://user-images.githubusercontent.com/62123804/119407819-0801ed80-bca2-11eb-99d1-5a3504c35531.png)
![image](https://user-images.githubusercontent.com/62123804/119407834-0cc6a180-bca2-11eb-8d70-ab3518c5c151.png)

The import slot components as they appear in the inspector.

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.5.24.1203
 - Neos Platform: Tested on Windows
 - Regression: Unsure

## Additional context
[wolfenstein.zip](https://github.com/Neos-Metaverse/NeosPublic/files/6535015/wolfenstein.zip)

## Reporters:
H3BO3#7957 Asai Hatsuyo#8612

**Comment by Frooxius** [comment]
It looks like this is because this font is not a Unicode font, but has its own character table. This is pretty old technique now, it was used by fonts like Webdings as well (which aren't supported in Neos either), see this issue here: https://github.com/Neos-Metaverse/NeosPublic/issues/352

This is a bit tricky. It would require substantial engineering to support, for something that's generally an outdated tech right now, so I'm not sure this is something we'd really want to invest time into. It'd just recommend seeing if you can find a version that's been upgraded to use modern Unicode mapping instead or convert it yourself.

**Comment by H3BO3** [comment]
Interesting, thanks for the explanation, Froox!
