### ISSUE TITLE
Unity SDK Unusable - OculusMobileController Conflict (among other things)

### ISSUE THREAD

**Issue by Enverex** [Neos-Metaverse/NeosPublic#2342]
## Describe the bug
The Neos SDK don't load due to conflicting DLL issues. If you eliminate that, you seem to have a cascade of other problems.

## Relevant issues
None

## To Reproduce
[Steps to reproduce the behavior:
1. Try and load the SDK.
2. It will produce a lot of errors on startup.
3. Trying to enter play mode will give a critical error relating to Oculus Mobile.

## Expected behavior
For the SDK to load cleanly.

## Log Files
Full editor log.
[Editor.log](https://github.com/Neos-Metaverse/NeosPublic/files/6541810/Editor.log)

Most of the (red) errors can be cleared, but this one is critical and the player refuses to run:
```
Assets\NEOS\Unity Environment\InputOutputDrivers\OculusMobileDriver.cs(14,5): error CS0246: The type or namespace name 'OculusMobileController' could not be found (are you missing a using directive or an assembly reference?)
```

## Screenshots / Video
![image](https://user-images.githubusercontent.com/958670/119556026-6dcfa180-bd96-11eb-868b-669bfa8dc944.png)

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: SDK Released on 2021-05-05
 - Neos Platform: Windows
 - Link to reproduction World/Item: N/A
 - Regression: Yes

**Comment by Konshu** [comment]
Any update to this issue?

**Comment by Frooxius** [comment]
It seems like just deleting that file should work, it's not necessary for it to work. I don't know what "cascade of other problems" is since you didn't clarify, so I can't do much there.

However I just pushed a new clean version to the #unity-sdk channel, this should help resolve any issues like this. Just make sure you don't have old files in your solution, as they can cause more errors.
