### ISSUE TITLE
badges are italicized in session menu

### ISSUE THREAD

**Issue by jeanahelver** [Neos-Metaverse/NeosPublic#2355]
## Is your tweak request related to a problem? Please describe.
badges of users that are outside the world show italicized. that includes the patreon logo

## Describe what would you like tweaked
adding `</i>` before badges

## Describe alternatives you've considered
dont italicize badges

## Additional context
![Photo in NumberWang](https://user-images.githubusercontent.com/32199119/119916111-30207380-bf64-11eb-80f4-7a50bad14706.png)

**Comment by AshtonSparx** [comment]
The reason this is the way it is because, they use sprite embedding in their Text Rendering to place the badges with them. I also believe the patreon badge is being removed very soon with our own Supporter badge.

**Comment by Frooxius** [comment]
Thanks for the report! Fixing this would take a bit of a rework of the code for displaying the username (it caches the generated name with all the badges, so by the time it gets to adding <i> tags that's already a single blob) and since the UI is planned to be reworked anyway, we won't be fixing it for the old one, since it's just a cosmetic problem.

The new one will be designed to avoid this problem.
