### ISSUE TITLE
reticle below horizon no longer works - screen 360

### ISSUE THREAD

**Issue by pushstartvr** [Neos-Metaverse/NeosPublic#2357]
Would be great to have this working for the planetarium before 180 fisheye (thanks BTW :)
I can see the problem will be accessing the menu as it takes up the whole screen.  Could the menu be much smaller on 360 mode? and only above horizon when the checkbox is marked?
:)

**Comment by shiftyscales** [comment]
Please use the issue templates when submitting an issue. It is not entirely clear what your issue is, having a full description of the problem, steps to replicate it, and if possible screenshots or video to demonstrate it will help us in understanding your issue so we can address it.

Please feel free to make a new report on this issue following the bug report template.
![image](https://user-images.githubusercontent.com/54213390/120034559-14dc5500-bfb2-11eb-9f0c-6dad7be22635.png)
