### ISSUE TITLE
Add LogiX node: Dynamic Variable Output

### ISSUE THREAD

**Issue by RobertBaruch** [Neos-Metaverse/NeosPublic#2369]
## Is your feature request related to a problem? Please describe.
We have Read Dynamic Variable and the corresponding Write Dynamic Variable. We also have Dynamic Variable Input, but no corresponding Dynamic Variable Output.

In this screenshot, we see the jarring difference between the beautiful use of a Dynamic Variable Input, and the annoying fact that there is no corresponding Dynamic Variable Output:

![Dynvar Output Ex](https://user-images.githubusercontent.com/1783950/120078497-b6bc7a00-c064-11eb-8fca-2ad057d1d4a6.jpg)

## Describe the solution you'd like

A node which does the same thing as Write Dynamic Variable, except the slot is the node's slot in the hierarchy.

![image](https://user-images.githubusercontent.com/1783950/120078958-b329f280-c066-11eb-831a-d6e8844160b5.png)

## Describe alternatives you've considered
Keep using Write Dynamic Variable.

## Requesting User
Xekri

**Comment by Psychpsyo** [comment]
I feel like the way to go here would be to just drive the variable. That's a single drive arrow, pointing into a refcard.

**Comment by shadowpanther** [comment]
Drives are local, writes sync. We have a node for writing already (though you need to provide a slot ref and a name separately), but we don't have a node to drive a dynamic variable. The way I usually do it is pulling an interface card and driving that, but a more clean way similar to Dynamic Var Input would be appreciated.

**Comment by ukilop** [comment]
its worth noting here, 'write dynamic variable' if given no slot reference will behave in that same manner, it attempts to write to a dynamic space that the node itself is currently under

**Comment by shiftyscales** [comment]
Regarding driving dynamic variables- it's outside of their intended scope/design/is a misuse of the components. Related discussion can be found in #1371 @Psychpsyo @shadowpanther @ukilop.

As Frooxius put it:
> If you want it to only be a single fixed source, then you should just use ValueCopy instead (or just wire them directly), using the dynamic system when you don't want it to be really dynamic is using the wrong tool for the job.

https://github.com/Neos-Metaverse/NeosPublic/issues/1371#issuecomment-732334485

Also, the discussion feels out of scope of the issue?

If I'm understanding, the desire is effectively to just modify the existing write dynamic variable node to have its variable name on the node itself?

This doesn't really fit in the design of Logix- the reason it can be done on the input is because it's an input and doesn't receive any values.

Removing the string input from the write dynamic variable node would negatively impact its versatility, and based on my understanding, the only issue presented here is merely aesthetic?

Is this correct, @RobertBaruch?

**Comment by shadowpanther** [comment]
Driving dynamic variables allow for localized (per-user) world-avatar interactions, like driving WorldColor off of music volume, @shiftyscales. There is no way to directly plug the avatar into the world for direct driving or ValueCopy besides using the dynamic variables system. Writing every frame is out of the question too, as it would lag behind and cause a lot of extra sync traffic. Also, music itself could be localized per-user too.

**Comment by RobertBaruch** [comment]
> This doesn't really fit in the design of Logix- the reason it can be done on the input is because it's an input and doesn't receive any values.
>
> Removing the string input from the write dynamic variable node would negatively impact its versatility, and based on my understanding, the only issue presented here is merely aesthetic?

I saw Dynamic Variable Input as a kind of shorthand for Read Dynamic Variable where the slot is its position in the hierarchy, and the name is embedded as a text field. So, Dynamic Variable Output would be a shorthand for Write Dynamic Variable where the slot is its position in the hierarchy, and the name is embedded as a text field.

I get the aesthetic issue -- it would be a long node with inputs, which I don't think we have.

**Comment by RobertBaruch** [comment]
Closing as nonviable.
