### ISSUE TITLE
Autosave should make a noise

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#2383]
## Is your feature request related to a problem? Please describe.
Autosaves currently happen without any warning. (if enabled) This can lead to things not getting saved when they should be (for example when people are holding them)

## Relevant issues
#2382 was the previouly suggested 'fix' for this.

## Describe the solution you'd like
Have an option (or just have it be the default) that the autosave announces itself in some way. (probably a noise)

## Describe alternatives you've considered
Already mentioned and discussed in #2382

**Comment by mralext20** [comment]
Right now, you can rig up some logix such that a moment before autosave (based on last save time, as known from the `on world save` node) an announcement is made.

**Comment by shiftyscales** [comment]
Yeah, as noted this is something that you could probably achieve in Logix. But in the longer term, this is potentially something that could be notified in the notifications system once it is developed?

Either way, auto-saves are more used for preserving work-in-progress states. It's sort of expected that everything might not be where you want it, because when it comes to finalizing the map, you would want to turn off auto-saving, and make a deliberate save after everything is definitely where it needs to be.

Similarly, how myself/others usually handle this scenario is just announcing our intent to save before we do, ensuring anyone that's touching anything they shouldn't stop, or anyone that's spawned anything in can hold onto it/prevent it from being saved.

**Comment by Frooxius** [comment]
This sounds like you'd need the notification to happen shortly before the auto-save occurs? I'm not sure if this would be a good approach though, instead we might end up making the auto-save be more of a recovery function, where it doesn't overwrite the existing copy, but allows you to recover.

Although having an exposed timer before the next save might help as well if you want to rig your own solution.
