### ISSUE TITLE
Cannot UI Align to anything parented under Avatar

### ISSUE THREAD

**Issue by Hayden-da-Serg** [Neos-Metaverse/NeosPublic#2384]
## Describe the bug
Whenever trying to edit Logix on the currently equipped avatar in screen mode, I cannot UI align to any Logix nodes that are parented under said avatar.

## Relevant issues
None to be found

## To Reproduce
- Unpack Logix on the currently equipped avatar while in screen mode
- Attempt to UI align to any of the nodes while working

## Expected behavior
I should be able to UI Align to any Logix node or UI canvas no matter where it's parented.

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.5.29.1365
 - Neos Platform: Windows
 - Link to reproduction World/Item: N/A
 - Regression: Unknown

## Reporters:
Hayden#3180

**Comment by Frooxius** [comment]
This is intentional, you can't edit stuff that's on your active avatar, because this risks creating endless feedback loop,  because the avatar moves based on the UI aligned camera view (and other modes too), but if the camera moves in response of that it can end up spinning or glitching out.

You'll have to hop out of the avatar if you want to edit it this way.
