### ISSUE TITLE
Method to Update tools and items from the Cloud

### ISSUE THREAD

**Issue by seif1** [Neos-Metaverse/NeosPublic#2392]
## Is your feature request related to a problem? Please describe.
The current methods for spawning items from the cloud are rather hacky and prone to problems. And there is no real method for creators to release updates to tools without forcing anyone using the tool to have to completely reinstall the entire thing, as well as any changes they made to it.

## Relevant issues
None that are talking about a update mechanism, more just requests for being able to spawn items from the cloud
#1478, #410, #269

## Describe the solution you'd like
There are so many ways to implement this type of feature that this is meant more as a general overview of things that I could see being useful.

It could trigger a security popup (similar to get/post request), and the most recently added item in that folder is compared to the referenced slot, and any changes which can be easily done (such as new slots, or changed logix) could be updated to the version contained in the folder.

Ideally this component would contain many different options for limiting where it searches, and limiting what it tries to replace by tag, or type (to prevent something like overwriting the textures which are meant to be changed by users), and so on, As well as different settings on how it does its replacement, such as making the item non-persistent to create items which automatically grab the latest version of a tool without having to save a version of the tool on the item itself, and a way to make it not search for new entries past a certain item, for instance, because of incompatibilities in newer versions of the item.

Would obviously not be functional within user space because of security risks associated with that.

## Describe alternatives you've considered
Creators give Every item a link to the folder where the newest version is stored, and some cloud variable or other method of indicating that a updated version is available, which must then be reintegrated, along with any changes made by the user recreated in the updated version.

## Additional context
I understand that this would likely be longer term, and would require systems to deal with conflicts, really the request is about a method by which people could more easily get up to date versions of created tools, without having to go to the specific folder every time, save a new copy of whatever they are working on which uses that tool, and reapply any changes they made to parts of the tool that are otherwise exactly the same. All of this would have to be done for anything they have which uses the updated item.

**Comment by H3BO3** [comment]
This should be covered by the marketplace and licensing.

**Comment by seif1** [comment]
I think this is a more specific update method than what is planned for the marketplace, though I am not sure of everything that is planned in that regard, so I may be wrong.

**Comment by H3BO3** [comment]
Hmm, I imagine a mechanism for that would need to be implemented before/with the marketplace, so I suppose we'll see what Froox says when he's back.

**Comment by shiftyscales** [comment]
@H3BO3 is right, updating items would fall under the purview of item submission/the workshop for which there is issue #145.

Modified/customized versions of tools/avatars/etc. could still be saved to one's personal inventory (license permitting once the licensing system is integrated, which is a separate/later addition) but the workshop itself would serve as a link to the most recently published version of an item.

Much in the way that when you browse/visit worlds you are always visiting the most recently updated/published version the creator has released unless (permissions granting) you save a copy of the world in a state it was in previously.

It wouldn't be possible to make a generic updating mechanism for items that support the changes someone makes to it in a custom version, because they could make any number of arbitrary changes to it, some of which would be implicitly incompatible with the newer version the original tool author released.

If the tool is intended to be skinnable/customizable, hopefully the original object creator would have set their object up in such a way that it is easy to drag and drop any custom bits from version to version.

Also:
> Public folders are just a holdover, they were never designed for public item distribution. The workshop/marketplace will be a proper mechanism to do that. Records already support descriptions, so it'll be just matter of UI for them.

https://discord.com/channels/402159838827905024/477711742001086505/831258862706360342
