### ISSUE TITLE
Importing a 7zbson file with the file dialogue doesn't clean up the holder slot

### ISSUE THREAD

**Issue by Epimonster** [Neos-Metaverse/NeosPublic#2418]
## Describe the bug
If you attempt to import a Neos database 7zbson file using the file importer, the spawned item will be parented under a slot called holder.

## Relevant issues
No other relevant issues

## To Reproduce
1. Configure a file dialogue with your 7zbson link
2. Press the import button on the file dialogue
3. The spawned item is now parented under a Holder slot

## Expected behavior
Expected for this to act in the same way spawning something from your inventory does, or pasting a 7zbson link directly into Neos. This spawns the item then cleans up the holder slot.

## Log Files
The log file simply says starting a gather job the first time it is spawned out and then gives no further errors.

## Screenshots / Video
![20210605023158_1](https://user-images.githubusercontent.com/44652736/120882925-78fdab00-c5a8-11eb-9bf8-7676e5d9fc97.jpg)
![20210605023225_1](https://user-images.githubusercontent.com/44652736/120882897-5c617300-c5a8-11eb-848f-2783686d41f8.jpg)
![20210605023248_1](https://user-images.githubusercontent.com/44652736/120882911-671c0800-c5a8-11eb-9a87-1a249ed94195.jpg)

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.5.29.1055
 - Neos Platform: Any
 - Link to reproduction World/Item: http://cloudx.azurewebsites.net/open/world/U-Gareth48/R-958b0136-bb81-4273-af0e-81d943863549
 - Regression: No

## Additional context
Cannot think of any other context

## Reporters:

Gareth48#3428 and Erin

**Comment by Frooxius** [comment]
This is not a bug. When you import 7zbson file like that, you're doing a raw import, which can include extra structures like that. The system doesn't know that they need to be cleaned up or unpacked, because that's handled by the behaviors that use those files internally.

Generally we **strongly** discourage using those files for import outside of data recovery. They are an internal format that can (and will) change at any moment and they typically need external metadata and other files to work properly and aren't designed to be used standalone. You are risking potential data loss or corruption by using them directly like this.
