### ISSUE TITLE
URI does not properly cast to string

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Neos-Metaverse/NeosPublic#2464]
## Describe the bug
Casting URI to string produces "NULL" even when the URI is proper

## Relevant issues
-

## To Reproduce
1. Cast any URI to string

## Expected behavior
Properly casts the URI back to string

## Log Files
None

## Screenshots / Video
![grafik](https://user-images.githubusercontent.com/61988002/121787468-76add900-cbc6-11eb-808f-9e7f47d7048d.png)

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: Beta 2021.6.10.457
 - Neos Platform: Windows
 - Link to reproduction World/Item: See reproduction
 - Regression: Not sure.

## Additional context
This can be rather annoying when wanting to swap in-between the two or when debugging logix code.

## Reporters:
3x1t_5tyl3# 0001

**Comment by Frooxius** [comment]
Uri's are not castable to a string, because they're not a string. Use the ToString node.

**Comment by mralext20** [comment]
You can also use the multivaluetextformatdriver component.

**Comment by 3x1t-5tyl3** [comment]
I should then probably suggest to block the "uri_to_string_cast" from existing? It seems rather misleading.

**Comment by Frooxius** [comment]
That's a bit tricky issue, because it "already" doesn't actually exist.

For any class types, Neos will create a generic cast instead, which will try to cast any types between each other, but depending on castability the result can be null. Problem is that with some type casts the result will be for some inputs and not null for some others, depending on their actual type.

One of the planned improvements is to check if two types will ever be compatible with each other and prevent instantiating generic casts that are known to never work between two types, but this gets a bit complicated, so it's not a super quick change  and I'm not sure when exactly it'll get prioritized.
