### ISSUE TITLE
Drive Playback Doesn't Maintain Sync Between Video Player Components

### ISSUE THREAD

**Issue by Enverex** [Neos-Metaverse/NeosPublic#2472]
## Describe the bug
I have a video playback component. A Logix node then takes the normalised playback position of that component and feeds it into 8 other video playback components.

## Relevant issues
None.

## To Reproduce
1. Create a video player playing a remote video file with stream enabled.
2. Create additional video players, also set to stream the remote file.
3. Use Logix to set up a Drive Playback driving the extra video players with the normalised position of the original player.

Note that these are not streams, we're just using the Stream option here so that Neos doesn't try and download the whole file at once before playing. Instead to chunk-load it as it plays back. Setting the MaximumPositionError appears to have no effect, no matter how low it's set (even as low as 0.001). Not only will the additional players not stay synced with the main video, they will be desynced with each other too.

## Expected behavior
For the video players to all remain in sync given that they are all being driven to identical timestamps.

## Log Files
N/A

## Screenshots / Video
The video feeds claim to be at the same timestamp (or at least close enough, the difference here is ~10ms) yet in reality it was nearly a full second out of sync.
![image](https://user-images.githubusercontent.com/958670/121823789-5b62cc80-cc9f-11eb-80cd-efefc330fde6.png)

In this example, they showed the same timestamps, but were again desynced from one-another.
![image](https://user-images.githubusercontent.com/958670/121823851-b98faf80-cc9f-11eb-9cdc-4322eef8d3f5.png)

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.6.10.457
 - Neos Platform: Windows
 - Link to reproduction World/Item: An example world exists but needs some guiding to recreate the issue.
 - Regression: No

## Additional context
Changing the video players to not Stream either helps very little or it's just a plecebo effect, they still desync. Also pausing the main video (which all others have their position driven from) then unpausing changes how much (or if) all the others are desynced, as does seeking.

**Comment by Frooxius** [comment]
What exactly are you trying to achieve with this?

This is unfortunately just aspect of the video playback - given the complexities and unpredictability of video playback, there's a small amount of slack (1-2 seconds) of the actual playback compared to the timestamp, to account for things like the seeking and buffering taking some time to complete, as well as the video playback engine not reporting the current playback position with enough precision (e.g. the libVLC updates just a few times a second, but not often enough).

If you tried to enforce the timestamp with a much narrower margin for error, the video playback might end up degrading significantly and just constantly jump around as it tries to correct the actual playback position. With streaming and network delays this is even worse, as there's unpredictable amount of buffering time required for each change.

We could potentially expose and allow this amount of error to be configurable beyond the safe limits, but you might just end up with the video playback becoming unusable. Guaranteeing perfect sync between several independent playbacks would require a more advanced system.

Generally I'd recommend encoding everything you need into a single video and then UV mapping parts of it where you need (or using texture offset and texture scale).

**Comment by shadowpanther** [comment]
I believe the intention here was to emulate cinema 5.1/7.1 setup with separate audio sources because Neos doesn't allow to extract separate audio channels from one stream and map them to different audio outputs. The ideal solution would be just that - support loading multichannel audio in video streams and allow mapping such streams to a set of audio outputs.

**Comment by Enverex** [comment]
> Generally I'd recommend encoding everything you need into a single video and then UV mapping parts of it where you need (or using texture offset and texture scale).

As Shadow has already mentioned, the purpose of this was for recreating a working 7.1 cinema so the key here was audio splitting.

The reason the audio sources were videos in my original example was because of Neos' lack of audio streaming capabilities right now, so they're "videos" (not really videos, the video is a static 64x64 black image) is for the streaming functionality to be usable.

**Comment by Frooxius** [comment]
I see. I understand the issue, but unfortunately this is not a suitable way to achieve that effect. Between the buffering, networking, decoding delays and imprecision of the video playback position, you will never be able to get them perfectly synced up to sync different audio channels across multiple independent video playback streams.

To achieve that they would need to be part of a singular stream and decoded and processed together, as is in case of 7.1 audio, or we'd have to write some custom decoder and system to match the presentation timestamps (note that even the video playback itself has a small slack for the audio synchronization itself, so the individual streams might not still match up exactly). 

Proper way to do this would be split the audio streams from a single video source. That's something we can add, I can see if there's a way to add it quicker that won't compromise long term compatibility if the issue is important enough to people, but this one I'll have to close as it's not something that's feasible to achieve, sorry.
