### ISSUE TITLE
Tip Jar Component doesn't let you choose which type of currency you'd like to see tipped

### ISSUE THREAD

**Issue by mirpasec** [Neos-Metaverse/NeosPublic#2509]
## Is your tweak request related to a problem? Please describe.
Recently, there has been a case of sending money incorrectly in the Korean community. So, if there is a function to select the currency to be used in the TipJar component, I wonder if such an accident can be prevented in advance.

## Describe what would you like tweaked
I would like to add a property to select a currency in the form of a selection box in the TipJar component. The selection box has 'User choice', 'NCR' and 'KFC'.  Default value is 'User choice' for compatable.

## Describe alternatives you've considered
I'm also thinking of a way to draw attention by making the text in the remittance window stand out. But it won't be a solution to the underlying problem.

**Comment by TehTurk** [comment]
https://i.imgur.com/1CRs9om.png 
Went to go investigate this one a bit because it was brought up to me. I wanted to make sure this didn't fly under the radar as this has to deal with money and language barrier sometimes has us missing stuff. I think having something to determine what kind of tip the creator would be important. Allowing Creators prevent NCR if they just want it to be KFC as play money.

**Comment by Frooxius** [comment]
Added in 2021.6.23.11! Thanks!
