### ISSUE TITLE
LogiX node: Dynamic Variable Output (driven)

### ISSUE THREAD

**Issue by shadowpanther** [Neos-Metaverse/NeosPublic#2555]
## Is your feature request related to a problem? Please describe.
Sometimes I need to drive the value of a dynamic variable. Reasons for driving the value are:
- the need to put a constantly changing value into a dynvar
- the need to "localize" the value

## Relevant issues
#2369, but that one was about replacing the Write Dynamic Variable node

## Describe the solution you'd like
A node that has one typed input for the value and a field for the variable name on its face, similar to Dynamic Variable Input.

## Describe alternatives you've considered
Creating a component for the dynamic variable and driving its value through an interface card.

## Additional context
One big example of a dynamic variable that needs to be local and driven is the world color standard. Usually it's used in tandem with a music player and drives the color/intensity locally for each user depending on the music they have playing locally.
Other example would be passing values between separate parts of LogiX of one object.

**Comment by Earthmark** [comment]
I was just about to make an issue for this, this pattern came up a lot during the creation of the mentor panel. Being able to have self contained LogiX functions is very much helped along with having this kind of a feature.

**Comment by TehTurk** [comment]
Hmm wouldn't this just be a DynamicVariableDriver but in Logix Form I'd gather? Couldn't one just have an DynVarInput and drive from that normally?

**Comment by shadowpanther** [comment]
> Hmm wouldn't this just be a DynamicVariableDriver but in Logix Form I'd gather? Couldn't one just have an DynVarInput and drive from that normally?

No, DynVarDriver drives _from_ the DynVar. This one drives the DynVar itself.

**Comment by shiftyscales** [comment]
This one is fundamentally the same issue as #1371.

**Comment by shadowpanther** [comment]
Yes, @shiftyscales, and I saw that argument in the mentioned #2369. But I'm doing it anyway, just in a mixed way by having a component, an interface card and some LogiX driving it. I ask for more convenient LogiX-only way to do the same to get rid of the component and interface card part.

In other words, I have a "broadcast" source that some random consumers would plug into dynamically. ValueCopy won't fit this use pattern at all. If that's not the proper way to use dynamic variables, we need another similar dynamically-connected concept with just one source per namespace and many consumers.

**Comment by Earthmark** [comment]
From the previous issue that was linked, I do agree it is related. Also yeah a value copy would be better in a lot of cases, although to me that's like saying "don't use small functions in code, use big ones cause they're faster", it may be true that it's often faster, but it's much less maintainable in my experience.

If you get a chance possibly look to the mentor signal panel for some usages like this, that logic is function based because it would be much more complicated if all the code was slammed into one slot (although that is a matter of debate).

The panel currently uses state dynamic variables that are driven by backing logix, because that way I can more easily mentally compartmentalize the code. (I'm a fan of making things legible over super super optimized, although if I can do both at the same time that's a plus).

One alternative to this may be dynamic relays, so instead of linking a hard component value, it's linking LogiX nodes through the dynamic space. That way the propagation style of LogiX is maintained.
