### ISSUE TITLE
Documentation: Write's Sync-Behavior

### ISSUE THREAD

**Issue by Banane9** [Neos-Metaverse/NeosPublic#2590]
## Where have you searched for this information before making this issue?
I have looked through the Issues, Wiki and of course discussed with other people in the community, but no one is sure how it works.

## Which part of the system do you need information on?
Specifically the value syncing behavior of the Write (Ref) nodes.

## What information do you need to know?
There's two points of unclarity:
1. When multiple writes are performed in one update: Does only the last value get synced to others, or does it create sync packets for each intermediate value?

2. When a Field is being driven by a ValueCopy to itself with write back enabled, it can be written to just fine and all values stay local. However the question is whether the action of writing to it still generates a sync package or if the driving prevents that.

## Do you plan to format and contribute the provided information to Wiki?
The answers to this would make sense to be added to the Wiki pages on the Write nodes and the ValueCopy component.  
Currently the WriteNode page says that each written value gets synced and no page exists for ValueCopy.

**Comment by Frooxius** [comment]
Write and any other components that change values do not do any sync at all (or care about it), they only mutate the data model. Synchronization in Neos is completely separate from all the behaviors, any mutations of the data model are automatically replicated to other users and all components are pretty much abstracted from any networking.

The answers to this are general and not specific to a particular node.

1. Generally only the last value will end up being replicated to the user. The changes in the data model are sent at the end of every update. However this can be a bit different if the value is being synced via a stream - e.g. player's position and rotation. In that case the value is continually streamed and interpolated. Also the data model by default resolves conflict, if you have multiple users writing to the value, that will generate extra network chatter to correct any conflicts (this follows "latest write wins" principle from the reference of the server).
2. Driving is telling the data model "Don't replicate this, I'm responsible for computing this for every user". As long as this doesn't result in a change of any non-driven value, there will be no network traffic. There will still be sync when the data model is fully encoded for newly joined users, but that's all.

Internally Neos already supports local only parts of the data model and you can have data that's purely local too, but right now that doesn't quite fit into other parts of the system yet, notably LogiX. It's something to be a bit careful with, since you can end up shooting yourself into the foot with it easily (e.g. causing divergent behavior that's not intentional, but won't show itself until some multi-user scenarios), using values that are local only or generating other updates and that might not be desirable.

We're working on managing this in a proper formal way to make sure that the system will warn you about potentially problematic uses and require you to mark that it's what you want to do.

But other than that, driving value from itself is perfectly fine to only update it locally! For example you can drive a rotation from itself, adding a little increment every frame. It won't be synced across users, but if it's purely visual and it doesn't matter, then it's an ok approach as long as you're aware of it.

There were a few cases where it has cause some issues. Some people have built vehicles using this method. They worked great, except they would drift over time, causing everyone to see the person at a completely different spot in the world, so using write that syncs would be the necessary approach there.

I hope this info helps, let me know if there's anything else that's unclear!

**Comment by Banane9** [comment]
Thank you for the detailed comment!

It is working as I expected then, regarding not generating sync packets and only using the latest value, but since there was disagreement on it, we wanted to get some Word of God on it, especially since it was seen as a bit of a hacky work around 👍

**Comment by Banane9** [comment]
Speaking of divergent behavior though... certainly produced at least one interesting interaction with it:

The dynamic variable component's value is localized using value copy, and gets set back to false whenever it was true to generate one update long true values - this works fine when it's being set by other logix, but turns into an infinite spam when set in the inspector, even though the value shows as false.

![Infinite fire while true on a value that's false.](https://user-images.githubusercontent.com/2124570/124622321-4c74d180-de7b-11eb-944c-0f78a611a599.jpg)

But that's perhaps something for another issue.

**Comment by shadowpanther** [comment]
@Frooxius some clarification - if the self-driven (ValueCopy+WriteBack) value is modified by a Write (required to do because it happens on an impulse) for one user - does this cause any sync? The value is technically changed in the datamodel for this one user (should sync?), but the value is still driven for all users (should not sync?). What "wins" in this case.

**Comment by H3BO3** [comment]
@shadowpanther What's happening there is the drive is being marked as locally calculated - And when someone tries to write to that value, it's a hook - it updates itself to change to that new value because it that change happened locally, but nobody else sees that change because the field is being driven and is telling them to only update it on their end. No replication happens

**Comment by Zyzyl** [comment]
The key bits of this (at least related to LogiX) as been transcribed to https://wiki.neos.com/Write_(LogiX_node)

@Banane9 are you happy to close this issue, or were you looking for any additional information?

**Comment by Banane9** [comment]
Seems good to me 👍
