### ISSUE TITLE
Guidelines about how to help/contribute.

### ISSUE THREAD

**Issue by Z2Up1UwcaYOyZq** [Neos-Metaverse/NeosPublic#2597]
## Goal of discussion
To determine every way you can help Neos by growing the playerbase or making it a better ~~game~~ metaverse. 
Also a wiki page/FAQ entry/Readme update/poster would be nice, for easier spread across the community.

## Discussion:
Currently I can't see anywhere a word about how an average player can help Neos (not counting Patreon).

So I made a rough "How can YOU help?" poster to show an example of how engaging to help should look (and that it sometimes is as easy as just playing the game with friends)
![helping](https://user-images.githubusercontent.com/81369284/124679647-57982380-deb4-11eb-8dba-dbde888c8ed7.jpg)

As stated in the Goal of discussion: I don't know every way of engaging a community, so please help me brainstorming new ones.

**Comment by ProbablePrime** [comment]
This is a good idea, I'll investigate creating a Wiki page for this.

**Comment by Mysticporo** [comment]
Determining a goal via popularity is something that is separates a user base into categories that could make the user base potentially an extremely toxic environment in my opinion,
perhaps I can see where you’re coming from if the goal is to help the community in general but that happens the majority of the time from my perspective as Neos is a fairly constructive and nurturing place.

**Comment by TehTurk** [comment]
We have this in some form of the #faq on the Neos Discord and the (https://wiki.neos.com/Main_Page Neos Wiki) but I think a simple document like this could have its uses. I'd like to assist with this if I can as well Prime. With stuff like this is tricky because not everyone will always see the document as well because when people want to help, they won't always ask what's ok to do first.

Ideally with stuff like this for ways to at least answer your initial question to contribute is we ask people to report bugs, suggest ideas (usually after seeing if it's been said first), give us constructive feedback, let people know about the platform, and make cool neat things within it, but also keep the positive collaborative nature that Neos is.

If your interested in supporting the platform through volunteer efforts, there is also the Mentors, but I'd recommend getting adjusted to the platform before applying. Generally these are community members who take their time to volunteer where they can [Mentors](https://wiki.neos.com/Mentors)

@Mysticporo It's less what's on the current page and more so the general idea of "Wana help? Here's what you can do" I don't think we'd have something specifically for that.

**Comment by ProbablePrime** [comment]
I'll be writing a first draft shortly and people can edit that from there.

**Comment by Vegasx** [comment]
Instructions unclear, I reported my friends

**Comment by ProbablePrime** [comment]
This page is now created here: https://wiki.neos.com/How_to_Help

And i'll be integrating it into various sources soon.

Thanks for your request!
