### ISSUE TITLE
NeosDB Links

### ISSUE THREAD

**Issue by win189** [Neos-Metaverse/NeosPublic#2612]
## Where have you searched for this information before making this issue?
i have asked arround and there are many differant what appear to be ideas of how NeosDB or Item storage works and would like to have this More Clairifyed rather then going to staff and multi people asking

## Which part of the system do you need information on?
NeosDB links and how our storage works with Azure

## What information do you need to know?

Do items have an Expiry date meaning if I log in today and don't use this item or whatnot for 6moths + ,,,, will the item get removed?

Do Neosdb Url Links have an Expiry date/time when the link is repopulated or is it on the first creation of the item and kept the same indefinite

What actions can one do that may inadvertently cause a change to the neosdb link for said item 

## Do you plan to format and contribute the provided information to Wiki?
I wouldn't mind but throughs with better language skills then mine should proofread it :P

**Comment by win189** [comment]
Also forgot to ask to also know who can access  this dblink

**Comment by H3BO3** [comment]
NeosDB links are just a pointer to a file in the cloud, more or less.

When you save an item or world with an asset provider (containing a valid asset url) to your inventory, that asset is pinned to your account - Other people can also pin the same asset to their account by saving the item too.

Items will not expire as long as they are pinned to someone's account. For general purposes, pinned assets will reflect in your cloud space indicator and also in your storage records if you decide to fetch them. Bear in mind that some assets are counted as "free" and will not take up your storage space. The same unique asset saved multiple times will only count once, as it has previously been pinned. https://discord.com/channels/402159838827905024/439422161657135106/723609395031703668

Assets that are no longer pinned by any user are permanently deleted from the cloud after 30 days. https://discord.com/channels/402159838827905024/469131434628612116/491238974757797896

The link itself does not expire or change. However, if you modify the asset in-game somehow (For instance, using the buttons on the asset provider components to make edits to it) and then re-save it, it will count as a new unique asset and have a new hash/URL. You do not have to worry about managing any URL changes since the asset provider will keep it updated automatically.

I do not know much about security regarding raw neosdb asset urls, if such a thing even exists - The length of the hash should be sufficient to obfuscate access, imo. Someone else will have to answer that.

**Comment by win189** [comment]
Thanks, i will copy a bunch of this and make a Wiki Post as that is where most people should be Looking through there and no 20 million discord messages and possible pins
