### ISSUE TITLE
Saving the default avatar with the save current avatar button deletes the users head

### ISSUE THREAD

**Issue by Earthmark** [Neos-Metaverse/NeosPublic#2629]
## Describe the bug
New users, when learning about save avatar, often press the save current avatar button. If they have not picked a new avatar yet this, through some interaction, deletes their head and they no longer have an audio output.

This can be a trap for new users, as it's not straight forward that this has happened.

## Relevant issues
Unsure

## To Reproduce
Be in the default headset
Click the save-current-avatar button (blue down arrow)
Notice that you can no longer talk.

## Expected behavior
Nothing happens, the avatar head is maintained, nothing is saved to the inventory.

## Log Files
I can provide one if requested.

## Screenshots / Video
The user I am looking at just got their avatar on, so I do not have a picture, but it's a user just without a head.

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? No
 - Neos Version: 2021.7.11.1002
 - Neos Platform: Windows
 - Link to reproduction World/Item: Any time an avatar is not equipped
 - Regression: This has been a constant issue.

## Additional context
 While I was typing this report one of the two new users in the world I'm in did this exact case...

## Reporters:
Earthmark#0314 Earthmark

**Comment by shiftyscales** [comment]
This actually is a duplicate issue of #725, and is technically correct (although undesirable) behavior due to the AvatarDestroyOnDequip component present. More details on the considerations with the issue, and previous attempts to deal with it are present on that issue as well.

Thanks for bringing this back up again though.

**Comment by Earthmark** [comment]
I do personally feel this is still under the bug label tbh, from the users perspective them being left unable to speak without a viable reason was very stressful for them, but perhaps I am not understanding why this is considered a feature. What purpose does this serve if it's a feature?

**Comment by shiftyscales** [comment]
I'm not saying it's not an issue nor that it's a feature, @Earthmark - just that there is nothing technically wrong as everything is doing what it's meant to do, even if the end result is undesirable. During the avatar saving process, the avatar is dequipped, as the avatar is dequipped, it is destroyed because it's triggering the AvatarDestroyOnDequip component.

This is something that could be looked into again though by our content builders now that we are using a customizable (not hardcoded) default avatar- so perhaps the default avatar could be set up such that it doesn't use the AvatarDestroyOnDequip at all, meaning that if a user switches into a new avatar (in-world) it would leave behind the headset.

**Comment by H3BO3** [comment]
What if the behavior was changed so you just couldn't save an avatar with an avatardestroyondequip component?

**Comment by Earthmark** [comment]
when I ponder this topic, I wonder would it be possible to have an avatar without a head? In such a case would the user be unable to speak?
When a user equips an avatar without hands they are provided hands, could they be provided a head if they equipped an avatar without a head?

My though is then it would be using an existing system used to spawn the hands, although I'll need to check if this is an issue with headless avatars.

**Comment by Earthmark** [comment]
Verified, this issue occurs with an avatar that does not have a head either. Akwardly a head is provided for the avatar at first, but when you attempt to save the only-hands avatar the save fails, and the head is destroyed.

This is my low poly avatar where I have destroyed the head and left hand before equipping the avatar.
![image](https://user-images.githubusercontent.com/1251609/125717529-c5917ed5-0efc-4eae-8ee0-1a29e04991c7.png)

![image](https://user-images.githubusercontent.com/1251609/125717556-adc452e3-771d-451a-b011-30e28d99e67b.png)
Note, the default provided hand is still provided.

I can make this a different issue if requested, but the head seems to not come back when destroyed.
It does appear a Dummy Head slot is added for the head node, however the head has nothing on it.

**Comment by Earthmark** [comment]
Seems like even the name badge survives re-equip, I believe this bug is that the headset does not survive re-equip, instead of the headset deleting itself on save.

**Comment by Frooxius** [comment]
This is a duplicate of https://github.com/Neos-Metaverse/NeosPublic/issues/725 and a known issue. Could we merge this into one issue (either closing that one or this one) so the conversation isn't split across two different places? 

As mentioned in the other thread, I already attempted to fix this by making it not possible to save the default avatar, but this ran into issues that made it a fair bit more complicated.

Alternative simple solution is to just remove the DestroyOnDequip from the default avatar, since it might be a relic that isn't likely to be needed much anymore.

The system will fill any missing slots - that's how the head and hands get spawned. However the interactions with the saving system and other parts make this a bit more complicated, which is why it breaks. I wouldn't go for this fix, as it's dealing more with the symptoms, rather than the cause.

**Comment by Earthmark** [comment]
Ahh, I'll close this in deferment to that then. Hope you have a good one!
