### ISSUE TITLE
Separate Permission: Export Any Objects / Save Any Objects

### ISSUE THREAD

**Issue by kazu0617** [Neos-Metaverse/NeosPublic#2716]
### Is your feature request related to a problem? Please describe.

This problem was encountered when I was using Logix as an alternative measure to describe items that I did not want to be taken outside of Neos, since I could not currently control them with Tags #2513 .

### Relevant issues

I think #2513 and #289 . #289 is soft relevant.

### Describe the solution you'd like

Currently, WorldPermission has an option called OnSavingItems, which checks both saving and exporting of items.
This check is used to check both saving and exporting of items, and the exporting bypasses the Persistent option even if the hierarchy is turned off. In contrast, saves go through the OnSaving node and do not save items that have the appropriate Logix processing running or Persistent turned off.

Therefore, separating export and save as specific options in WorldPermission will solve this problem.

### Describe alternatives you've considered

This problem can also be solved by including OnSaving and Persistent processing in the export process.
However, as far as the export UI is concerned, I don't think this will solve the problem in the short term as it will be part of UI/UX Overhauls.

### Additional context

I will set this up for the next event if I can get it done in time.

**Comment by Frooxius** [comment]
Adding this to the existing permission system would unfortunately open up a hole. If you're allowed to save items, but not export, the user could simply save the item, open their own world and export it from there, since the permission is tied to the world and not the item.

Preventing export while allowing saving would be handled by the Object ID / License System: https://github.com/Neos-Metaverse/NeosPublic/issues/21

I'm going to close this one, as adding this option would create false sense of security that item cannot be exported, when in reality it could be easily worked around, sorry!

I recommend upvoting the issue above if you're interested in a robust solution for this.
