### ISSUE TITLE
Contacts tab looks broken when logged out

### ISSUE THREAD

**Issue by RestrainedRaptor** [Neos-Metaverse/NeosPublic#2718]
### Describe the bug?

When I opened Neos and tried to access my friends list, I was greeted with an empty, broken chat UI.

After restarting Neos a few times and asking the Neos Discord for help, it turns out I wasn't logged in. This is completely unintuitive, given that it says 'all synced' at the top and I can continue to see active world sessions in the Worlds panel and local home world.

There are probably several other areas where the UI could make this clearer, since other new users, like me, probably aren't aware that you could use Neos entirely offline.

### Relevant issues

None found

### To Reproduce

- Be logged out of Neos
- Open the dashboard and go to Contacts.

### Expected behavior

- The page should clearly state that you're not logged in.
- Perhaps Neos should ask you if you want to log in or continue offline when starting up (as a novice user, I didn't know it was possible to get this far without being logged in)

### Screenshots

![image](https://user-images.githubusercontent.com/52027008/127088931-9ead6f9e-b5f3-46e9-8ace-d3e595d004ea.png)

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.7.25.489

### What Platforms does this occur on?

Windows

### Did this work before?

I Don't Know

**Comment by shadowpanther** [comment]
You might have also noticed that you loaded into your Local Home only instead of Cloud Home, and that the facet on your Home tab of the Dash has a button for login instead of your username. Neos doesn't force you to log in, you can use it as an anonymous user, you just don't have access to most of the Cloud functions.

To make some parallels, you can browse GitHub without logging in, you just miss the functionality to post stuff.

**Comment by kazu0617** [comment]
Is it possible that some tabs are masked so that they are not available when you are logged out...? (I think masking, adding, or removing specific tabs is needed for enterprise purposes, but I don't know the specifics.

ログアウト状態では一部のタブが使えないようにマスクされるとか…？（特定のタブのマスクや追加や削除についてはエンタープライズ目的で必要とされている気もしますが、具体的にはわからないです。）

**Comment by shadowpanther** [comment]
The other way to show it would be to just add "Not logged in" text across the contacts and inventory tabs, but those both are legacy UI and require a full remake to allow to make changes efficiently.

**Comment by RestrainedRaptor** [comment]
> You might have also noticed that you loaded into your Local Home only instead of Cloud Home, 

I wouldn't have noticed because I'm a new user and don't have a custom cloud home set up. I'd definitely prefer to see something more prominent or in-your-face when loading up Neos to let me know that I'm not logged in.

**Comment by Frooxius** [comment]
Thank you for the report. We understand the issue, but don't plan fixing this in the old UI, as it's due to be completely scrapped and redesigned. The new UI will take this into account.
