### ISSUE TITLE
Unknown Behavior for UnresolvedReferences & A method to clear it or self cleanup

### ISSUE THREAD

**Issue by AshtonSparx** [Neos-Metaverse/NeosPublic#2744]
### Is your tweak request related to a problem? Please describe.

For a long time now, UnresolvedReferences has gone into the shadows of worlds on root, building itself a collection of ID tags that we have no idea what they point to, and possibly linked to Assets being held in worlds even if

- Unused assets are set to clear after X amount of time
- You manually try to clear those assets knowing they're no longer in the world. They rebuild themself as AssetName - Assets - Assets
- Clearing the component's content manually, saving the world and restarting it. It build's itself again.

ProbablePrime in the past has tried figuring out what this component does, why it exists, how to fix it. But to no avail.

### Describe what would you like tweaked

I would like a few things regarding this component.

1. Documentation on how this component works.
2. A method to clear this component. Rather manually but preferred, automatically. I've not fully tested it, but it seems it also holds assets it's referencing. I have in my world Holder - Assets that contain old LogixInterfaceProxy's with the _worker pointing to [Number] on UnresolvedReferences on Root. Deleting this with the red trashcan, saving and reloading the world, seems to fully get rid of it, but I'm not fully sure if this will always work. Other's can probably talk about their experience with this component in the comments.

### Describe alternatives you've considered

If nothing can be done about this component, at least have an option to wipe the references it contains, or a way for the user to figure out what the problem could be and fix it themself.

### Additional context

My world has 262 unresolved references, I don't know what any of them points to. Kulza told me their VBLFC worlds had approx 700 of them, Their method was saving the entire world into their inventory. Creating a new world and spawning it back out in the fresh world.

**Comment by Frooxius** [comment]
This is not an user facing component, you shouldn't ever use or touch it yourself, it's internal use only. Doing so can break things and result in data loss.

Internally it's used to track any references to objects that didn't load (e.g. due to missing components and such), so they can be properly saved back if those objects still point to those missing components.

There is no need to clear it, because it's not persistent. It's generated automatically on load of the world. If you want to reduce unresolved references, you can clear up any objects and missing components on the world and items or simply point them to a different object, but I strongly discourage nuking the whole component.
