### ISSUE TITLE
Allow asset url redirect from http(s) to neosdb

### ISSUE THREAD

**Issue by Earthmark** [Neos-Metaverse/NeosPublic#2772]
### Is your feature request related to a problem? Please describe.

I want to make an asset loader that can redirect to different assets based on the choices of a webserver, to do this I can make a webserver do redirects to an http url, but not a neosdb url. My hope is with a redirect to neosdb I can have the asset variant system pre-process the asset, instead of needing each client to do that processing as a secondary step.

### Describe the solution you'd like

A webserver returning a 302 with a neosdb target is then processed as a neosdb target (AKA goes through the same caching and loading mechanism as it normally does).

### Describe alternatives you've considered

Sticking to http, this would be fine but my goal is to make this as efficient as possible. Not using the asset variant system seems like a waste.

### Additional context

Aggressive caching of the http urls already occurs and that's fine, I'm expecting to need a cache-breaker in the url for this to work as expected.

**Comment by Frooxius** [comment]
Unfortunately this isn't something we'd likely implement, as it goes against the design of the system. By the time the http(s) URL gets loaded, it's too late for any of the asset variant system to kick in, because it needs to know in advance (from the direct URL) what is it going to be doing - for neosdb URL's it actually requests a bunch of metadata before it even gets to the loading part.

Supporting this would require either significant re-engineering of our systems to do it cleanly or some brittle hackery, that would cause us a bunch of problems in the future (and consequently to any Neos users).

I'd recommend utilizing the in-game systems instead. If you want the URL to change by external webserver, make a request to it as you would normally and then assign the resulting neosdb to the field on the asset provider.

If you have more specific needs/use-cases for this, we can look into other solutions that are native to Neos and work well with the existing design of the systems.
