### ISSUE TITLE
Blendshape normals don't import

### ISSUE THREAD

**Issue by zkxs** [Neos-Metaverse/NeosPublic#2909]
### Describe the bug?

When importing a mesh, the normal data for blendshapes is stripped out. This causes weird artifacting on some materials when blendshapes are nonzero.

I do not know if this affects all import file formats or not. I've been told people are having mixed results using formats like .gltf. .glb appears to be working.

### Relevant issues

Searching for terms like "blendshape", "shape key", and "normals" yielded no open issues.

Looking at closed issues, #1709 might be relevant? Not sure.

### To Reproduce

1. Import a mesh with blendshapes.
2. Use a material that uses normals (e.g. something reflective).
3. Set the blendshape, and observe how the normals are now incorrect

### Expected behavior

Blendshapes should properly update the normals when they are changed.

### Screenshots

This is a .blend cube with a blendshape that deforms it into a sphere:
![image](https://user-images.githubusercontent.com/1807509/131581351-55623a82-65ca-450b-95c2-335382188eb4.png)

Same object, but imported as .glb. I don't know what's up with the hard edges, but the normals appear to be working:
![image](https://user-images.githubusercontent.com/1807509/131583112-d2d32fe8-d49c-4cce-95b6-3dbcae63e447.png)

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.8.29.1240

### What Platforms does this occur on?

Windows

### Did this work before?

I Don't Know

### Additional context

Blender project for the cube: [CubeBall.zip](https://github.com/Neos-Metaverse/NeosPublic/files/7087060/CubeBall.zip)

### Reporters

Azavit#2360 demonstrated the problem to me in-game
JackTheFoxOtter made the reproduction item (CubeBall.blend)
Enverex#6528 reported on discord
zkxs#1039 (runtime) wrote the dang bug report despite being a blender novice 😠

**Comment by Enverex** [comment]
An example on a model:
![image](https://user-images.githubusercontent.com/958670/131584342-34af878c-508b-4516-be86-181942688e4d.png)

This happens in Unity as well, but can be negated in Unity by enabling their "Legacy Blend Shape" or "Blend Shape Normal: Import" option. There appears to be no similar option in Neos to negate the issue.

**Comment by ModernBalloonie** [comment]
To add to this, this only happens when you import as FBX or BLEND I believe. I've been sucessful with importing normals with the GLB file format. It seems FBX and BLEND fail though.

**Comment by ModernBalloonie** [comment]
https://www.youtube.com/watch?v=qlcrBNu2nF4 I made a video on the topic

**Comment by Enverex** [comment]
> To add to this, this only happens when you import as FBX or BLEND I believe. I've been sucessful with importing normals with the GLB/GLTF file format. It seems FBX and BLEND fail though.

This happened for me regardless of format. Trying GLB was literally the first thing I tried.

**Comment by Frooxius** [comment]
I've looked into this and unfortunately this isn't a bug in Neos, but in Blender. When Blender exports the FBX, it includes Blendshape normals of the base mesh, instead of the actual deformed blendshape - the normals that you get in Neos from the FBX are the actual normals that the FBX file specifies, so there's nothing wrong on our end.

Blender's GLTF exporter includes correct normals, so Neos imports those correctly. When you import .blend file directly, Neos exports it to .fbx in the background from Blender. We can see if we can switch this to .gltf, but we need to make sure this doesn't break stuff.

You can verify that this is issue with Blender by using the FBX2GLTF converter that's based on the official FBX SDK: https://github.com/facebookincubator/FBX2glTF/releases/tag/v0.9.7

Export the FBX from Blender to GLTF and import to Neos - the normals are still wrong.

I recommend reporting this bug to Blender and using GLTF in the meanwhile. I'm going to look into Blendshape normal recalculation in the meanwhile as per #3075

**Comment by Enverex** [comment]
This doesn't appear to have resolved the issue in my case. Exporting from Blender as GLB (from the original Blend file, not an FBX) still has the same issues in Neos as the FBX did.
![image](https://user-images.githubusercontent.com/958670/134980866-48e5ed49-13e6-4e2d-8214-d27b9e303399.png)

Here's the same model in Unity, switching between imported and calculated Blendshape normals.
https://cdn.discordapp.com/attachments/439422161657135106/892043100279701554/Normals.gif

Calculate never works in Unity, only import, so it feels like the missing functionality in Neos here is the ability to import the normals as opposed to calculating them.

**Comment by Enverex** [comment]
>Importing the model as Centimeters is now no longer 1:1 scale.

When using GLTF/GLB you want to use metres.

**Comment by Irick** [comment]
We've been bit a couple times by the new defaults. We can no longer replace meshes from previously imported .blend files with new ones without exporting to FBX as an intermediary. Scale also appears to differ now compared to the same settings in prior imports.

**Comment by Epimonster** [comment]
An error being caused by this is vertex colors are importing as darker than they are in Neos. If you look here I have the same blend file exported as an fbx, and imported using the new blend importer, the blend import doesn't match up the the viewport at all. On a more technical level it appears that the blend file's vertex colors are being multiplied by themselves on export, resulting in the saturation increase, though it could also be some color space shenanigans.

![content](https://user-images.githubusercontent.com/44652736/136276123-3079497a-d4e2-4a08-85be-041158bbb969.PNG)
