### ISSUE TITLE
Making the head viewpoint be seperated from the head proxy but having the same rotation values

### ISSUE THREAD

**Issue by alexderpyfox** [Neos-Metaverse/NeosPublic#2941]
### Is your feature request related to a problem? Please describe.

So basically this was after taking in the ? Channel about the viewpoint and the current way of having the viewpoint disconnected doesn't really work for our usecase so what i would like is the head proxy and view position to be seperated but movable from eachoter but keeping the same rotation values this would be for when you move the viewpoint forward so the rotation swing  of the view point says the same so it doesn't become nauseating currently using the  avataruserrootoverrideassignerview for it makes the view rotation swing be too big and Shakey to be properly useable as viewpoint adjustment 

### Relevant issues

Decoupled Viewposition 

### Describe the solution you'd like

The feature 

### Describe alternatives you've considered

Value copy's altho not sure if that works either

### Additional context

Requested by @sylva and @alexderpyfox

**Comment by Frooxius** [comment]
You can already do this by decoupling the Root instead of View. That will preserve the neck model and view of the avatar.

Decoupling View will most likely be nauseating in VR, because to be comfortable the motions in VR need to be 1:1 with your physical movement (in other words coupled) and decoupling them makes them diverge.

It's strongly discouraged to use it in VR in particular for most things, decoupling Root will provide better option there to change the view.
