### ISSUE TITLE
Allow string locale driver to take a fallback, directly provided, translation string

### ISSUE THREAD

**Issue by Earthmark** [Neos-Metaverse/NeosPublic#2960]
### Is your feature request related to a problem? Please describe.

With the localization toolkit an issue has come up where the kit doesn't support the localization syntax that neos does.

The toolkit itself is a placeholder until #1715 is done, but something that's been useful with the tool has been modifying the text to localize from inside the game, which I do but believe is directly supported at the moment.

There's also an odd edge case I've encountered when adding locale string drivers to the mentor signal. You need the new strings to be released in a full release before the tool is released. This complicates the workflow, and Git might be walking into this one if attempts to translate neos essentials are made.

### Relevant issues

#1715 sidesteps part of this this by removing the core of the base need, besides the argument access need.

### Describe the solution you'd like

Add a fallback string to the locale driver, where if the translation assets don't exist or the base translation doesn't contain the translation key, that fallback is used and executed as a translation string.

### Describe alternatives you've considered

Wait for #1715 and until then have basic formatting only
This is the current plan, I'm making this issue because I feel it is right to request the fix from translators using the localization tool, and it's my due diligence.

Implement the same localization formatting logic in LogiX! - no.

### Additional context

There's an added issue that complicates this issue, as I can't access the field key value pairs for the string. However it would have made the original pivot of the mentor signal less painful, and should help with what I get a feeling Git will encounter if translating some of neos essentials.

Also, now that I've realized that formatting thing I'm not sure I can translate the mentor signal properly, and the same goes for neos essentials. Any formatting strings can't have proper argument support (Although not many things do).

Depending on the strength of the string solver, this may introduce another Turing complete language for more code golf.

**Comment by Frooxius** [comment]
I'm sorry, but this isn't something we'd add to the design of the system.

As a rule we avoid adding these types of "holdover" changes, because once we do, there can be a significant amount of content built on them that we would either have to break at later point or get stuck supporting an anti-pattern that will make implementation of the more robust system much harder on our end.

The full version of the native localization system will allow for dynamic locale resources that can be edited dynamically in the world and the merged with the static ones, which will provide a proper mechanism to handle this.

I could investigate implementing that first, but it will require us to prioritize a portion of the locale system to ensure it'll work with the design of the system.
