### ISSUE TITLE
SnapperWhitelist causing to always snap

### ISSUE THREAD

**Issue by jeanahelver** [Neos-Metaverse/NeosPublic#2964]
### Describe the bug?

SnapperWhitelist causing to always snap the Snapper, no matter the distance of the SnapTarget

### Relevant issues

no

### To Reproduce

Create Slot with SnapTarget.
Create Grabbable object with Snapper.
Add Snapper Slot to the SnapTarget's SnapperWhitelist.
Add SnapTarget Slot to the Snapper's SnapperWhitelist.

grab the snapper object and move far away, wen releasing it will snap to the SnapTarget

### Expected behavior

Snapper only snapping if withing the range of the SnapTarget.

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.9.8.946

### What Platforms does this occur on?

Windows

### Did this work before?

Yes

### If it worked before, on which build?

2021.9.6.614

### Reporters

@TheBasementNerd
@jeana

**Comment by shiftyscales** [comment]
Can you please produce a reproduction world for this issue?

**Comment by TheBasementNerd** [comment]
To embellish a little, this bug seems to follow the update of snappers being set up to snap to the nearest snaptarget when snappers overlap, it seems like the SnapperWhitelist where snap components are directly dropped into doesn't respect distance of the SnapTarget and will always snap to the nearest one. The usual and expected behavior occurs when using keyword whitelisting, but the component reference whitelisting does not respect distance and will snap to the closest target in its list from any distance

**Comment by jeanahelver** [comment]
neosrec:///U-jeana/R-a305da5f-3945-4b3d-8047-999afadc7610

**Comment by Frooxius** [comment]
Should be fixed in 2021.9.8.1275! Thanks for report and sorry for the trouble!
