### ISSUE TITLE
Slot to CharacterController cast automatically created but does not work

### ISSUE THREAD

**Issue by XDelta** [Neos-Metaverse/NeosPublic#2989]
### Describe the bug?

Connecting a Slot to a Character Linear Velocity node will automatically create a Slot to CharacterController cast and connect them. As far as I am aware, this cast will always return null.

### Relevant issues

None found

### To Reproduce

Check description.

### Expected behavior

This cast should either effectively act like the Find Character Controller node or otherwise not automatically be connected.

### Screenshots

![image](https://user-images.githubusercontent.com/7883807/132937773-0241019f-84df-4d78-ad44-7ca7866e3869.png)

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.9.9.1144

### What Platforms does this occur on?

Windows, Linux

### Did this work before?

No

### Reporters

Delta#0942

**Comment by Frooxius** [comment]
This is technically correct behavior. Casts between class types will result in null if the input type cannot be cast into the target one. In this case you're trying to interpret Slot as CharacterController, but since it's not that type it cannot be cast to it. You need to use actual search function for it to find a different object of that type.

It's a bit tricky issue that came before (though I can't find the issues right now). We want to eliminate cases like this where the cast is known to be invalid so it doesn't generate confusing casts, but we also need to make sure that potentially valid casts aren't eliminated by this, since in some cases the cast might actually produce result. 

I'll see if I can at least eliminate cases like this for now in the next build.

**Comment by Frooxius** [comment]
I've added some filtering in 2021.9.11.1001 which should now prevent creating confusing casts like this. Thanks for report!
