### ISSUE TITLE
Add decimal support to Logix>Math>POW

### ISSUE THREAD

**Issue by Arkie001** [Neos-Metaverse/NeosPublic#3018]
### Is your feature request related to a problem? Please describe.

When trying high precision computations using the power node, precision is lost with floats and doubles.

### Describe the solution you'd like

I would like decimal to be supported for this node.

### Describe alternatives you've considered

An alternative could be to use a For loop with the desired power being a function of iterations and multiply by the previous result.

**Comment by Frooxius** [comment]
I'm sorry, but this isn't something we can really add. The decimal datatype isn't designed for mathematical operations like this, it's main purpose is for financial calculations as it represents the fractional in base 10 instead of 2, making sure that decimal fractions can be expressed exactly. As such it doesn't have those mathematical functions implemented.

I wouldn't recommend using it for any math like this. You can learn more about it here: https://docs.microsoft.com/en-us/dotnet/api/system.decimal?view=net-5.0

There's more info on this specific topic here as well: https://stackoverflow.com/questions/6425501/is-there-a-math-api-for-powdecimal-decimal
