### ISSUE TITLE
Non-uniformly scaled anchors cause users to dismount at a massive size

### ISSUE THREAD

**Issue by IanCorvid** [Neos-Metaverse/NeosPublic#3021]
### Describe the bug?

When a player anchors on to a User Anchor that is on a non-uniformly scaled slot, or is the child of such a slot, and then un-anchors their restore scale will be vastly ramped seemingly based on the differences in value between the X, Y and Z inputs for Scale. It does not matter which coordinate is non-uniform. 
Examples with a user at default scale 1:
An anchor at scale (1, 1, 1) or (0.1, 0.1. 0.1) will restore an anchored user to their appropriate scale of 1.
An anchor at scale (1, 0.1, 1) restores the anchored user at scale 2.8
An anchor at scale (1, 1, 0.01) restores the anchored user at scale 22.7

Addendum: I've noticed that, while in a non-uniformly scaled anchor, the _OriginalScale field on AvatarAnchor shows incorrect numbers and may be responsible for the jumps in user scale.

### Relevant issues

None

### To Reproduce

-Create a UserAnchor on an object or use the last item (Grebber 3.0) in this folder: neosrec:///U-I-an-Corvid/R-85bbdab6-6811-4e23-8eb0-2a5cfcf48e49

-Non-uniformly scale the green pill on any dimension by any amount.

-Sit on the anchor and jump off. Taking note of your size before and after.

-Experiment with larger number differences, notice how larger differences result in far larger changes to user scale on restore.

### Expected behavior

Player's restore scale should remain constant, A user at scale 1 should be returned at scale 1 when dismounting from an anchor.

This issue can be resolved by using uniform scale, however in some projects that specifically require non-uniform scaling to work, this becomes a problem requiring many extra steps to compensate for, such as forceful re-scaling of the user upon exit. 

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.9.16.105

### What Platforms does this occur on?

Windows

### Link to Reproduction Item/World

neosrec:///U-I-an-Corvid/R-85bbdab6-6811-4e23-8eb0-2a5cfcf48e49

### Did this work before?

I Don't Know

**Comment by shiftyscales** [comment]
I'd highly suggest against using non-uniformly scaling when possible. The user root has built in protections against non-uniform scaling and will try to correct its scale/become uniform again.

To my understanding this is related to creating a 'flattening' effect for the avatar- to this end, for this approach you would likely either need to change your approach. E.g. using a camera that selectively renders the user, or change your order of operations for anchoring/unanchoring the user to ensure the anchor is uniformly scaled when they enter the anchor and exit it.

Alternatively you can set a `RestoreReference` slot that has uniform scaling and set the `TransformRestoreMode` to `Reference`. But you will still need to ensure the anchor is uniformly scaled when the user enters it.

![image](https://user-images.githubusercontent.com/54213390/133806525-b96dbaee-a11b-481e-9f9a-df0fac3d6966.png)

**Comment by Frooxius** [comment]
Unfortunately this isn't something that we can fix, non-uniform scaling combined with rotations will break the transformation math.

To put a simple analogy, when you apply non-uniform scale and rotations, the transformations become lossy - essentially the rotation and scale become "mixed together" and can't be separated out anymore (like when you add 3+4+2 together and get 9 as a result. If then some things change and you know one of the numbers is now 5, you have no way of knowing what other two numbers are - they just sum up to 4).

Generally we strongly advise against using non-uniform scaling for anything other than meshes at the bottom of hierarchy. A lot of things will misbehave, because the math goes haywire with them and an issue pops in one place or another.

I'd recommend using alternative approaches that @shiftyscales provided above, which can behave better in this case.
