### ISSUE TITLE
bhaptics not working on player join

### ISSUE THREAD

**Issue by micmac253** [Neos-Metaverse/NeosPublic#3034]
### Describe the bug?

Whenever a player joins a session, my haptics do not work when they collide with them. only when the player reloads their avatar will it function. item with haptic volumes work perfectly without issue. leaving and rejoining the session does not fix the issue either.

### Relevant issues

none that I can think of.

### To Reproduce

have someone with a haptic vest, have a player join in on your session that you are in, test haptics and they should not be working. then have the player reload their avatar and test again, it should be working now.

### Expected behavior

I expect haptics to work when a player joins instead of having to tell every new player to reload their avatar.

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.9.16.105

### What Platforms does this occur on?

Windows

### Did this work before?

No

**Comment by shiftyscales** [comment]
When testing this with infotron# 0243 (the poster of this issue) last night, I had enabled debug visuals on her haptic vest, and noticed that while the bug was in effect (after I joined the session, and prior to re-equipping my avatar), the haptic vest debug visuals remained gray, suggesting no collision events were registered.

As mentioned, if I (the user triggering the haptics, not the one wearing the vest) re-equip my avatar, it will work properly, and the haptic vest will be triggered by my touch as expected. After leaving and re-joining the session, the same bug occured until switching avatars again.

Infotron also has found this happens both for sessions she's hosting as well as sessions she's just joined.

**Comment by shiftyscales** [comment]
I also believe this issue is likely a regression occuring from the bepuv2 upgrade.

**Comment by micmac253** [comment]
I have also discovered that if someone joins a world before me, the haptics seem to work fine. at least in the couple of times I tried testing it.

**Comment by Frooxius** [comment]
@micmac253 What's the exact flow in that case? If the person joins the world before you, do haptics work for them (meaning they are wearing the vest) or do they work for you (you're wearing the vest and they trigger it)?

**Comment by micmac253** [comment]
> @micmac253 What's the exact flow in that case? If the person joins the world before you, do haptics work for them (meaning they are wearing the vest) or do they work for you (you're wearing the vest and they trigger it)?

oh sorry, I mean the haptics work for me, as in they can trigger my vest.

**Comment by Frooxius** [comment]
Fixed in 2021.9.20.1334! Thanks for report!
