### ISSUE TITLE
Component to modify colors

### ISSUE THREAD

**Issue by TheBasementNerd** [Neos-Metaverse/NeosPublic#3077]
### Is your feature request related to a problem? Please describe.

When setting up a color that is designed to be based off another color (such as its invert, or a transparent of it) it can be a hassle to use Logix as multiple math nodes and sometimes boolean decisions are needed to create a working system for modifying a color into another one where needed, and with the number of places that users like to have active colors on systems, easy modification would greatly assist in the design aspect and optimization of multicolored systems

### Describe the solution you'd like

A component that can take in a color value and has fields to multiply, add to, or subtract from the color values and the alpha, with check boxes that can do slightly more complicated operations such as inverting the color, and either drives a color field or has a color field to be read from as the output

### Describe alternatives you've considered

I don't believe there is a singular alternative with Logix that would be able to reproduce a wide enough range of effects for users, as well as if the user is modifying multiple colors off one you'd have to have the modification system cloned for every color output desired

**Comment by shadowpanther** [comment]
Clever usage of /Transform/Drivers/[LinearColorMapper](https://wiki.neos.com/LinearColorMapper_(Component)) and /Transform/Drivers/[ValueGradientDriver<color>](https://wiki.neos.com/ValueGradientDriver%601_(Component)) can do addition(subtraction) and multiplication(division). Anything more complex is better done with LogiX.

**Comment by Frooxius** [comment]
I'm not sure this is something we'd add. Generally we don't codify specific LogiX setups as Components, unless they're very general or very common, otherwise it becomes hard to scale, as there's thousands if not more possible setups you could have with LogiX and we can't add component for each.

We could potentially add more common color operations to LogiX though to simplify the setups though. What operations do you commonly do?

**Comment by TheBasementNerd** [comment]
The most common is that I want to have the colors in my color system either be offset by a small amount to make the colors look better on different objects while matching the scheme, apply a transparency to the color that I'm using so I can place it on specific materials, or I'll want to invert a color so that it creates a nice contrast with the main color for easy visibility. I've also recently been doing things with having the emission map of something increase in response to an input, and with a dynamic color system like mine managing the colors across the system to be specially applicable to each situation I might apply them becomes a difficult task

I figured that this would be a considerably general use component, that could have applications for visual and entertainment tools, such as creating dynamically high contrast systems or color walls (I had seen a user with a wall of blocks that all changed colors together but as different colors and they had to have a complicated setup for each row to make it work)

**Comment by Frooxius** [comment]
What you describe is job much better suited for LogiX, since that has the expressiveness to have a lot of custom setups. What you describe is a number of completely unrelated operations that help in your usecase, but other users might want lots of others and packing all possible setups into a single component (or even lots of them) just doesn't scale.

We can add a number of LogiX nodes to perform some of these common operations - overriding channels, blending/inverting colors, measuring contrast and so on. From those building blocks you can construct the behavior you need.

**Comment by TheBasementNerd** [comment]
That makes sense. To me I felt that as it was color modifications, having a single approach to those modifications made sense for ease of use and access and improving the speed at which people may set up color systems that work in tandem, however the nodes as well would be an appreciated and helpful tool to make the color adjustments easier

**Comment by Frooxius** [comment]
I've added a whole bunch of nodes in 2021.9.27.743, hope they help a bunch!

- Added new LogiX nodes for color blending (based on request by @TheBasementNerd#3465, GH #3077)
-- Additive Blend, Multiplicative Blend and Soft Additive Blend
-- Alpha Blend has better handling for out of range values
-- All blend nodes are now in "Blending" subfolder in Color
- Added Luminance node for Colors (based on implementation by @Geenz#0228)
- Added Invert LogiX node for Colors (GH #3077)
- Added LogiX nodes for quickly overriding/multiplying color channels (both in RGB and HSV spaces) under Color/Channels (based on GH #3077)
-- Set R, G, B, A, Hue, Saturation and Value
-- Multiply R, G, B, RGB, A, Hue, Saturation and Value
