### ISSUE TITLE
Colliders generated after textures since switching to BEPU v2?

### ISSUE THREAD

**Issue by SHFRH** [Neos-Metaverse/NeosPublic#3078]
### Is your tweak request related to a problem? Please describe.

When I am selecting a model of say a kettle, I am used to opening a dozen glTFs from Sketchfab and quickly deleting the ones I don’t like and arranging or editing the others even before the textures load. Recently (since switching to BEPU v2?) this seems to have changed such that I can’t grab or select any of them (colliders) until the textures (variants?) load many minutes later.

### Describe what would you like tweaked

Unless I am missing something (as usual) I think it is better for colliders to be generated before textures if that's still possible?

### Describe alternatives you've considered

I find myself going off to make a cup of coffee or do something else while I wait :)

### Additional context

Enverex 01/09/2021
"I've noticed this. It's especially noticeable when importing things when you're not the host. The collider appears to load after the textures, so it takes a very long time in some cases."

**Comment by Frooxius** [comment]
There has been a change where there's only 1 thing generated at the time due to too many jobs resulting in some users having significant stutters.

However since the major stutters were caused by a different part, I think I can allow multiple parallel jobs again, especially separate ones for textures and colliders which should resolve this issue.

**Comment by Frooxius** [comment]
I split up the generation again in 2021.9.27.743 and added a bit more parallelization if you got plenty of cores, should run better now! Thanks for report!
