### ISSUE TITLE
Negative scale getting lost when reparenting slot

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#3081]
### Describe the bug?

When reparenting a slot that has a negative scale on any of its axes, those axes get rescaled to their absolute value.

### Relevant issues

Could not find any.

### To Reproduce

1. Make a slot.
2. Inspect the slot
3. Set its scale (on any axis) to -x
4. reparent it to any other slot that is the same size as its parent. (for simplicity)
5. Watch its scale go to positive x.

### Expected behavior

Negative scale should be preserved by reparenting.

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

9.22.1431

### What Platforms does this occur on?

Windows

### Did this work before?

I Don't Know

### Reporters

Psychpsyo#7818
Ukilop#4463
Earslya#7831
Irick#0001

**Comment by Frooxius** [comment]
This is a tricky issue. Generally non-uniform and negative scales are strongly discouraged against, because they tend to require a lot of special handling, which can take up extra performance and cause issues in different parts of the system.

Neos used to preserve the negative scale before when parenting, but this had consequence of broken transforms in different places, so it got changed.

We can look into improving this behavior by tweaking the math again, but it's probably something we need to do carefully to avoid regressions.
