### ISSUE TITLE
Component Cloning assets should make them persistent

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Neos-Metaverse/NeosPublic#3085]
### Is your tweak request related to a problem? Please describe.

It's extremely annoying working on something and cloning assets (textures, materials ect) only to have them be non-persist and then saving and not realizing that the assets don't exist only needing to do it all over again.

### Describe what would you like tweaked

The component clone tip should make assets persistent when cloning. As when you're cloning assets, atleast for me, I want them persistent, otherwise I wouldn't clone them in the first place.

### Describe alternatives you've considered

-

**Comment by Frooxius** [comment]
Why are they non-persistent in the first place?

The cloning process is just that - exact cloning. It doesn't perform any modifications to the cloned data and it's even unaware of what they are.

We can't have it modify fields like that arbitrarily just because it's convenient for particular use-case, because this would break anything that performs cloning that requires the state to stay the same.

I'd probably recommend just making them persistent if you want them persistent, the system has no way of knowing whether persistent or non-persistent is the right choice. Explaining your use case in more detail might help.

**Comment by mralext20** [comment]
I think this may be for the action of coping a material onto an object for driving / interacting with via logix / field reference. 

This happened to me I the past, and I solved it on the discord here:  https://discord.com/channels/402159838827905024/439421735474036738/760719267258957825

**Comment by 3x1t-5tyl3** [comment]
I think it's due to them living in the assets which are non-persistent.
Like this random material. (see bottom)

As such when component cloning, the asset stays non-persist and when you want to drive it with components or logix it'll obviously need to be persistent otherwise it's gonna get deleted. And even if I know about it I still forget.. (I mean by now I'm at 4200 hours in neos and I still forget..)

That being said, it's clear there's no ways to make this work either way so I'll close this issue now.

![grafik](https://user-images.githubusercontent.com/61988002/134806114-2ea507a6-7303-427f-8cce-6dd3903b67cb.png)
