### ISSUE TITLE
Ability to mark a slot as not providing parent values, and have it look to the grandparent instead

### ISSUE THREAD

**Issue by Earthmark** [Neos-Metaverse/NeosPublic#3107]
### Is your feature request related to a problem? Please describe.

I have a particular use case where I want a slot with bindable fields, and then a binder object that contains receivers for those fields. It ends up looking like this:
```
BindableSlot - with provided parent values
  BucketOfRecievers - thing that needs some magic
    Reciever 1 - actual destination of value
    Reciever 2
    ...
  BindableChildSlot1
    AnotherBucketOfRecievers
      ...
```
This ends up being quite clean to look at in the hierarchy, however it's quite messy to implement at the moment due to the wrapper bucket slot.

That bucket really helps readability, as it allows me to have all of the recievers together, and to mark them as non persistent or delete them easily.

### Relevant issues

None found

### Describe the solution you'd like

A component, that when placed on a slot, parent references and values skip that slot while searching for a match.

In my example the bucket would have this component. The bindable slot would provide values, and the recievers would consume that value.

### Describe alternatives you've considered

Dynamic variables - this is non optimal as I've got up to possibly hundreds or thousands of bindable slots. I feel that would get quite messy dynamic variable space wise, but it's possible.

Recievers being direct children - this is not as liked but is doable, recievers may need to be deleted or set persisted as a group, so that gets possibly quite messy.

### Additional context

Dunno if it would be valid to chain these parent value ignores.

Having ignores may be good for making apis, as you could have wrappers that are marked as ignore and the internals could recieve the values directly.

I'm still designing this system, so this kind of a skip may not end up getting used directly, however it may still be useful to have a utility like this.

**Comment by ProbablePrime** [comment]
> A component, that when placed on a slot, parent references and values skip that slot while searching for a match.

That's incompatible with the current parent data link systems. They're explicitly meant to be used with a single child<->parent link.

Beyond that you're looking for dynamic variables.

Adding this to the parent linking systems would just undermine and confuse the purposes of each system.

**Comment by Frooxius** [comment]
Yeah, like @ProbablePrime said this would unfortunately complicate the systems.

You can't just "mark" the slots to look for grandparents, because the system needs to track when the parents or children change. With a direct parent-child relationship this is quite simple, but once there can be objects in between them, it complicates the system quite a bit.

We'd have to redesign the system to handle tracking hierarchy changes for this, but that's already what dynamic variable spaces do, so we'd just be re-implementing that system.

Parent data link has been designed for simplicity. If you need more complicated behaviors, please utilize the dynamic variable spaces.
