### ISSUE TITLE
Queue Impulse LogiX Node

### ISSUE THREAD

**Issue by ImErinNeos** [Neos-Metaverse/NeosPublic#3109]
### Is your feature request related to a problem? Please describe.

No.

### Describe the solution you'd like

I would like a LogiX node that will queue up impulses and release them at a steady rate. The node would have an impulse input and a float input and an impulse output. An example use for this node would be connecting it to a For node that will output 10 impulses into the Queue Impulses node and if you have a 1 in the float input, it would output all 10 received impulses each one second apart from the other.

I know this probably needs collections, I just want it officially suggested.

### Describe alternatives you've considered

You could do it through complex logiX with delays.

**Comment by Frooxius** [comment]
This one doesn't actually need collections, since they'll only be used internally and not exposed to LogiX itself. We could take this as form of leaky bucket implementation with adjustable capacity (could be infinite, but also restricted, so if impulses are coming too fast, it'll pass them through faster if you want or alternatively drop them).

**Comment by Electronus** [comment]
For now you can use a set up like these first is a number of pulses on a time interval. 

The second fires one per update(frame). 
![image](https://user-images.githubusercontent.com/64871170/135366566-e6fc745e-f009-47c6-9d55-967a85a03f59.png)

**Comment by Frooxius** [comment]
Added in 2021.10.3.784! Hope it serves well!

https://www.youtube.com/watch?v=cYxj9Lqajmk
