### ISSUE TITLE
Node to detect if a user falls out of the map

### ISSUE THREAD

**Issue by epicEaston197** [Neos-Metaverse/NeosPublic#3143]
### Is your feature request related to a problem? Please describe.

I would like to have a Node that would detective a user falls out of the map bounds because some reparenting systems detective based off of distance and if the user falls out of the map then they go back to spawn but they're still parented to to something which means they are locally disabled for themselves and they have to respawn themselves in order not to be broken so a way to detect this so that I can reparent the user would be nice

### Relevant issues

none but I can think of

### Describe the solution you'd like

I would like there to be an Node to detect if a user is out of bounds 
![image](https://user-images.githubusercontent.com/76523692/136108348-cdab7648-7361-401e-9ff6-3fcd60e4db27.png)

### Describe alternatives you've considered
not making a new node but modifying the "user spawn" Behavior to include this Behavior

![image](https://user-images.githubusercontent.com/76523692/136108387-1f4e8862-b628-47f9-afb9-554c62a3c212.png)

### Additional context
if I could have this but user fall then I'll be able to reparent users to Root to prevent them being disabled for themselves
![image](https://user-images.githubusercontent.com/76523692/136118193-65574fb7-f941-4d8a-a380-7c41cc252bb6.png)
this has been a problem on my map for a good while and it haven't had a good solution to fix it yet

so what happens is when I go into the room I get parented into a folder in the room 
based off of distance it will deactivate the room when a user Falls and responds they are still in the folder
so they will be deactivated for themselves

https://user-images.githubusercontent.com/76523692/136109477-d8cc470b-12f6-454e-ba7e-79a2363bf380.mp4

**Comment by Frooxius** [comment]
This isn't something we'd add. The FallRespawnPosition is just a simple countermeasure to prevent the user falling endlessly if you don't setup anything for this yourself, it's not made to provide any complex behaviors.

If you want to control what happens when they fall out of the map, set the FallRespawnPosition to infinity and either use custom LogiX or put a large collider that fires an event that lets you respawn the user and run any other extra actions you wish to do.
