### ISSUE TITLE
MTC - New users are locked out of the dashboard until the panel after the dashboard

### ISSUE THREAD

**Issue by Earthmark** [Neos-Metaverse/NeosPublic#3145]
### Describe the bug?

With new users, when they are placed in the MTC world they are not able to open their dashboard yet (this maybe should change now that it's easier to close... anyways). The new users dashboard is only active the page after the dashboard is described. This is confusing to new users, as the dashboard appears to be broken.

### Relevant issues

None found

### To Reproduce

Be a new user, go to the dashboard page of the MTC, try to press escape.

### Expected behavior

The dashboard is openable when it is mentioned.

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

No

### Neos Version Number

2021.10.5.1054

### What Platforms does this occur on?

Windows

### Did this work before?

I Don't Know

### Additional context

I'm currently about to sleep, but verification is needed. This was reported by a new user and I've yet to verify. If I don't make this issue now I'll forget to later!

**Comment by Frooxius** [comment]
This is intentional part of the startup tutorial. It's been like this since the beginning. We found that if they can open the dash anytime, they easily escape the tutorial, skip important steps, get overwhelmed and leave, so it's better to require them to step through the tutorial without distractions.

We can see if we can communicate this better, but I'm a bit puzzled why it would be confusing. A new user shouldn't have any notion of what's normal and what's not, this is just a portion of the tutorial sequence.
