### ISSUE TITLE
Steam Launch Options should be simplified.

### ISSUE THREAD

**Issue by TehTurk** [Neos-Metaverse/NeosPublic#3210]
### Is your tweak request related to a problem? Please describe.

![image](https://i.imgur.com/5LuHxz1.png)

This originally came from Euphi, because they had trouble having a simple way to just launch Neos in Desktop Only. Yes, there are CML Arguments, but there could be improvements made here to make it easier on end-users.

![image](https://i.imgur.com/a0Fzr3g.png)
Currently, our current launch options show as this, having them be more distinctive would be more ideal.

### Describe what would you like tweaked

Honestly, one that launches VR (Automatically), one that launches Desktop, and one that launches the NeosLauncher or Neosine in the future to make it more simplified if people need to do custom setups.

### Describe alternatives you've considered

Launch Options are a thing, but not ideal for the end-user.

**Comment by Frooxius** [comment]
I don't think this will make it simpler, since it'll add number of steps you need to do if you want a custom launch option - those options are already custom, so I don't think having one more is such a problem.

We added those options specifically because people had trouble with those going through the Neos Launcher every time, so we added a quick Steam launch option to simplify it

**Comment by shiftyscales** [comment]
@TehTurk I feel like your request would be best resolved by a mechanism to auto-switch to desktop e.g. if the user isn't in-headset. This still allows users to switch between VR and desktop, and they can still use the launcher, and/or launch options if they really want to force desktop only.

**Comment by ProbablePrime** [comment]
@shiftyscales that would still start the SteamVR / VR runtime which in some cases is not Ideal. I think this is one of the things users may be trying to avoid by not using the "Hybrid" modes we have available.

**Comment by shiftyscales** [comment]
Well the basic 'play' option would still be auto-detect, yeah? Plus if they're all listed there as options it greatly reduces the friction to have the user try one of the other options, e.g. forcing Oculus.

I know I've seen the reverse too where users trying to use FBT with Oculus find their trackers aren't working because Neos launched in the Oculus runtime instead.

**Comment by shiftyscales** [comment]
"Launch Neos Launcher" perhaps? That option would also be suitable when we add Neosine which will be more than just a configuration tool. Or if possible, just "Launcher".

I think the list is looking pretty solid otherwise though.

**Comment by shiftyscales** [comment]
Then yeah, `Launch Neos Launcher` is suitable I think. Since you said tthe desktop is overriden aready maybe `Launch Neos in Desktop (Non-VR) Mode` instead? It's more consistent with the rest.

( ) Play Neos VR
( ) Launch Neos VR in Steam VR Mode
( ) Launch Neos in Desktop (Non-VR) Mode
( ) Launch Neos VR in Oculus VR Mode
( ) Launch Neos Launcher

**Comment by Frooxius** [comment]
@shiftyscales I can't change that one unfortunately, the custom templates always start with "Play". The specialized launch methods (e.g. VR or Configuration Tool) always start with "Launch".

**Comment by Frooxius** [comment]
Ok it should be changed now, it's Launch Neos Launcher.

**Comment by TehTurk** [comment]
Thanks Froox, Shifty, Prime, Hidi :) I'm fine to close this if need be, will close within the day unless anyone else has other tweaks but I think this is good for now.
