### ISSUE TITLE
Very long messages get very tall.

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#3213]
### Is your tweak request related to a problem? Please describe.

I'm always frustrated when I send a message to someone that has a very long continuous string of characters in it.
In those cases, the message becomes very tiny but the box around it stays as tall as it would need to be, had new lines been inserted. (I assume)
This is what it looks like: (had to set a really long default for a string cloud var)
![grafik](https://user-images.githubusercontent.com/60073468/137709120-6d5afd11-5408-4796-b409-da331234de81.png)

### Describe what would you like tweaked

Insert newlines into the visual representation of messages that are too long. (Not into the actual message, that would mess with bot commands like what I did above.)

### Describe alternatives you've considered

1. Keeping it this way. (Seems very suboptimal)
2. Scaling down the message box to fit the actual message. (Message stays illegible)
3. Forcing new lines into the message content (Makes certain bot commands impossible)
4. Adding a character limit to DMs. (see 3, also is just generally annoying)

**Comment by Frooxius** [comment]
I'm sorry, but we do not plan on any more incremental updates to the old Contacts UI. Unfortunately the old one was implemented when we had much more limited UI framework so it has a lot of undesirable behaviors like this, but changing it can be quite painful and laborious.

The new one will be designed to utilize the new features of the UI framework to properly size all the messages with a fixed font size, rather than resizing the text to fit the available area: https://github.com/Neos-Metaverse/NeosPublic/projects/2#card-61033401
