### ISSUE TITLE
KFC CDFT Test Run deposits don't respect /kfcOptOut status.

### ISSUE THREAD

**Issue by shiftyscales** [Neos-Metaverse/NeosPublic#3316]
### Describe the bug?

During the recent couple of CDFT mints, and test mints, I have received KFC despite being opted out- possibly as this is a direct depoit from the system?

I'm not currently opted out of CDFT/NCR, but am wondering if the same issue would be present for those as well if using the /ncrOptOut command?

### Relevant issues

N/A

### To Reproduce

Receive a CDFT test mint.

### Expected behavior

I would like to maintain my exact KFC total/not receive KFC from CDFT test mints.

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2021.11.5.486

### What Platforms does this occur on?

Windows

### Did this work before?

No

### Additional context

This issue is low priority, and the issue is mitigated by giving the KFC away.

### Reporters

Shifty

**Comment by Frooxius** [comment]
This is intentional, KFC is used for a test run to make sure that the whole system works properly before we do a proper run with NCR. 

We **really** don't want this process to go wrong since it deals with money, so the KFC opt out isn't going to be respected for this. Given that CDFT distribution is relatively infrequent event it's not worth complicating the code and potentially missing some errors or problems before the proper run.
