### ISSUE TITLE
Option to make it so the head on your avatar stays to your real head in full body tracking.

### ISSUE THREAD

**Issue by ModernBalloonie** [Neos-Metaverse/NeosPublic#3394]
### Is your feature request related to a problem? Please describe.

When the hips are pulled downwards a little too far, the head stops staying in it's location and gets pulled downwards. This sometimes really sucks when i need to make sure my neck is straight, especially when the avatar has a strange body shape.

### Relevant issues

Maybe https://github.com/Neos-Metaverse/NeosPublic/issues/1120 ?

### Describe the solution you'd like

I would like a way to keep my avatar head "glued" to my real head and have it so I can stretch the hips down slightly (if that makes sense) so my neck continues to be straight. Perhaps this could be an option in the full body calibrator?

### Describe alternatives you've considered

I've tried to parent the head proxy to the head but that wasn't a good idea (avatar freaked out)

**Comment by alexderpyfox** [comment]
Yes this has to do with the way the ik and fullbody tracking works i also put a GitHub issue of this issue in basically the solution would be to make the hip move independently from the head with fullbody tracking i made a video on it with a logic hip fix that when set up correctly should make the head stay in place whilst moving the hip target up and down to compensate the spine scrunching/stretching https://youtu.be/ELCwI38PaA4

**Comment by alexderpyfox** [comment]
So when not using fullbody the head is the leading tracking point making the rest of the ik follow but when using a hip tracker that suddenly becomes the leading tracker making everything follow the hip and with how the ik works when you look up and down the ik moves up and down when not wearing a tracker but when putting on a hip tracker the ik can no longer move up and downy hip fix fixes that and makes it so that the ik can move up and down despite wearing a hip tracker so the head will always stay in place when the 2 numbers are set up correctly

**Comment by shiftyscales** [comment]
This already exists @ModernBalloonie. It is a property called HeadMaxFixDistance and is on the VRIKAvatar component at the root of the avatar. If you and others are running into your head being pulled down, I suggest you increase that value.

**Comment by kulzae** [comment]
I wouldn't consider this a fix and i don't think changing that setting results in the behavior modern is referring to. After playing around with it it causes the neck to stretch so the head stays in place while the hips still follow the tracker. What modern (and nearly everyone else with this issue) is referring to is adjusting the weighting of the head and hips so the head is higher priority. meaning when you move your hip tracker further than what your body would allow the head takes priority without stretching

**Comment by ModernBalloonie** [comment]
> I wouldn't consider this a fix and i don't think changing that setting results in the behavior modern is referring to. After playing around with it it causes the neck to stretch so the head stays in place while the hips still follow the tracker. What modern (and nearly everyone else with this issue) is referring to is adjusting the weighting of the head and hips so the head is higher priority. meaning when you move your hip tracker further than what your body would allow the head takes priority without stretching

This. This would be great.

**Comment by shiftyscales** [comment]
@kulzae @ModernBalloonie - well if either of you would like to edit the OP to reflect that- but I'm pretty sure Alex already made such an issue with #3011 or #2916 in which case- this issue would be a duplicate.

I also don't know how good of an option that is- it's fundamentally just trading one problem for another if it even could be implemented. If the issues that result in neck scrunching could be resolved, then users could have a properly calibrated avatar and no stretched neck because they won't have to either pull the hips way down, or lower the height compensation below where it should be.

**Comment by alexderpyfox** [comment]
> 

Yep that's what my logix hip fix does it dynamically adjusts the hip Instead of being 1 static fix it needs to constantly adjust itself so that's what my logix hip fix does

**Comment by ModernBalloonie** [comment]
> 

I think some of the neck scrunching has to do with height and such because i notice when i go in and out of the full body calibrator the neck bends horribly on the robot, but that also affects the avatar. Basically if you go in and out of the full body calibrator without calibrating the whole robot gets bigger for some reason. I mentioned it here too at #3042 . 

Also about the trading one problem for another thing: It should still be an option for those who want to try it. I see it fixing some issues and there's no real reason why it shouldn't be added as an option. I see it fixing some issues for some avatars, not all avatars but some avatars might need something like this especially if they are non-humanoid shaped.

**Comment by shiftyscales** [comment]
The behavior you describe is what already happens when there isn't a hip tracker present, e.g. the user is not in FBT at all. That said- I still think it's better to allocate developmental resources to fixing the underlying issues rather than creating mitigations.

I believe it'd require a fairly substantial amount of work to make such an option as you are describing.

**Comment by ModernBalloonie** [comment]
> The behavior you describe is what already happens when there isn't a hip tracker present, e.g. the user is not in FBT at all. That said- I still think it's better to allocate developmental resources to fixing the underlying issues rather than creating mitigations.
> 
> I believe it'd require a fairly substantial amount of work to make such an option as you are describing.

Please make this an option, because I've recently played around with the IK beta in VRchat and it has an option to lock your head, or hip, or both your head and hip.

I know I am referencing VRchat here but that option in that game is incredibly useful. Having the head lock to your head and having the hip sort of "move" up and down depending on your head position is great for non humanoid shaped avatars, or avatars that are slightly too long or short.

I feel like this would really help, as again it would allow you to drag your hip way down so your chest doesn't bend strangely when looking up, the hip would move instead.

I know it would effectively trade one problem for another but VRchat has these options, it would be great if Neos had them as well.
