### ISSUE TITLE
Can't interact with userspace menus without opening dash in desktop mode. (Softlock during tutorial possible)

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#3424]
### Describe the bug?

When a local space menu is open in desktop mode, it blocks the middle of your screen but you can't interact with it until you open your dash.

### Relevant issues

Didn't find any.

### To Reproduce

1. Go to the Metaverse Training Center world.
2. Click the discord link.
3. You are now softlocked since you can't open your dash and the discord link window blocks your view/interactions.

### Expected behavior

The menu being there should make Neos behave as if the dash was open.

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

Beta 2021.11.10.1265

### What Platforms does this occur on?

Windows

### Link to Reproduction Item/World

http://cloudx.azurewebsites.net/open/world/G-Neos-Team/R-6eff26cf-dc1a-4519-91ea-0beb2e812f70

### Did this work before?

No

### Reporters

Cameron#7818
Dustin#7215

**Comment by epicEaston197** [comment]
this does not soft lock you open up your context menu doing this makes your mouse freeform and hit the cancel button
![image](https://user-images.githubusercontent.com/76523692/144671113-b1c800fa-656c-48e2-bb85-6a4e0a526e80.png)

**Comment by Bontebok** [comment]
I noticed there wasn't a screenshot of the original issue, so I reproduced it as shown below.

![Screenshot from 2021-12-10 18-43-19](https://user-images.githubusercontent.com/23562523/145654484-ccb1d5dc-6bfb-43bc-b31f-4521c846d06f.png)

The dialog is in user space, but unlike the Dash menu the laser/mouse cursor is not available since it is driving your head direction which causes your viewpoint to move making it impossible to click on Open or Cancel without taking additional steps.

As @epicEaston197 pointed out, you can press the middle mouse button to bring up the mouse cursor/laser so you can click on Open or Cancel, alternatively you can also press F6 to go into free form camera which will also allow you to click Open or Cancel.

This is mitigated for most users on the Desktop by pressing Escape to open the Dash Menu, however the Dash Menu isn't available until after part of the Tutorial is completed.
