### ISSUE TITLE
AvatarObjectScale doesn't work when joining other people's sessions

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#3485]
### Describe the bug?

When an avatar with an AvatarObjectScale component gets equipped to a user due to joining or respawning in someone else's session, the AvatarObjectScale won't have any effect.

### Relevant issues

Didn't find any.

### To Reproduce

1. Add an AvatarObjectScale component to an avatar with a rig. (not a head and hands)
2. Set the AvatarObjectScale's scale to something other than 1.
3. Save and favourite that avatar.
4. Join a session hosted by a different user.
5. You will equip the avatar but the AvatarObjectScale won't do anything.

### Expected behavior

The scale in the AvatarObjectScale should be applied to the avatar, as it is when equipping the avatar normally. (from inventory or by spawning it and equipping it)

### Log Files

[Uploading SYSTEM-PURPLE - 2021.11.10.1265 - 2021-12-25 06_30_21.log…]()

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

Beta 2021.11.10.1265

### What Platforms does this occur on?

Windows

### Did this work before?

I Don't Know

### Additional context

My guess is that this is related to the host spawning the avatar instead of the local user as this bug doesn't exist in my own sessions.

### Reporters

Cameron#7818

**Comment by epicEaston197** [comment]
this is really similar to The Avatar root override assigner component

**Comment by Psychpsyo** [comment]
In terms of the bug or in terms of what the component does?

**Comment by epicEaston197** [comment]
> Reference in new

basically do you know how my avatar can sit down? it actually overrides the Viewpoint to be where my head is and that is done with the Avatar root override assigner component 

but there was a bug where if the host loaded my avatar it wouldn't override my viewpoint and I had to manually equip my Avatar if I want it to work

this sounds very similar to your issue
this was fixed by having a equipment slot for the current user
so I bet a similar change can be done to the component in question
![image](https://user-images.githubusercontent.com/76523692/211010597-ee2227e4-d0a0-451f-9794-aaa393faa408.png)
