### ISSUE TITLE
Spectator ban causes avatar to not load when given Guest or higher

### ISSUE THREAD

**Issue by Sox-NeosVR** [Neos-Metaverse/NeosPublic#3592]
### Describe the bug?

Joining a session while spectator banned and provided with builder permissions, when respawned my favorited avatar does not load by default requiring me to manually equip the avatar every time i respawn.

### Relevant issues

N/A

### To Reproduce

- Be spectator banned
- Join another users session
- Be given guest permissions or higher
- Respawn

### Expected behavior

Avatar should load by default if the spectator banned user is given higher permissions.

### Log Files

[Sox - 2022.1.28.1335 - 2022-02-09 18_42_50.log](https://github.com/Neos-Metaverse/NeosPublic/files/8035413/KYLE-PC.-.2022.1.28.1335.-.2022-02-09.18_42_50.log)

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

2022.1.28.1335

### What Platforms does this occur on?

Windows

### Did this work before?

I Don't Know

### Reporters

Sox#0001

**Comment by shiftyscales** [comment]
This is by design. My suggestion is to avoid any actions leading to the first step in your replication steps.

**Comment by Sox-NeosVR** [comment]
although being spectator banned is a punishment, i made this bug report because this is unexpected behavior.
once the host has provided the spectator banned user with higher permissions, on respawn the favorited avatar should equip, but it doesnt.

**Comment by shiftyscales** [comment]
I understand your issue with it. As mentioned- it's by design. Sorry for the inconvenience.

**Comment by Sox-NeosVR** [comment]
![image](https://user-images.githubusercontent.com/66733654/153280117-c6196865-fbd5-4fd8-8501-082aebcc5468.png)
the wiki needs updating if that is the case because it says otherwise

**Comment by shiftyscales** [comment]
Thanks for noting so, @Sox-NeosVR. I've updted it to say the following:
> '''Spectator Ban''': Sets a user to Spectator when entering another user's world and does not allow the user to wear their favorited avatar unless manually equipped.

To clarify another point- the `LoadCloudAvatars` property of the `CommonAvatarBuilder` component has no ties to the permission system, and does not change regardless of what permission level a user has. It is either enabled, or disabled for everyone in the world.

The permission system separately has the AvatarObjectPermissions and WorldPermissions components which also control which avatars a user has access to equip, and if they're allowed to swap avatars.

So in effect, what a spectator ban is doing is enforcing a `LoadCloudAvatars` value of false for the spectator banned user, regardless of whether a given role otherwise has permission to spawn/equip avatars.

Spawning a favorited/cloud avatar is a separate behavior from equipping the avatar.

**Comment by sikirebirth** [comment]
So if I give admin to someone, my input matters less than a spectator ban I do not agree with?
