### ISSUE TITLE
[Feature Request] A way to access a images pixel-information (R, G, B, A)

### ISSUE THREAD

**Issue by BlaXun** [Neos-Metaverse/NeosPublic#365]
I would like to request a component or node that can output pixel-information on an imported image.

It could take 3 inputs: Image, x, y 
and it would output a float4, containing a value from either 0 to 1 or 0 to 255 each float. This would be the color information of the requested pixel.

**Comment by shiftyscales** [comment]
This functionality would also be very useful for allowing color-picking in the brushes, and other tools. E.g. if a user wishes to use reference images to get a specific color, or average out the color of a part of an image in like a 3x3, 5x5, nxn grid.

**Comment by wel97459** [comment]
My guess is access to this type of stuff will come with the addition of collections/arrays.

**Comment by shiftyscales** [comment]
The above issue was closed to merge it with this one. The above issue desired the ability to be able to write as well as read pixel data:

> The ability to create textures with logix (slowly over time) or modify existing textures such as drawing on them with a pen would be useful for complex programmatic effects and the forementioned style of note taking.
> 
> I'm not sure how the neos pipeline handles this kind of data so this may be a horrible idea! Replication wise I'm not sure how this would be handled, but my goal is to request things that are pie in the sky!
> 
> I'm also not sure how this would apply for different formats of images, but my understanding is they're converted to bitmaps at some point (witch is the goal of this request, modifying bitmaps).
> 
> PS: this is totally not so I can make a memory buffer that's not copy on write like a string is, no sir... That being said the ability to support a high data rate would not be turned down, and preferably making sure it still works for images not currently rendered.
> 
> PPS: this would also add support for image based heightmaps! (The static terrain kind, not the character drawing fuzz kind, see World Machine, I don't believe neos has an image to model pipeline right now).

**Comment by Frooxius** [comment]
Added nodes for this in 2021.8.29.1240! Thanks for request!

- Added Sample Texture2D UV node (under Assets) which will sample the texture color at given UV coordinate using bilinear interpolation (requested by @BlaXun | Ingo#6920, @Shifty#7944 and others, GH #365)
-- Note that the texture must be marked as readable in order to access its data and in format that supports CPU read (e.g. not block compressed)
- Added Texture2D Format node (under assets) which provides basic format and dimensions of input texture
- Added Get Texture2D Pixel node (under Assets), which allows getting specific pixel at specific mip level of a given texture
-- Note that the texture must also be marked as readable for this to work
-- If the position or mipmap are outside of range, clear color will be returned
