### ISSUE TITLE
Increase insertable precision on sliders in the inspector.

### ISSUE THREAD

**Issue by Psychpsyo** [Neos-Metaverse/NeosPublic#3852]
### Is your feature request related to a problem? Please describe.

I'm always frustrated when having to set a float slider in the inspector to a precise value since their text box only accepts values up to 2 decimal digits when typing them in by hand.
Anything that needs to be more precise than that is just impossible to set.

Since these sliders are used in fairly universal places, such as on ValueGradientDriver, there is cases where this much precision is needed.

### Relevant issues

Didn't find any.

### Describe the solution you'd like

Make the input field next to the slider respect finer precision when typing into it by hand instead of having it round the value when hitting enter.

### Describe alternatives you've considered

You can type the value you actually want into a different field that accepts more precision and then drag it over.
The slider accepts it that way but that's not really a good or intuitive solution.

**Comment by Beaned2000** [comment]
The odd thing is (going of the example of the ValueGradientDriver because its a good examplecomponent for this), you can actually type in the finer value into the component but **Visually** it rounds the value on the component while under the hood it actually keeps the value you typed in upto 7 decimals. so rather this is more of a visual bug in the inspector i would say.

so the solution here would be to make it so it displays the accurate value instead.

**Comment by Beaned2000** [comment]
upon further experimentation it seems like the slider for the gradientdriver under the hood actually has the proper value but instead it seems like it just ignores the actual slider value and just parses out the value from the textbox instead of taking the slider value as it really should. so it isn't only visual my bad
