### ISSUE TITLE
expand the editing ability inside user space

### ISSUE THREAD

**Issue by epicEaston197** [Neos-Metaverse/NeosPublic#3858]
### Is your feature request related to a problem? Please describe.

whenever I am modifying facets and user space and adding components and such I feel like it's such wasted potential I want to edit my avatar I want to create things inside my user space without having Builder permissions in the current world i'm in and Building Things and user space is the answer to that as I don't have access to World root

### Relevant issues

#3274

### Describe the solution you'd like

I want to be able to easily do Logics and editing inside my userspace

### Describe alternatives you've considered

maybe I could use a series of facets to equip tooltips but I don't know how to spawn things in my user space efficiently

**Comment by Beaned2000** [comment]
Your user space isn't meant to be used in such a way at the moment, if you don't have permission in a world sadly the only option right now is to start your own to edit your things in the way its intended. Issue #3274 should make the behaviour you want possible so i suggest to go and comment on there instead of making a new issue for this
