### ISSUE TITLE
Auto login disabled and low FPS

### ISSUE THREAD

**Issue by ghost** [Neos-Metaverse/NeosPublic#3873]
### Describe the bug?

Neos doesn't auto log me in and runs between 3-11 FPS

### Relevant issues

I skimmed them and didn't find any.  That doesn't mean they don't exist, it just means I couldn't find them.  My search string was just "FPS" though.  Also tried without mods with same result.

### To Reproduce

I have literally no idea

### Expected behavior

It works as it should with auto login and FPS at the normal rate.

### Log Files

Logfile is 45MB after running for 10 seconds, you sure you want the whole thing?  I can't even upload it here because this maxes out at 25MB!  Here have a sketchy link: https://www.mediafire.com/file/j4hrr7ni8flklnt/GIBSON_-_2022.1.28.1335_-_2023-04-03_06_34_10.log/file

### Screenshots

Not necessary as it's not a visual bug.

### How often does it happen?

Always

### Does the bug persist after restarting Neos?

Yes

### Neos Version Number

Beta 2022.1.28.1335

### What Platforms does this occur on?

Native Linux

### Did this work before?

Yes

### If it worked before, on which build?

Beta 2022.1.28.1335

### Additional context

None

### Reporters

IDK, I deleted my Discord because China controls it and the new privacy policy is even more abusive.

**Comment by Lexevolution** [comment]
This is likely due to the current cloud issues that have been happening for the past 48 hours. #3872
There's also fixes in there for all the issues (see [here](https://github.com/Neos-Metaverse/NeosPublic/issues/3872#issuecomment-1493576295) and [here](https://github.com/Neos-Metaverse/NeosPublic/issues/3872#issuecomment-1494167510)), but I'd first recommend trying to update Neos, as updates were pushed for some platforms.

**Comment by ghost** [comment]
Steam usually takes care of those updates as soon as there is an update marked available.

I can confirm this is working with your mod though and fixes the issues described.
