### ISSUE TITLE
RadiantUI new user welcome screen

### ISSUE THREAD

**Issue by Frooxius** [Neos-Metaverse/NeosPublic#683]
With the new RadiantUI dash coming up, one of the things I plan on adding is a "welcome wizard" screen, that will appear to new users and walk them through some of the initial setup for Neos. This will be a simple guided tour to make sure the essential things are working - think of the first time you setup a computer or your phone.

This should help alleviate some of the most common issues people have and give them a bit of time to get acclimated before jumping on.

There are a few things that it should likely contain (not in any particular order here):
- Audio input & out - the screen will help select the right microphone and make sure it's working
- Dash position/size (suggested by Zyzyl on Discord) - will allow selecting from a few presets (or a slider?) on how close/far and how big the dash should be so it's comfortable for the user
- Basic controls? Should show a graphic the controllers and their buttons. For screen users it could show warning that screen mode isn't fully ready yet
- Account registration/login - would be skippable, but would let users know that some things won't work if they don't log in
- Links to help - Discord, GitHub, Wiki, maybe Patreon, mention that Neos is in beta/early access
- Setup height? So avatars scale properly. See: https://github.com/Frooxius/NeosPublic/issues/656

Any other ideas as to what should be included that could help first time users? We want to leave actual interaction tutorials mostly to the MTC, but there might be a few more things.

**Comment by Abysmal2134** [comment]
Just going to mention that the basic controls graphic, should hopefully be accessible as a reference even after the tutorial, so that people can access it to as an easy reminder. Maybe even have the whole welcome setup be repeatable in case someone skips through it and needs to redo it?

Having an explanation for how to Scale your avatar and switch between mic setting would be nice too. Unless hovering over those facets shows brings up a tooltip or an option to open up an info panel.

When it comes to audio setup, it would be nice if it was possible for you to hear your own voice so that you can adjust your mic volume levels. 

Maybe besides links to outside sources of help, have links to the MTC world with an explanation of what it is before you get loaded there. Maybe even have a facet linking to it, that stays in one corner of your dash until you learn how to remove it or a set amount of time passes.

**Comment by TehTurk** [comment]
I would suggest having laser adjustments, some people might be used to more straight lasers vs curvy ones from most games. If it's a welcome screen I would go over all the settings that you'd normally want to do for a first time setup. Maybe hand or head for direction, speed etc.

**Comment by Frooxius** [comment]
Everything will be accessible afterwards as well. For the tutorials I'd like to add some kind of "Help / Knowledge Base" screen, which would allow browsing/searching tutorials and such.

Is the explanation on Scaling your avatar necessary for this screen? It's something that's toggled on later in game, that might be better left for the tutorial and it's not something I'd consider essential, as the user can get by without it.

It would definitely also have links to MTC and other information so the user knows what's going on.

@TehTurk Hmm that could maybe be added, but would the lasers be essential? If we add too many settings it might get too crowded/long. Though having a screen for some basic common settings/presets could work well (like the hand/head direction and such), where you can either leave defaults or tweak them or later tweak them on in detail in actual settings.

**Comment by Abysmal2134** [comment]
Since there would be a dedicated Help screen to serve as a wiki, then explaining scaling your avatar probably wouldn't be necessary in the initial setup.

Locomotion modes, on the other hand, are something that people should be aware of from the start, as well as the settings for smooth turning, POV turning etc.

Same for stuff like the respawn button and mute options might also fall into essential knowledge.

I can see how cluttering up the initial setup too much can lead to annoyance and skipping through it.

**Comment by TehTurk** [comment]
I would say yes, you want people to tweak or skip the process so they are aware of it and be able to adjust it later in terms of the lasers, basic stuff yes but lasers would also be an important one as the wiggly feel is very different for everyone. The Welcome Screen will be one of the first things they see and they should be aware of all the basic functionalities in some form.

**Comment by Zyzyl** [comment]
I expect the most common goal of new users will be to comfortably join and socialise with others. I'd suggest that the "Welcome screen" content be laser focused on doing that, while still providing quick access to extra tutorials if desired. Assuming this will usually be a one-time wizard which will take <10 min, I'd strongly recommend against making it skippable. People are impatient, but it will be far more frustrating to skip and then not know important things than to be forced through a concise tutorial.

To my mind an unskippable progression roughly along these lines would make sense:

- Dash welcome and comfort (size, scale, location) options, (account login?)
- Basic controls: lasers (2 presets, rigid vs. wobbly), opening / closing dash, context menus
- Basic comfort settings: head height, seated mode, snap/smooth turning, head vs. controller directed movement
- Mic / audio setup
- Locomotion modules, note available options may depend on the world
- Physical gripping, remote manipulation with lasers, equipping (a basic prop not a tooltip)
- Friends list + online, away, busy, invisible status
- Intro to social comfort / safety features (user volume, muting, respawn, block)
- Brief rundown of permissions (including kick/ban), note different worlds may be setup differently
- Intro to world joining / switching

I think that mostly covers the bare essentials so I think anything following could be recommended but skippable. Easy access to support and Discord links would be good. Many people will be interested in getting an avatar, so direction to a fleshed out MTC avatar room would be a good next step.

**Comment by Frooxius** [comment]
I don't think that we should really put the tutorials for locomotion, physical gripping and so on in there, that's the job of MTC and it would make the welcome wizard too long. This stuff is better shown anyway, rather than just displayed in text/images.

I'd say the dash comfort, mic/audio check, very basic controls (just a diagram and opening/closing the dash), height, some basic control presets and login should be all that's necessary to get the user setup.

Afterwards they can be redirected to MTC and follow tutorials.

**Comment by TehTurk** [comment]
Oh! I know we don't really have hyperlinks in the startup but I think a hyperlink to the disc would be a good idea. One thing I've found out is people don't have anywhere to voice themselves or get help so having something in some form is a good move.

**Comment by Frooxius** [comment]
Oh yeah, I'd definitely add those there. Discord, Wiki, GitHub, Patreon, maybe Steam, perhaps at the end of the wizard, if they need extra help.

**Comment by Enverex** [comment]
I think this thread highly overestimates the general attention level, or possibly intelligence of the random user. Anything that can be ignored, will be ignored. Anything that doesn't scream in the users face that that's what they need to do, will be overlooked. You **must** force users to do things the first time, else they will simply ignore it, gloss over it, or miss it accidentally. Users need to be walked through the basics, step-by-step, otherwise you will still have many users with no idea what they are doing and continue to claim everything is "too complicated" because they're immediately presented with the full array of Neos' interface(s).

A good recent example of a new user getting stuck would be this video - https://www.twitch.tv/videos/673896961 - I recommend grabbing a drink or something first because it takes them over 15 minutes to close the main menu (not helped by the fact the control diagram refers to it as a "Dash Menu" and I, even as an existing user, had no idea what that was).

**Comment by Frooxius** [comment]
Why does it overestimate it? The point of this screen is to pretty much force the user to go through a few basic steps initially so they know what to do and to make sure their audio and such is correct. Similarly how when you get a new phone and it walks you through basic setup before you can do anything else.

**Comment by Enverex** [comment]
No no, that I agree with. My point was not to make any assumptions about the user's technical aptitude at all. Assume that it's your luddite nan playing the game. Having people that you'd deem "non-technical" try and run through all this before it goes live would probably be a good idea, to see if they can actually follow it as having existing users run through it wouldn't really provide useful input due to existing knowledge bias.

**Comment by Frooxius** [comment]
Ah right! Yeah my goal is to pretty much gather observations of what do new users mostly get stuck on. The audio device being wrong is one thing that comes up commonly. Not knowing what buttons do or how to close stuff is another as well, although the MTC tutorial will do the main part there, by taking away everything, except for the few controls that they're currently learning (moving, grabbing and so on).

**Comment by shiftyscales** [comment]
The welcome screen has been implemented for a while, and has been fairly successful in funneling new users towards the MTC where they can take on more detailed tutorials past the initial setup phase offered by the welcome screen.
