### ISSUE TITLE
No way to tell lasers apart with lack of color

### ISSUE THREAD

**Issue by Hayden-da-Serg** [Neos-Metaverse/NeosPublic#705]
While experimenting with various color-blindness filters, it came to my realization that some laser color changes aren't visible in different types of color-blindness, suck as with red-green, the difference between the Red laser to grab, Green laser for custom interactions, or the normal white laser is next to none. While the curser icons do help, they're impossible to see from a distance and not at all easy to see at a glance.
I also noticed that the "Show Interaction Hints" option in settings now does nothing, I'd personally recommend restoring the functionality of this option by showing text or an icon above the laser base depending on the interaction context.

**Comment by Frooxius** [comment]
What would help in this case to make them more distinguishable in this scenario? If I understand correctly with red-green blindness the the color options are limited pretty much to yellow and blue, so there's not enough colors to cover all the scenarios.

The interaction hint could help, I could perhaps even show the cursor at the origin of the laser too so it's up close.

**Comment by shiftyscales** [comment]
I think having the interaction text return could be a good idea. It's a very clear way to indicate what your laser will do at any moment, and can very literally be translated when translations become a functionality that's implemented down the line, too.

The icons are only really beneficial if a user is aware of what the icons mean ahead of time after they've already learned what the interactions do.

**Comment by InsaneGrox** [comment]
Hmm, just gonna leave my two cents, maybe have the lasers have different brightnesses instead of just having color differences.

**Comment by KierDran** [comment]
What? I didn't know the lasers were different colors? (I am colorblind BTW)

**Comment by KacperLa** [comment]
Hello!
I also have trouble seeing the lasers. I am low vision and the lack of contrast makes it impossible to see the laser against light backgrounds.  Currently, I use a tool that a friend helped me make that upon pressing changed the laser to be opaque and black and increases the radius of the mesh a tad. by doing this I mostly lose the context color of the laser but I can't see that anyways. 

Having contextual info at the base of the laser near the hand would be a great addition(with the ability to change the font size). Also, the ability to set the laser to have an inverse color material would be amazing as well. (by inverse color I mean that the laser is translucent but instead of letting the normal color of whatever is behind it from the pov of the user the color would be inversed)

**Comment by Frooxius** [comment]
In build 2020.7.11.1366 there are now some basic brightness patterns on the lasers, let me know if it helps a bit. Hints/labels are coming in later.

**Comment by KierDran** [comment]
The laser dash patterns are very nice, I can easily tell them apart.

**Comment by Hayden-da-Serg** [comment]
While it is now definitely easier to tell them apart, knowing what pattern means what does require previous knowledge, I did see that it was stated that interaction hints will come in a future update so I'll keep this open for the time being.

**Comment by shiftyscales** [comment]
Closing this issue as the underlying issue was resolved. There are both cursors, and laser patterns to distinguish the function of the laser alongside its color.
