### ISSUE TITLE
Users respawning breaks a lot of on spawn events

### ISSUE THREAD

**Issue by Ruikio** [Neos-Metaverse/NeosPublic#769]
There are some things that trigger and are meant to stay on a user for the purpose of a world can break if the user respawns. Having a node for, say "On Respawn", sounds like it could make a lot of headaches go away. Would also have the flexibility to be used in conjunction with things like say if a user respawns when they enter a collider, it'll teleport them to somewhere else or make text appear.

**Comment by shiftyscales** [comment]
This sounds like it could be an implementation issue, possibly, @Ruikio. What is the context for which things are breaking? There isn't actually a 'respawn' mechanism as such (and hence no direct way to make an 'on respawn' node). All respawning does is delete the user slot.

The cases you had specified sound like things that could already be made using the existing tools.

I could see potential use for a 'User Spawned' node similar to 'User Joined' but firing every time a user is spawned- but again, that's an implementation issue, because you could also just fire once with 'User Joined' and use that to set a value user override for that session that is controlling whatever you wish to keep persistent between respawns.

**Comment by Frooxius** [comment]
What exactly are the things that get broken by the user respawning? You mention that it breaks a lot of them, but I'm not quite sure what they are.

I wouldn't add "OnRespawn" node, since that's a bit too specific, although more general "OnSpawn" (that doesn't exclude the original spawn) could perhaps work. However the specific will have to depend a lot, since there's not actually any special "OnSpawn" event in the system, it's a behavior handled by components in the world.

**Comment by Toxic-Cookie** [comment]
How about when a user slot is deleted, send an impulse to a "OnUserSpawned" Node along with the user that spawned when their slot is added to the root?

**Comment by RueShejn** [comment]
It sounds like you want the "on loaded" logix node it should pulse once the users avatar is respawned or when something is spawned from the inventory (and has the node attached) if im not mistaken
Also like shifty and froox stated we need a more detailed explanation to help any further.

**Comment by TehTurk** [comment]
A node like this has been added in #1374. Please remake a newer issue outlining more details if needed.
