### ISSUE TITLE
Unexpected Window Behaviour when taskbar is moved

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Neos-Metaverse/NeosPublic#873]
When in Screen mode the Window behaves unexpectedly.

Reproduction:
1. Have taskbar at the top and use windowed mode of neos.
2. Start neos in screen mode
3. Move taskbar to the sideto move the neos window
4. move taskbar back to the top
[GIF of it](https://i.imgur.com/wUyHOVM.gif)
At the end the window snaps back to the origin point underneath the taskbar if the taskbar is ontop.

It's possible to still get the window to stay put by:
1. Move the taskbar
2. maximize NEOS window
3. move taskbar back to origin

The window is now maximized and stays put.
Edit: Clarification

**Comment by Frooxius** [comment]
We'll have to report this one to Unity, as this is fully handled by them, rather than by Neos. It'll take some time to make a repro case for them, so I'll have to chunk this at low priority.

If anyone could replicate this with empty Unity project using the latest version of Unity (2019.4.x) and send them a bug report that could help speed it up.

**Comment by 3x1t-5tyl3** [comment]
This was reported to unity a while ago and I deemed it unnecessary to include here aswell as the future plan (as far as I'm aware) is to move away from unity anyways.
