### ISSUE TITLE
Camera anchors eject cameras at random intervals

### ISSUE THREAD

**Issue by Ruikio** [Neos-Metaverse/NeosPublic#886]
You can have a camera in an anchor and after an unspecified amount of time, it'll eject the camera somewhere else randomly in the world.

I will try to time this to better replicate results.

**Comment by Frooxius** [comment]
What exactly happens to the camera when it's ejected? Does it switch to a different mode? Can this be replicated in some way?

**Comment by TehTurk** [comment]
I've run into this and I think this is occuring due to possibly changing the camera view, or closing the window. Camera will default to root sometimes if your not paying attention to where your pointing it, or your switching worlds/directions. If this issue still persists do reopen or remake the issue. Thanks!
