### ISSUE TITLE
Feedback: World UI Tab

### ISSUE THREAD

**Issue by TehTurk** [Neos-Metaverse/NeosPublic#997]
So after playing with it for a little bit, I have some feedback on the world tab as I've had some time to just use it "generally" enough to get a good feel of it. Not very much of there's a Problem, but some things I've personally identified and should make get another look or addressed before we move away from the World UI Changes roadmap wise.

Couple issues I've found:

- It's very Busy, while complex, it doesn't allow for a good feel of I look at the menu, I find the world I want and go to it. One feedback I've gotten from users who's tried out Neos and don't come back is Neos is Complex. While we and many others can make more simple ui, the baseline should be good for new users. Oft not we will get users who turn off their brain and just "play" so they won't really look/think what they are doing. 

- Looking at Active Sessions that I can readily join don't seem as distinct, yes there are indicators on the world panels themselves, but it feels and looks too small at a glance (On Index myself) and you have to pay attention/think. For more Social Interactions people will not be thinking about the usage but more so it's simplicity.

- I find myself never closing the custom tab, it's always open, affecting my active search, refining what I want when I want it, While I understand we have categories, I feel like they aren't used to often and would feel better as a suggested tag/common tag type of system. 

One thing I was kinda hoping with the World UI to make myself( I will once the WorldListUI gets User Assignment so it doesn't fire on everyone in the session), but maybe this is better as a default, is that there are 3 rows,

Friend Sessions
Active Session
Worlds

Active Categories are Nice as in Social/Games/Tutorial etc in some form after some usage/experience I think it would be more benefit to have them as a separate list category like above ^ 

Friend Sessions
Active Sessions
Worlds
Social
Games
Tutorial
etc

While it does separate it up, it makes more distinct and you can see what's going on for the most part. 

Thanks for reading and hopefully this brings up some considerations. If anyone else has feedback feel free, I decided to post this in the github, vs the Discord as a means to kinda have everything somewhat layered and more careful considerations are posted.

**Comment by Frooxius** [comment]
Thanks for the feedback. I think I'd need more information though to see how to best address the things:

- Why exactly do you feel it's busy? It has been designed to be much simpler to use, especially for new users. Did the user who didn't come back mention why they found the new World UI complex (either directly or indirectly)? 

- Active sessions can be made a bit more distinct. One potential solution would be to add grouping headers to the list, so opened worlds, active sessions and regular worlds  would each be grouped under appropriate header, that would separate them vertically as well. Do you feel this would help?

- The categories are designed for quick access to common search and filtering presents, particularly for new users and as such are designed to be simple 1-click use. If you're advanced user you might not use them as often, but I don't think removing them would be a good idea. 

They cannot be replaced by tag suggestion, because they represent a more complex set of tags and filtering/sorting parameters. Even if so, that wouldn't help with discoverability, as new and existing users wouldn't know how to quickly access those common groups of items.

They can be grouped a bit in the list perhaps, but I'm not sure what would be best grouping that wouldn't mess with the order of the most interesting/important ones being at the top. Perhaps just adding horizontal separators could help a bit.

**Comment by shiftyscales** [comment]
I think it would be very beneficial to segregate open sessions, active sessions, and unpopulated worlds with a header above each that labels them as such as you've suggested, @Frooxius.

That would effectively cover the three main states a world can be in:
- a session that you have opened/have joined
- a session that is open that you're not in
- a world that has no active users/sessions

I've personally found that I very seldom use the custom search at all, primarily I use either 'Everything', 'Active Sessions', or 'Friend Sessions'. This is a good thing I think- a majority of the use-cases, at least for myself, are already covered by the existing preset searches/filters, and I think this might be the case for other users too.

I think the 'Active Sessions' preset search should also have a minimum user filter set to 1 to effectively exclude empty headless sessions, as without any other users in them, 'active' is a bit of a misnomer/is misleading.

**Comment by TehTurk** [comment]
Anytime! I figured you'd have questions so I tried to not to get too much into specifics. I agree it's alot simpler, but there's also alot of choice, alot of options. Choice Paralysis is a thing.
,
 Sorry, it's not a specific user persay, it's just an general sentiment I've encountered, I've haven't quite re-encountered the same people that made those sentiments.

Group Headers would be a lovely addition. This would also counteract the busy aspect of the my initial point. If they are added, I at least suggest that all 3 are visible on the main page, and maybe expandable/minimizable in some form. This would allow people to quickly find what they are looking for and not having to scroll up or down to locate them. 

The other thing I've noticed is that Active Sessions is a Combination of Public + Friend Sessions, what if I want to say join someone who isn't my friend? In those cases it makes it seem like meeting new people discovery wise is tricky as it leans more to your friends sessions being seen first. 
This is why if we do add them I suggest the Addition of Active, Friends, Open, Empty, normally you'd just click on the category to the left, but it's an extra step to see more immediate information that you want to see when world searching/hopping. 

Hmm okay, I considered this in mind, but I figured less clicks would be more beneficial 🤔 

I was also quickly reviewing and noticed is there a reason that "Owner is User" and "Owner is Group" Is distinct? Would it make more sense if your searching a User or Group you just type in the respective Group or User?

**Comment by Frooxius** [comment]
2020.9.9.214 now has some of the things addressed. ActiveSessions now filters out completely empty sessions and has a new category. 

I'm not sure where exactly would be too many choices? Are you referring to the categories? Or too many worlds shown at once? Or something else? 

I'll try to add categories soon, I do plan on having them minimizable. But I need to think some of the grouping mechanisms first, because I'd like to later generalize them into other browsers as well, like workshop, inventory, file browser and others.

I think that filtering worlds where none of the people are your friends is a bit niche, so that'll probably get added into the Custom filters. The filtering engine supports maximum friends, so I could wrap that into a checkbox. I don't think having a special category for this would be too beneficial.

And yes, Owner Is User and Owner Is Group are separate, because you can have a group that has same name as user and you need to be able to differentiate.

**Comment by TehTurk** [comment]
No problem! Seriously Thanks as always Froox! Happy to help how I can :) if there's anything I can do to make it easier always let me know. 

Hmm when I made that comment I was going to say a mix of everything 🤔, while distinctly you can click on Categories/Common Tags on the Left to choose and makes it easier for new users, why have a choice when you can have everything within the list itself and also detailed. It would be expandable if people wanted to see more , why not just have Headers where they are Categories are split within the list itself, it comes off more simple and intuitive. Unless you just explained this and I misunderstood, I'm a little unsure one what you meant by adding categories.

Ah that'd still be a good thing :), i think the recent suggestion of adding custom searches as categories in the recent issue Shifty made on the suggestion of Hamish would go hand in hand with this. 

Ah okay! I was surprised there was a distinct choice of it and just figured there wasn't some sort of easy search tag like -G or -U instead of a option.

**Comment by shiftyscales** [comment]
Polaris has noted that occasionally the world browser can feel 'sluggish'- primarily this comment seemed to stem from the delay while fetching results (sometimes up to five seconds, but usually no more than one to two).

In particular- this seems to occur when switching filters, and especially so for the first time the world browser is opened/the first time it needs to refresh/pull a bunch of results that aren't yet cached.

Something which could potentially help this would be having an adjustable/custom page-size to limit the number of results that are shown?

**Comment by Frooxius** [comment]
@TehTurk One of the main goals is so when new users come in and they don't know what's what and are clicking things, they have a higher chance of ending up in a populated sessions. The worlds that have people in them show up higher in the list.

Headers instead categories wouldn't work well, because each of the categories is potentially huge, meaning you'd have to scroll way too much to get to the next one.

Tag is a possibility for distinguishing things, but it makes things complicated - you need to know it in advance. Doing something like `User: Username` or `Group: Group name` could work, but I'll probably do that one for the main search instead. 

@shiftyscales That sounds more like a networking issue, that's not something we can do much about. The default list fetches only 50 items. The items are cached on the server and the server response typically happens under 200 ms, often even for non-cached results too. If there's big delay like that caused by network and such, returning fewer things isn't going to help, because it's not the bottleneck.

Don't really know why exactly it would be that sluggish for them, could be lots of different things. We'd need to profile it on their end somehow.

**Comment by Earthmark** [comment]
One piece of feedback I saw recently, there are two icons on the worlds browser that are identical accept for color differences, if possible having two different icons would mitigate confusion that may arise due to color blindness.

**Comment by Earthmark** [comment]
That user also didn't realize the icon in the top left was a button on the world dialog.

From that I'm curious what the mini dialog provides that the big one does not? It has compressed buttons, but it seems like the page that describes the world would be useful to a new user, or the active list would be useful, however that information is hidden unless you expands the worlds menu.

**Comment by TehTurk** [comment]
Hmm okay, so here's another round of stuff I've found! and Some of these are from @Gearbell in the discord with some of my additions sprinkled on too. 

**Gearbell:**
<img src="https://user-images.githubusercontent.com/26357446/93116478-4e229e00-f68b-11ea-9b46-ea1f8fce7904.jpg" width="360" height="180"><img src="https://i.imgur.com/zErXNYy.jpg" width="360" height="180">
- Close World [X] Should also be in the window when you focus a world. same thing when the panel is fully expanding, I can only close at initial selection 
- Focus for the Focus World while technically true, fits, it's not the most intuitive word wise. Maybe Open? Jump? ReOpen? (This is more suggestion to make it less thinky of the user and more comfy)
- Would there be the possibility of some sort of History Tab? 
- Creating a New Session is Un-intuitive atm, are you open for suggestions?

**Turk** 
<img src="https://i.imgur.com/rb9vqrt.png" width="360" height="180"><img src="https://i.imgur.com/7jHZGnw.png" width="360" height="180">
- So one thing I've noticed is going by how my eyes and hands are tracking on the screen, it's a little jarring/confusing that when you focus and click something on the right side of the screen, that it appears on the left, would it be possible to have the Modal show the sessions on the right? Because when you focus further on the screen it's on the top right, but then all the extra sessions are on the left. It doesn't flow with how your attention is focused on the screen. 

- Also, on the Fully Focused Screen, the X should be an < because it's not closing the window, it's just returning. While yeah it's not a big thing, it's small things that add up for the presentation. <img src="https://i.imgur.com/jaTLLu7.png" width="90" height="45">


- This icon does not indicate what it does clearly, I suggest putting something like a little circle with an [i] inside to convey that this is an increased info panel.<img src="https://i.imgur.com/C6DDubt.png" width="90" height="45">

- Also I find myself clicking on Users Names while in the World Tab when looking at who is in a session to message them, is this on the docket or just never got added :O, it'd be interesting if each name had a FriendLink Component on it so when I click their name I can message or add that person in question. 

Some of these aren't objective problems, but in the context of this it's more UI Flow/Feel vs having it be objective. But these are my takeaways as you have to deal with how people are feeling/thinking when they are doing some of these actions and takes the burden off the user as good UI should do.

**Comment by mralext20** [comment]
Another thing I noticed: it is not obvious at all that on this view: [!image](https://camo.githubusercontent.com/dae1d35a85ebc3785e2bb03105bd359de8f51dfc/68747470733a2f2f692e696d6775722e636f6d2f7a4572584e59792e6a7067) you can click on the Users header to see the session description.

**Comment by mralext20** [comment]
This issue has not been actioned in 9 months, if these pain points still exist please open individual issues for each problem.

**Comment by TehTurk** [comment]
I would like to preface we shouldn't be making it a habit to close issues if they haven't been actioned on within past months because by doing so alot of issues would be closed. So please note to ask in the future to ask if this issue is okay to close to make it easier to follow up on. I'll try to make a more fresher issues with a checklist that goes down the issues individual but this is one of those issues where doing individual little issues might prove more problematic.
